### ISSUE TITLE
CRITICAL - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'inventory'

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Bitmessage/PyBitmessage#1011]
just deleted my trash messages (probably around 150) and got this (A).

this the first time, I am not quite sure what the causing action is

BM version: current [0.6.2 branch](https://github.com/Bitmessage/PyBitmessage/tree/v0.6)

(A) 
 CRITICAL -   File "/George_Bush/PyBitmessage-0.6/src/bitmessageqt/__init__.py", line 4401, in addressChanged
     shared.inventory.flush()
 
 CRITICAL - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'inventory'

**Comment by PeterSurda** [comment]
Thanks, I need to test the fix.
