### ISSUE TITLE
error: uncaptured python exception, closing channel <network.tcp.TCPConnection connected

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [Bitmessage/PyBitmessage#1012]
I am seeing: (A)

0.6 branch, with [this](https://github.com/Bitmessage/PyBitmessage/commit/cba749088a297327175af68613ca1944275d2b8b) commit

on request further info is available

(A) 

Number of threads: DELETED

error: uncaptured python exception, closing channel <network.tcp.TCPConnection connected someIPhere1:32976 at 0x7fe1154fc790> (<class 'socket.error'>:[Errno 110] Connection timed out [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|read|108] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|handle_read_event|651] [/Saddam/PyBitmessage-0.6/src/network/tcp.py|handle_read|167] [/Saddam/PyBitmessage-0.6/src/network/tls.py|handle_read|90] [/Saddam/PyBitmessage-0.6/src/network/advanceddispatcher.py|handle_read|76] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|recv|582] [/usr/lib/python2.7/ssl.py|recv|756] [/usr/lib/python2.7/ssl.py|read|643])
error: uncaptured python exception, closing channel <network.tcp.TCPConnection connected someIPhere2:47604 at 0x7fe114ea1910> (<class 'socket.error'>:[Errno 110] Connection timed out [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|read|108] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|handle_read_event|651] [/Saddam/PyBitmessage-0.6/src/network/tcp.py|handle_read|167] [/Saddam/PyBitmessage-0.6/src/network/tls.py|handle_read|90] [/Saddam/PyBitmessage-0.6/src/network/advanceddispatcher.py|handle_read|76] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|recv|582] [/usr/lib/python2.7/ssl.py|recv|756] [/usr/lib/python2.7/ssl.py|read|643])
error: uncaptured python exception, closing channel <network.tcp.TCPConnection connected someIPhere3:8080 at 0x7fe114b52150> (<class 'socket.error'>:[Errno 110] Connection timed out [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|read|108] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|handle_read_event|651] [/Saddam/PyBitmessage-0.6/src/network/tcp.py|handle_read|167] [/Saddam/PyBitmessage-0.6/src/network/tls.py|handle_read|90] [/Saddam/PyBitmessage-0.6/src/network/advanceddispatcher.py|handle_read|76] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|recv|582])
error: uncaptured python exception, closing channel <network.tcp.TCPConnection connected someIPhere4:8444 at 0x7fe0d0d22850> (<class 'socket.error'>:[Errno 110] Connection timed out [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|read|108] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|handle_read_event|651] [/Saddam/PyBitmessage-0.6/src/network/tcp.py|handle_read|167] [/Saddam/PyBitmessage-0.6/src/network/tls.py|handle_read|90] [/Saddam/PyBitmessage-0.6/src/network/advanceddispatcher.py|handle_read|76] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|recv|582])
error: uncaptured python exception, closing channel <network.tcp.TCPConnection connected someIPhere5:8444 at 0x7fe114d59290> (<class 'socket.error'>:[Errno 110] Connection timed out [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|read|108] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|handle_read_event|651] [/Saddam/PyBitmessage-0.6/src/network/tcp.py|handle_read|167] [/Saddam/PyBitmessage-0.6/src/network/tls.py|handle_read|90] [/Saddam/PyBitmessage-0.6/src/network/advanceddispatcher.py|handle_read|76] [/Saddam/PyBitmessage-0.6/src/network/asyncore_pollchoose.py|recv|582] [/usr/lib/python2.7/ssl.py|recv|756] [/usr/lib/python2.7/ssl.py|read|643])

ERROR - someIPhere6:8080 error: 2, Server full, please try again later.

**Comment by PeterSurda** [comment]
thank you for all this reports, it's very helpful

**Comment by PeterSurda** [comment]
This should be fixed now.
