### ISSUE TITLE
Segfault on Centos7

### ISSUE THREAD

**Issue by bentterp** [Bitmessage/PyBitmessage#1016]
```
[bent@guestlaptop PyBitmessage]$ ~/PyBitmessage/src/bitmessagemain.py
Loading existing config files from /home/bent/.config/PyBitmessage/
Using default logger configuration
2017-06-22 08:40:17,916 - ERROR - /home/bent/.namecoin/namecoin.conf unreadable or missing, Namecoin support deactivated
Segmentation fault (core dumped)
[bent@guestlaptop PyBitmessage]$ rpm -qa PyQt4 openssl-compat-bitcoin-libs python
openssl-compat-bitcoin-libs-1.0.2f-1.el7.x86_64
PyQt4-4.10.1-13.el7.x86_64
python-2.7.5-48.el7.x86_64
[bent@guestlaptop PyBitmessage]$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core) 
[bent@guestlaptop PyBitmessage]$ 
```

This is what shows in the audit log:
```
type=ANOM_ABEND msg=audit(1498113618.334:12909): auid=4994 uid=4994 gid=4994 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3591 comm="bitmessagemain." reason="memory violation" sig=11
```

The segfault also happens with SELinux disabled.

**Comment by PeterSurda** [comment]
It looks like you have to build your own python that either uses statically linked openssl, or is linked during build time against the one that comes with openssl-compat-bitcoin-libs.

**Comment by PeterSurda** [comment]
Well I tried different approaches but I can't find out how to fix it. Own python build still can't load the ssl library internally, and trying modify and rebuild the RPM that comes with centos didn't fix the crash. Someone who deals with redhat/centos needs to find out how to fix it. In the meantime, you can use Fedora, there are no special requirements there, they fixed the OpenSSL compatibility issues already.
