### ISSUE TITLE
error: uncaptured python exception, closing channel

### ISSUE THREAD

**Issue by g1itch** [Bitmessage/PyBitmessage#1024]
Got the following strange output in console with latest code:
`error: uncaptured python exception, closing channel <network.tcp.Socks5BMConnection localhost:9050 at 0x7fdae80a5290> (<class 'network.socks5.Socks5Error'>:Connection refused [/usr/lib64/python2.7/site-packages/pybitmessage/network/asyncore_pollchoose.py|read|106] [/usr/lib64/python2.7/site-packages/pybitmessage/network/asyncore_pollchoose.py|handle_read_event|639] [/usr/lib64/python2.7/site-packages/pybitmessage/network/tcp.py|handle_read|167] [/usr/lib64/python2.7/site-packages/pybitmessage/network/tls.py|handle_read|91] [/usr/lib64/python2.7/site-packages/pybitmessage/network/advanceddispatcher.py|handle_read|85] [/usr/lib64/python2.7/site-packages/pybitmessage/network/advanceddispatcher.py|process|51] [/usr/lib64/python2.7/site-packages/pybitmessage/network/socks5.py|state_pre_connect|89])
error: uncaptured python exception, closing channel <network.tcp.Socks5BMConnection localhost:9050 at 0x7fdae80a5390> (<class 'network.socks5.Socks5Error'>:Connection refused [/usr/lib64/python2.7/site-packages/pybitmessage/network/asyncore_pollchoose.py|read|106] [/usr/lib64/python2.7/site-packages/pybitmessage/network/asyncore_pollchoose.py|handle_read_event|639] [/usr/lib64/python2.7/site-packages/pybitmessage/network/tcp.py|handle_read|167] [/usr/lib64/python2.7/site-packages/pybitmessage/network/tls.py|handle_read|91] [/usr/lib64/python2.7/site-packages/pybitmessage/network/advanceddispatcher.py|handle_read|85] [/usr/lib64/python2.7/site-packages/pybitmessage/network/advanceddispatcher.py|process|51] [/usr/lib64/python2.7/site-packages/pybitmessage/network/socks5.py|state_pre_connect|89])`

However BM connects to network and receives messages.

**Comment by PeterSurda** [comment]
This is another overly dramatic log entry. I fixed it locally yesterday and will commit it in the next day or two.
