### ISSUE TITLE
Bitmessage_x64_0.6.2.,exe uses the 100% of 1 core on Windows 10

### ISSUE THREAD

**Issue by marcomarsala** [Bitmessage/PyBitmessage#1069]
Bitmessage_x64_0.6.2.exe on Windows always uses 100% of 1-core when idle. The whole GUI is slow and unresponsive. Objects to be synced is 0.

**Comment by PeterSurda** [comment]
Try the development snapshots: https://bitmessage.org/download/snapshots/win64/

**Comment by PeterSurda** [comment]
Should be fixed by now, haven't heard about this appearing recently.
