### ISSUE TITLE
signed git tags

### ISSUE THREAD

**Issue by adrelanos** [Bitmessage/PyBitmessage#108]
It would be nice if you could provide signed git tags for new releases.

**Comment by bashrc** [comment]
+1 This is pretty straightforward to do.

**Comment by PeterSurda** [comment]
I have been signing pgp commits [in my fork](https://github.com/mailchuck/PyBitmessage/releases/tag/v0.5.0) for a while. I screwed up signing the tag, but I'll know how to do it next time. I'm using key 53FBF089. I'll have a new key next week, I'll make the appropriate announcements.

I kindly request people who make pull requests to also sign their commits.
