### ISSUE TITLE
Can't compile on Windows10

### ISSUE THREAD

**Issue by asrod** [Bitmessage/PyBitmessage#1080]
While I installed the OPENSSL and configed the system enviroment, still have the error"Couldn't find and load the OpenSSL library. You must install it"

**Comment by PeterSurda** [comment]
Here are the instructions for building on Windows: https://docs.google.com/document/d/1XcPtVLBis7t_dyZzPh0h__Ve2iR8XAOsMaO7eKeAu5Q/edit

There are also daily binaries for win32 and win64 platforms available: https://bitmessage.org/download/snapshots/
