### ISSUE TITLE
"Mark all messages as read" causes critical error

### ISSUE THREAD

**Issue by g1itch** [Bitmessage/PyBitmessage#1081]
Hello!

I have 346 messages in `[chan] bitmessage` shown as unread. When I select "Mark all messages as read" context menu this causes PyBitmessage crash with many unicode characters dumped into console and finally the following messages:

> Here is the actual error message thrown by the sqlThread: too many SQL variables
CRITICAL - This program shall now abruptly exit!

So I probably have [SQLITE_MAX_VARIABLE_NUMBER](https://www.sqlite.org/limits.html#max_variable_number) < 999 in my system, but it seams there is no easy way to check the exact value.

[The source](../blob/v0.6/src/bitmessageqt/__init__.py#L2536)

**Comment by PeterSurda** [comment]
Thanks. I thought I fixed that. I think I should create a new function over sqlExecute which would handle this limit.

**Comment by reelsense** [comment]
What version are you using @g1itch ?

**Comment by g1itch** [comment]
Latest PyBitmessage commit, Python 2.7.12, sqlite 3.19.3

**Comment by g1itch** [comment]
Hmm, I don't understand this:
`if i % 999 == 999:`

It seems to be always False

**Comment by PeterSurda** [comment]
good catch.

**Comment by PeterSurda** [comment]
Fixed in 80fdb08f0369a86e4e65b740c0457b467fdff416
