### ISSUE TITLE
hang on urlencoded utf8 text in message

### ISSUE THREAD

**Issue by sss123next** [Bitmessage/PyBitmessage#1119]
`https://ru.wikipedia.org/wiki/Opus_(%D0%BA%D0%BE%D0%B4%D0%B5%D0%BA)`
this link inside message cause pybitmessage to hang

**Comment by PeterSurda** [comment]
Thanks, I'll look at it.

**Comment by g1itch** [comment]
And it seems to hang [here](/blob/v0.6/src/bitmessageqt/safehtmlparser.py#L104)

**Comment by PeterSurda** [comment]
fixed in f870bcc6f7bc03ae4fa4380aa8647c60d44ec190
