### ISSUE TITLE
[request] fresh windows builds

### ISSUE THREAD

**Issue by sss123next** [Bitmessage/PyBitmessage#1120]
please post fresh windows nightly builds with recent url parser bugfix.

**Comment by g1itch** [comment]
Do not hurry. f870bcc didn't resolve the issue.

**Comment by PeterSurda** [comment]
Should be up now.

**Comment by sss123next** [comment]
where can i find it ?
i have difficult to do it myself, building something for windows is pain (

**Comment by PeterSurda** [comment]
https://bitmessage.org/download/snapshots/

**Comment by sss123next** [comment]
thank you for quick fix and quick response.

**Comment by sss123next** [comment]
unfortunately latest builds for windows does not work.
looks at screenshot

https://imgur.com/a/wMKMV

nothing in console.
but i have similar problem when tried to build myself with outdated pyqt4 binary package.
in my case it was absent QSetting class member...

**Comment by PeterSurda** [comment]
You're right, it doesn't work.

**Comment by PeterSurda** [comment]
I refreshed today's dailies with a fix, can you try now please?

**Comment by sss123next** [comment]
now it works, thank you.
