### ISSUE TITLE
Can't add entries to black list using Add Entry button

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1138]
@g1itch:

Came over in bitmessage chan:

Unhandled exception
Traceback (most recent call last):
  File "PyBitmessage/src/bitmessageqt/blacklist.py", line 59, in click_pushButtonAddBlacklist
    if self.NewBlacklistDialogInstance.ui.labelAddressCheck.text() == _translate("MainWindow", "Address is valid."):
AttributeError: 'AddAddressDialog' object has no attribute 'ui'

------------------------------------------------------
Can't add entries to black list using Add Entry button
is anyone experiencing the same problem?

**Comment by g1itch** [comment]
Hmm, I see the source. Fortunately `blacklist` module is not part of merged `ui-refactoring` branch, so this is not my mistake. Testing patch now.

**Comment by PeterSurda** [comment]
odd I haven't had this problem before

**Comment by g1itch** [comment]
7800272

**Comment by g1itch** [comment]
Excuse me, part of it is mine. After dialog refactoring this code started to fail because it relies on old dialog members.

**Comment by PeterSurda** [comment]
thanks
