### ISSUE TITLE
Bitmessage Version 0.6.3.2 upgrade Error

### ISSUE THREAD

**Issue by Liranus** [Bitmessage/PyBitmessage#1142]
Dear´s

I upgrade my Bitmessage on Debian to Version 0.6.3.2. Get following Error on Terminal

(process:1486): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

and

(python2.7:1486): GConf-WARNING **: Client failed to connect to the D-BUS daemon

Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Qt: Session management error: None of the authentication protocols specified are supported
2018-02-19 14:08:36,971 - ERROR - /root/.namecoin/namecoin.conf unreadable or missing, Namecoin support deactivated
2018-02-19 14:08:45,290 - WARNING - No indicator plugin found
2018-02-19 14:08:45,306 - WARNING - No notification.message plugin found
2018-02-19 14:08:50,307 - WARNING - No notification.sound plugin found

Anybody here who can help me to fix it?

**Comment by PeterSurda** [comment]
I don't recommend runnig it as root. Please follow the compiling instructions:

https://bitmessage.org/wiki/Compiling_instructions

In particular the section about `checkdeps.py`.

However, the logs that you posted aren't anything critical. I regularly test PyBitmessage on Debian 8 and 9. If it's otherwise running then just ignore them. Running the build script may get rid of some of them but it isn't very important.

**Comment by Liranus** [comment]
First let me say thank you for your fast answer. Yes, Bitmessage is running very well. About checkdps.py

Here is the LIST

It looks like you're using Debian. It is highly recommended to use the package manager
to install the missing dependencies.
Missing mandatory dependencies: setuptools
Missing optional dependencies: pyopencl
If you install pyopencl, you will be able to use GPU acceleration for proof of work. 
You also need a compatible GPU and drivers.
You can install the missing dependencies by running, as root:
apt-get install python-pyopencl python-setuptools

Do i need this?

**Comment by PeterSurda** [comment]
You don't need these, it will run fine without them. The only thing I would check is that the C PoW can be built, which checkdeps cannot verify without setuptools being installed. These requirements are a C++ compiler and SSL headers:

`apt-get install build-essential libssl-dev`

The module will autobuild if it's missing, assuming the requirements are installed.

Installing setuptools may make the whole process more clean and will allow some notifications plugins to load but again it isn't necessary, if you're happy with it, leave it as it is.

Hopefully soon there will be Debian packages which will make the process even easier.

**Comment by Liranus** [comment]
Dear Peter.

Thank you for your answer. The C PoW -> apt-get install build-essential libssl-dev -> was installed.
I will not install both others. Thanks for your detailed explanation. Problem solved.

Best Regards and have a nice day.
