### ISSUE TITLE
Virustotal detection

### ISSUE THREAD

**Issue by mainsight** [Bitmessage/PyBitmessage#1144]
Hey there,

Thanks a lot for great software which helps us to be secure :wink: 

Current issue is [4 AV detections by virustotal service](https://www.virustotal.com/#/file/e714337ac069b06aa5ba66cc37c55ebf6da0546838e96850818474544742fe58/detection)

Any ideas?

**Comment by PeterSurda** [comment]
It shows up every now and then. It's the pyinstaller bootloader triggering this, because some malware also uses it.

**Comment by PeterSurda** [comment]
I already had tried to contact both of these AV vendors in the past. One of them has the false positive submission mailbox full, and the other one does not provide a method to submit false positives.
