### ISSUE TITLE
Connection to local namecoind at startup

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1146]
When you launch PyBitmessage first time,
it says 'Bitmessage won't connect to anyone until you let it.'
But it seems that it has already attempted to connect local namecoind.

This is inspected by using torsocks:
torsocks $HOME/PyBitmessage/src/bitmessagemain.py

# with keys.dat: namecoinrpchost = localhost
WARNING torsocks[9]: [connect] Connection to a local address are denied since it might be a TCP DNS query to a local DNS server. Rejecting it for safety reasons. (in tsocks_connect() at connect.c:192)

# with keys.dat: namecoinrpchost =
ERROR torsocks[97]: Unable to resolve. Status reply: 1 (in socks5_recv_resolve_reply() at socks5.c:683)

It seems that namecoind support should be totally disabled by default
and activated later manually.

Tested on 0.6.3.2.

=-=-=-=-=-=-=
By the way, it failed to run PyBitmessage over torsocks.
It could not connect to anywhere.

ERROR torsocks[9]: Connection refused to Tor SOCKS (in socks5_recv_connect_reply() at socks5.c:549)
ERROR torsocks[9]: General SOCKS server failure (in socks5_recv_connect_reply() at socks5.c:533)

Of course, I usually use PyBitmessage through SOCKS5 to enable Tor.

**Comment by g1itch** [comment]
I assume it's fixed in #1146
