### ISSUE TITLE
Not all invs relayed

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1155]
- it looks like if a connection is established, it does not relay all invs, although the initial "big inv" seems to work correctly. You can reproduce it by using a trustedpeer, and after a couple of hours restart, new objects will show up for syncing
- ACKs sent via Dandelion don't seem to enter stem phase correctly
- it could also affect locally created objects

**Comment by g1itch** [comment]
Was it fixed by #1483?

**Comment by PeterSurda** [comment]
Unfortunately I don't have a good way of testing it. I hope it was but I don't know for sure.

**Comment by navjotcis** [comment]
I have tested it and I faced issues like some times the autoresponder does not reply and shows the status of waiting for the encryption key. I have wait for a couple of hours but I did not get the response so I think there are some issues with autoresponder.

**Comment by PeterSurda** [comment]
Doesn't seem to be happening anymore, was probably fixed in #1483
