### ISSUE TITLE
Python3?

### ISSUE THREAD

**Issue by MaxValue** [Bitmessage/PyBitmessage#1185]
I know I am just complaining here, but I am interested in this project and want to remind everyone that Python2 will be end-of-lifed in 2020 (about 1.42 years from now (i will update this number when i see this issue again))

So:
# **Python3 Support!**

**Comment by sigoa** [comment]
hey Max Headroom, its good that you keep reminding everyone. :camel:

**Comment by MaxValue** [comment]
I hope so!

**Comment by g1itch** [comment]
Some efforts were taken in #1328.

**Comment by g1itch** [comment]
See #1626, #1712
