### ISSUE TITLE
subcription enable/disable bug

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1195]
From a discussion in the bitmessage chan.

> Both actions work near instantaneously for me.
> 
> ------------------------------------------------------
> I found another performance bug.
> 
> When I click to enable a previously disabled broadcast the
> PyBitmessage interface freezes for couple minutes.
> 
> ------------------------------------------------------
> I noticed a performance bug in the address list of the recent
> release of PyBitmessage.
> 
> When I right click and choose 'subscribe to this address' the
> interface freezes completely for several minutes and remains 100%
> unresponsive. This freeze lasts from 3 to 5 minutes.

**Comment by navjotcis** [comment]
I have tried to reproduce the enable/disable issue by adding addresses in the address book then after that, I have tried to subscribe that address book listed addresses then they start showing in the subscriptions address list then I have tried to enable and disable that subscription addresses and it is working fine so now there is no freezing issue with it.
