### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by snow-frog** [Bitmessage/PyBitmessage#1201]
When running setup.py, error is encountered
`building 'pybitmessage.bitmsghash.bitmsghash' extension
C:\Users\user\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tpsrc/bitmsghash/bitmsghash.cpp /Fobuild\temp.win32-2.7\Release\src/bitmsghash/bitmsghash.obj
bitmsghash.cpp
src/bitmsghash/bitmsghash.cpp(19) : fatal error C1083: Cannot open include file: 'openssl/sha.h': No such file or directory
error: command 'C:\\Users\\user\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2`

Skipping setup.py and running bitmessagemain.py from /src, 
`Traceback (most recent call last):
  File ".\bitmessagemain.py", line 19, in <module>
    import depends
  File "C:\Users\user\Downloads\PyBitmessage\src\depends.py", line 5, in <module>
    import pyelliptic.openssl
  File "C:\Users\user\Downloads\PyBitmessage\src\pyelliptic\__init__.py", line 16, in <module>
    from .openssl import OpenSSL
  File "C:\Users\user\Downloads\PyBitmessage\src\pyelliptic\openssl.py", line 549, in <module>
    loadOpenSSL()
  File "C:\Users\user\Downloads\PyBitmessage\src\pyelliptic\openssl.py", line 547, in loadOpenSSL
    raise Exception("Couldn't find and load the OpenSSL library. You must install it.")
Exception: Couldn't find and load the OpenSSL library. You must install it.
PS C:\Users\user\Downloads\PyBitmessage\src> py -2 -m pip install openssl
Collecting openssl`
Even after installing openSSL. All versions. Everywhere (/bin AND windows directory). 
1. Why does setup fail?
2. Which version of openSSL?
3. Install to /bin or windows system directory?
4. What extra steps required?

**Comment by PeterSurda** [comment]
Here are detailed windows instructions: https://docs.google.com/document/d/1XcPtVLBis7t_dyZzPh0h__Ve2iR8XAOsMaO7eKeAu5Q
I never tried setup.py on windows though. You may be missing the openssl headers. You haven't mentioned where you got the openssl from, maybe you got the "light" version, that's probably not enough.

**Comment by PeterSurda** [comment]
To make it clear, if you only want to run it locally, you don't need to follow all the instructions, although you should check that the library version loaded isn't the one that comes with the binary qt distribution as that one's old.

**Comment by PeterSurda** [comment]
Oh and regarding which version of openssl, anything newer than 0.9.8b should work. I recommend either a recent 1.0.2 or 1.1.0 release. I do the windows builds with the latest 1.0.2 available at the time or release.

**Comment by snow-frog** [comment]
I got the openSSL from here http://slproweb.com/products/Win32OpenSSL.html which is what the wiki says to get.

**Comment by chenshaoju** [comment]
The snapshots has no longer update, Is URL changed? Thanks.

**Comment by dimyme** [comment]
https://github.com/Bitmessage/PyBitmessage/releases   works here

**Comment by dimyme** [comment]
> The snapshots has no longer update, Is URL changed? Thanks.

looks OK to me

**Comment by chenshaoju** [comment]
Sorry, I'm mean snapshots version, Not releases. https://bitmessage.org/download/snapshots/win64

**Comment by PeterSurda** [comment]
The snapshots aren't available at the moment, but they should be available in the near future again.

**Comment by g1itch** [comment]
Fixed in #1605
