### ISSUE TITLE
PyLint configuration file

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1223]
The current Codacy settings are overly zealous and for some reason I can't permanently save the configuration. A `.pylintrc` is required, which will relax some naming regexps.
Some examples:
- [ ] variables can be both xxx_xxxx and xXxxXxx format

**Comment by dimyme** [comment]
also it should not bother if "global" is used (as long as its not excessive usage)

**Comment by PeterSurda** [comment]
You can manually disable checks by using a specially crafted comment in the file (at the top, or at the end of the corresponding line).
