### ISSUE TITLE
API Error 0015: when sendin a message

### ISSUE THREAD

**Issue by jranma** [Bitmessage/PyBitmessage#1236]
Hi, 

trying to send a message from CLI, using liux system. 

Message Status: API Error 0015: The length of ackData should be 32 bytes (encoded in hex thus 64 characters).

using bitmessagecli.py
"This is an example of a daemon client for PyBitmessage 0.6.2, by .dok (Version 0.3.1) , modified
"

**Comment by jranma** [comment]
System: linux debian Stretch amd64, python version 2.7.13
freshly installed bitmessage 0.6.3.2 from official https://github.com/Bitmessage/PyBitmessage and using unmodified bitmessagecli.py
just created an address and trying to send a test message, which resulted in above error message. 
receiving messages is OK. 
I am willing to do tests to help debug

**Comment by f97ada87** [comment]
This is my mistake, regression from PR #1062 

https://github.com/Bitmessage/PyBitmessage/blob/4ea6f0208c48710347df1c5d8650ac0ac0107a0a/src/api.py#L779

"!= 64" should be "< 64"

**Comment by f97ada87** [comment]
Actually, to be 100% accurate it should be `if len(ackdata) < 76` to account for the fact that ackdata now includes the 6-byte T/V/S header, so minimum hexstring length becomes (32 + 6) * 2 = **76**

**Comment by f97ada87** [comment]
Awesome, PR #1238 should fix it. Sorry about the issue, and thanks for your help.
