### ISSUE TITLE
Blacklist/Whitelist doesn't talk to the sqlite database

### ISSUE THREAD

**Issue by rwicklin** [Bitmessage/PyBitmessage#1260]
Issue on 0.6.3.2 both windows and linux versions (did not test mac). Attempting to create an entry is not reflected in the database, or in the gui. The database exists and seems to work for other tables. Manually creating a database entry for a blacklisted/whitelisted address through other software produces an entry displayed on the blacklist/whitelist screen. Unclear as to effectiveness of entry after it has been created

**Comment by PeterSurda** [comment]
That sounds like something that was fixed recently but I can't find it at the moment. Can you check if it's still broken with the latest v0.6 branch?

**Comment by g1itch** [comment]
This duplicates #1162. Which is fixed in a3436fe.
