### ISSUE TITLE
Ackdata length mismatch

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#1266]
`getStatus` API wants a 32 byte long hex encoded value, but ackData returned by `sendMessage` is longer (38 bytes)

Version: 0.6.3.2

**Comment by AyrA** [comment]
Ref: https://github.com/Bitmessage/PyBitmessage/blob/master/src/api.py#L777

This should probably be `76`

**Comment by g1itch** [comment]
Don't use `master`, use `v0.6`: https://github.com/Bitmessage/PyBitmessage/blob/v0.6/src/api.py#L967

**Comment by g1itch** [comment]
It looks like duplicate for #1236 which is fixed in #1238.

**Comment by PeterSurda** [comment]
Looks like fixed, please reopen if it resurfaces
