### ISSUE TITLE
Matters arising from PR 1258

### ISSUE THREAD

**Issue by coffeedogs** [Bitmessage/PyBitmessage#1269]
In PR 1258 @g1itch pointed out that:

1. There was some nested comprehension that could be clearer to read if it were unrolled
2. The use of entry_points and extras_require tags to manage plugins means adding prctl to extras_require alone is insufficient. To maintain the plugin interface as it is, we need...something else.

1258 has been merged into v0.6 already, this issue is to keep track of these issues.

**Comment by coffeedogs** [comment]
In PR1258 @g1itch wrote:

> I remember what prctl is used for and counted on it together with psutil. 

If we're counting on it we should make it a solid dependency. Instead, we are gracefully failing if it's not there, which is OK.

> But extras are used for entry points in setuptools, e.g. 'gir' is used for 'notify2' in 'bitmessage.notification.message' EP and requires pygobject package for it. 

So from my reading of that line, based on [the docs]() and [this example](https://stackoverflow.com/questions/36005886/conditional-setuptools-entry-points) is that if both gir and notify2 are installed, the entrypoint `notify2` will be made available.

> So when a module loads EP setuptools checks the dependency. I don't see any reference to prctl extra here.

So this means that prctl is not an optional dependency that satisfies a plugable feature? Are you saying that named threads should be a plugin feature that could be satisfied with the optional dependency prctl?

> I hoped to retain compatibility with plain setuptools, not only pip, because pip is an extension for setuptools.

OK, so can you show me how to reproduce the failure please? I will add the scenario to the test runner and fix it.

**Comment by coffeedogs** [comment]
The related commit does not address the second part of this issue so a PR has not been raised yet.

**Comment by g1itch** [comment]
Total bullshit ):
