### ISSUE TITLE
Option to connect/disconnect should require Confirmation

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#1292]
As of now, clicking the Menu option to connect/disconnect will not show a message but immediately perform that action.

I recommend asking the user if he wants that action performed because the menu option is close to others and might be clicked by accident

**Comment by g1itch** [comment]
Excuse me, I don't understand how it might be clicked by accident. It close to "Quit" and "Regenerate deterministic addresses". If you clicked it by accident, just click again.

**Comment by AyrA** [comment]
> If you clicked it by accident, just click again.

And wait for ages for the client to reconnect? No thanks. Every Application that has a TCP listener I know of will show a confirmation dialog before disconnecting. Reconnecting Bitmessage occasionally takes a long time. I personally would also move this menu item to the settings menu

**Comment by g1itch** [comment]
> And wait for ages for the client to reconnect? No thanks.

~25 seconds

So you want to force the people who know what they're doing to do an extra click because you often regenerate your addresses and misclick to "Go offline"?

**Comment by AyrA** [comment]
> ~25 seconds

If you are really lucky. Bitmessage only tries 8 simultaneous addresses and waits for an entire 20 seconds before continuing (by the way, this should probably be reduced too).

20 seconds is still much longer than confirming that you actually want to disconnect. I doubt that people are using this anyway. You can just exit the client if you want to so I am not sure what the point of this option is at all. Neither any browser nor Mail client nor Torrent application I am using has a disconnect option that prominent.

**Comment by g1itch** [comment]
It's probably specific to PyBitmessage. I've often seen complaints about `dontconnect` config setting. Users want easy knob to go offline.

**Comment by PeterSurda** [comment]
I would add the confirmation, this is not really a technical but a usability question.

**Comment by g1itch** [comment]
OK, let's try

**Comment by g1itch** [comment]
@AyrA did #1303 solve this issue?

**Comment by AyrA** [comment]
It did, but instead of OK/Cancel it should probably be Yes/No

**Comment by posta-store** [comment]
many users hat those confirmation with a vengeance. introducing another pointless "YOU REALLY REALLY WANNA DO IT" without posibility of clicking "NEVER AGAIN GET ON MY NERVES" to disable all repitition of it is a complete  ANTI-feature and hated by most users.

**Comment by AyrA** [comment]
You know you can confirm these dialogs by pressing Y/N? do you?

Next question, why are you upvoting your own comment?

**Comment by Kleshni** [comment]
Sometimes Bitmessage shows me two asking dialogs in a row when I try to close it. My opinion is that a button "Do the action" must do the action because it's what the caption states and what the user expects clicking it.

**Comment by AyrA** [comment]
> My opinion is that a button "Do the action" must do the action because it's what the caption states and what the user expects clicking it.

The user still expects the confirmation dialog under some circumstances. Yes you want to exit an application when you click on that option but you still want the application to warn you about unsaved changes. You also want the application to not exit if unsaved changes could not be saved. A confirmation dialog for an option that renders the bitmessage client almost useless is not a bad idea.

I suggest closing this issue here because it's resolved anyways.
