### ISSUE TITLE
The green LED goes  ON / OFF inconsistently

### ISSUE THREAD

**Issue by KM-200** [Bitmessage/PyBitmessage#1311]
green coming **ON** is Okay, I believe.

However, while YELLOW goes RED consistently on network-offline, 
GREEN remains GREEN even when network is **offline** here. please try out and verify by pulling net cable or something.

**Comment by g1itch** [comment]
Seems fixed in c9bc97f (#1472). Can you confirm?

**Comment by g1itch** [comment]
So I assume it's fixed.
