### ISSUE TITLE
is this truely a collaborative project ?

### ISSUE THREAD

**Issue by dimyme** [Bitmessage/PyBitmessage#1318]
github users (or customers? who knows?) are subject to violent changes in company policies (hostile takeover bids et cetera)  concerning e.g. github-wiki access which can be extremely disruptive to free software development.

This - indeed - is a serious issue which needs to be resolved.

I fully expect this posting to be censored by the "powers to be". And that is - kind of - my point here.

**Comment by posta-store** [comment]
true. since MS took over github, users experienced unacceptable disruptions and blockage. we can't have that.

**Comment by PeterSurda** [comment]
I'm trying to sort this out. In the meantime, you can send your code contributions via bitmessage. Also, try to troll less on github.

**Comment by posta-store** [comment]
what do you mean "troll". Justified complaints are justified complaints which need to be solved, and be solved before long.

**Comment by PeterSurda** [comment]
I'm not asking for me but regarding whatever triggered the flagging.

**Comment by posta-store** [comment]
if NSA triggered it, they would not tell you.
