### ISSUE TITLE
Bitmessage Always crash

### ISSUE THREAD

**Issue by k79e** [Bitmessage/PyBitmessage#1330]
Using Bitmessage_x86_0.6.3.2.exe on win7 x64

debug.log

> 2018-07-30 18:24:08,782 - ERROR - C PoW test fail.
> Traceback (most recent call last):
>   File "proofofwork.py", line 256, in init
>   File "proofofwork.py", line 106, in _doCPoW
> ValueError: Procedure probably called with too many arguments (12 bytes in excess)
> 2018-07-30 18:24:12,611 - WARNING - No indicator plugin found
> 2018-07-30 18:24:12,611 - WARNING - No notification.message plugin found
> 2018-07-30 18:27:07,790 - ERROR - 95.85.40.163:8444 error: 2, Server full, please try again later.
> 2018-07-30 18:28:36,108 - ERROR - 206.248.139.204:8444 error: 2, Too many connections from your IP. Closing connection.
> 2018-07-30 18:28:49,931 - ERROR - 144.76.78.214:8444 error: 2, Too many connections from your IP. Closing connection.
> 2018-07-30 18:29:18,160 - ERROR - 206.248.139.204:8444 error: 2, Too many connections from your IP. Closing connection.
> 2018-07-30 18:29:50,267 - ERROR - 95.85.40.163:8444 error: 2, Server full, please try again later.
> 

Dump file.
[Bitmessage_x86_0.6.3.2.exe.4732.dmp.7z.zip](https://github.com/Bitmessage/PyBitmessage/files/2240766/Bitmessage_x86_0.6.3.2.exe.4732.dmp.7z.zip)

**Comment by dimyme** [comment]
that is not a crash. BM should still work OK I presume

**Comment by kxmp** [comment]
It's not crush anymore.
But it crush again after I delete knownnodes.dat
Then It's not crush anymore.

Is it dos attack from some bad server?
It send me something buggy then my client just shutdown(crush)

**Comment by PeterSurda** [comment]
There will be new binary snapshots soon, you can try it then.

**Comment by kxmp** [comment]
Hey. I just marked the all message in sent box to readed.
Then bitmessage just disappear without any sign!!!!
Is it another kind of crash or this is normal.

**Comment by PeterSurda** [comment]
That sounds like another bug that was fixed in the meantime. If you can't run the current code from source, you'll have to wait for the next binary snapshot.

**Comment by kxmp** [comment]
OK. I'm waiting for next version.

**Comment by kxmp** [comment]
WOW. It start to crash again.
I found that it may only crush in specific condition.
If I open the app then minimized it to tray it will not crush.
It seems only crush when connection to servers. (Through app show it already connected. But it still test or check the connectivity of many ip. It most likely to crush at this stage. When connection become stable. It don't send out any syn. Then it's may not crush.)
Or maybe I just opened the app and checked some tabs, This caused the later crush.
I'v already re-opened the app and don't switch any tabs. Maybe it will not crush anymore. XD

**Comment by kxmp** [comment]
Crushed again. I switched the tab to net stats then to first tab then switched to net info then switch back then switch to net stat. Then leave window to background. The webbrowser's window is on the top of it.
I'm going to test it again. Just switched to netstat then leave it alone.
Maybe it's the sort inside the netstat cause the crush?

I'm going to edit this post when new situation come.

**Comment by PeterSurda** [comment]
It should work now. SOCKS5 was broken with 0.6.3.2 but there have been so many fixes since then.

**Comment by kxmp** [comment]
I think I found the answer.  :+1: 
That's why he said only version older than 0.6.3.2 don't have that problem.

**Comment by kxmp** [comment]
Already run and closed it 3times without any crash. (I exit it when connection is fully finished. When app don't send any syn.)
I'll let you know if anything wrong happen.

**Comment by PeterSurda** [comment]
Thank you for the feedback

**Comment by kxmp** [comment]
I found that mark sent box(right click and mark all with readed) will make app crash. In snapshot version.
Mark inbox and trash don't crash.

**Comment by PeterSurda** [comment]
Yes this has been fixed, it happened if you selected more than 999 messages due to sqlite limitations.

**Comment by PeterSurda** [comment]
Oh wait I misunderstood, thank you for the report, I'll look into it.

**Comment by g1itch** [comment]
#1431 should fix the issue with crash
