### ISSUE TITLE
add 'mark read' to context menu

### ISSUE THREAD

**Issue by milahu** [Bitmessage/PyBitmessage#1353]
this patch will add a 'mark read' button
to the message list context menu.

todo: translations

[pybitmessage.mark_read.2018-09-30.patch.txt](https://github.com/Bitmessage/PyBitmessage/files/2431482/pybitmessage.mark_read.2018-09-30.patch.txt)

ps, i cant create pull requests

**Comment by g1itch** [comment]
I don't see a point. When you open context menu the message is marked read already. If that's not true for you, please check for some exception in debug.log.

**Comment by milahu** [comment]
the existing 'mark read' does work for single messages.

i use my mod to 'mark read' multiple messages at once.
it does make sense, 
if you only read the titles for winnowing = to select non-spam.
plus, if you do 'compulsive hoarding' of all the messages.
the morbid gain of cheap memory, i guess.

**Comment by PeterSurda** [comment]
@milahu please consult the [contribution guidelines](https://github.com/Bitmessage/PyBitmessage/blob/v0.6/PULL_REQUEST_TEMPLATE.md). My guess is you're trying to create a PR against the master branch rather than the v0.6 branch.

**Comment by milahu** [comment]
> master branch rather than the v0.6 branch.

true. i did visit 
https://bitmessage.org/wiki/Contribute
and
https://github.com/Bitmessage/PyBitmessage/tree/v0.6
clicked 'clone or download'
and copy-pasted that URL after `git clone`
in naive hope, to clone the v0.6 branch

now i use
```
base=pybm # short for PyBitmessage
branch=v0.6
git clone https://github.com/Bitmessage/PyBitmessage.git \
--branch "$branch" --single-branch "$base-$branch"
```

patch 1 = markread
here is the 'mark read' patch vs v0.6
= add 'mark read' button to context menu in inbox message list
todo: add translations for 'Mark Read' in MainWindow context
[pybm-v0.6-markread.patch.txt](https://github.com/Bitmessage/PyBitmessage/files/2437997/pybm-v0.6-markread.patch.txt)


minor patch 2 = trashselect
when i delete a message, the selection goes 'one up'.
this feels wrong to me.
when i scroll messages with 'arrow down' 
and delete messages with 'del',
i want to read the next message 'top down'.
[pybm-v0.6-trashselect.patch.txt](https://github.com/Bitmessage/PyBitmessage/files/2437999/pybm-v0.6-trashselect.patch.txt)

minor patch 3 = zoomkeys
add keyboard shortcuts to zoom message view + message compose.
ctrl + + = zoom in
ctrl + - = zoom out
ctrl + 0 = reset zoom
just like in other browsers, firefox, chromium, etc.
[pybm-v0.6-zoomkeys.patch.txt](https://github.com/Bitmessage/PyBitmessage/files/2438563/pybm-v0.6-zoomkeys.patch.txt)

minor patch 4 = xml encoding
specify encoding in ts files
otherwise, xmlstarlet does assume latin1
and does escape all non-ascii chars
```
sed -i 's|<?xml version="1\.0" ?>|<?xml version="1.0" encoding="utf-8"?>|' \
pybm-v0.6/src/translations/*.ts

```

minor patch 5 = xml format
xmlstarlet does also
1. replace `&apos;` with '
2. replace `&quot;` with "
3. reformat the XML header to one node per line
4. add newline after `</TS>`

so much for now ; ]
