### ISSUE TITLE
script to edit interface text = translations

### ISSUE THREAD

**Issue by milahu** [Bitmessage/PyBitmessage#1354]
this is a script i made,
to quickly modify translations.

it does modify your `src/translations/bitmessage_*.ts` file
and does rebuild your `src/translations/bitmessage_*.qm` file

restart bm + enjoy your customized interface

[edit_translation.sh.txt](https://github.com/Bitmessage/PyBitmessage/files/2437055/edit_translation.sh.txt)
[edit_translation_demo.sh.txt](https://github.com/Bitmessage/PyBitmessage/files/2437033/edit_translation_demo.sh.txt)

needs `xmlstarlet` to be installed.

in the ts file,
new translations have `type="no-location"`
```
    <message type="no-location">
      <source>source_name</source>
      <translation type="modded">translation_text</translation>
    </message>
```
modified translations have `type="modded"`
```
    <message>
      <location filename="../bitmessageqt/blacklist.py" line="152"/>
      <source>Whitelist</source>
      <translation type="modded">Whitelist</translation>
    </message>
```

**Comment by g1itch** [comment]
Translation work is done at [transifex](https://www.transifex.com/bitmessage-project/pybitmessage/).
