### ISSUE TITLE
Unused code in shared and protocol modules

### ISSUE THREAD

**Issue by g1itch** [Bitmessage/PyBitmessage#1374]
Hello.

The functions `checkAndShareObjectWithPeers`, `_checkAndShareUndefinedObjectWithPeers`, `_checkAndShareMsgWithPeers`, `_checkAndShareGetpubkeyWithPeers`, `_checkAndSharePubkeyWithPeers`, `_checkAndShareBroadcastWithPeers` are same in `protocol` and `shared` modules and used from latter as I can see.

Remove it from `protocol`?

**Comment by g1itch** [comment]
The only place where `checkAndShareObjectWithPeers()` appears is [class_objectProcessor.py#L751](../blob/v0.6/src/class_objectProcessor.py#L751) but `broadcastToSendDataQueues` seems to be useless, because I cannot find where `sendDataQueues` are handled.

**Comment by PeterSurda** [comment]
Yea it probably does need extra work as the `BMObject` constructor requires decoded arguments, and the decoder only works on buffers. So some redesign is necessary if we're to avoid duplication of code.

**Comment by PeterSurda** [comment]
Maybe create a fake `BMProto` object `o`, copy the buffer from the ACK buffer (or just reference it), and call `o.bm_command_object()` to process it. Probably some additional tests are necessary.

**Comment by g1itch** [comment]
I found that I do not understand where objects are broadcasted to the network ):

**Comment by g1itch** [comment]
I have a rather controversial solution: 03ee14e9.
