### ISSUE TITLE
Questions about API

### ISSUE THREAD

**Issue by g1itch** [Bitmessage/PyBitmessage#1378]
Hello

I used API to test ACK sending so I finally read the `api` module completely. And decided to [refactor it](../compare/v0.6...g1itch:api). Now I have several questions:

1. If `MySimpleXMLRPCRequestHandler` is XML-RPC server why it's methods return json strings?
1. If it's desirable to return JSON, maybe it should be JSON-RPC server?
1. Why so inconsistent return values? [success](../blob/v0.6/src/api.py#L624), [Added subscription](../blob/v0.6/src/api.py#L1145), [done](../blob/v0.6/src/api.py#L1386) seems to have same meaning. [sentMessage](../blob/v0.6/src/api.py#L842) and [sentMessages](../blob/v0.6/src/api.py#L873) counter intuitively both are lists. [getInboxMessagesByReceiver](../blob/v0.6/src/api.py#L820) doesn't return read status. Also some methods may return `None`.
1. Wouldn't it be better to return error status like `{"error": "Number and descriptive text"}` instead of simple string?

JSON string vs XML object:
```xml
<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><string>{
    "numberOfBroadcastsProcessed": 7,
    "networkStatus": "notConnected",
    "softwareName": "PyBitmessage",
    "softwareVersion": "0.6.3.2",
    "networkConnections": 3,
    "numberOfMessagesProcessed": 69,
    "numberOfPubkeysProcessed": 1
}</string></value>
</param>
</params>
</methodResponse>
```
```python
'{\n    "numberOfBroadcastsProcessed": 7,\n    "networkStatus": "notConnected",\n    "softwareName": "PyBitmessage",\n    "softwareVersion": "0.6.3.2",\n    "networkConnections": 3,\n    "numberOfMessagesProcessed": 69,\n    "numberOfPubkeysProcessed": 1\n}'
```

```xml
<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><struct>
<member>
<name>numberOfBroadcastsProcessed</name>
<value><int>0</int></value>
</member>
<member>
<name>networkStatus</name>
<value><string>connectedButHaveNotReceivedIncomingConnections</string></value>
</member>
<member>
<name>softwareName</name>
<value><string>PyBitmessage</string></value>
</member>
<member>
<name>softwareVersion</name>
<value><string>0.6.3.2</string></value>
</member>
<member>
<name>networkConnections</name>
<value><int>0</int></value>
</member>
<member>
<name>numberOfMessagesProcessed</name>
<value><int>0</int></value>
</member>
<member>
<name>numberOfPubkeysProcessed</name>
<value><int>0</int></value>
</member>
</struct></value>
</param>
</params>
</methodResponse>
```

```python
{'networkConnections': 0,
 'networkStatus': 'connectedButHaveNotReceivedIncomingConnections',
 'numberOfBroadcastsProcessed': 0,
 'numberOfMessagesProcessed': 0,
 'numberOfPubkeysProcessed': 0,
 'softwareName': 'PyBitmessage',
 'softwareVersion': '0.6.3.2'}
```

**Comment by PeterSurda** [comment]
The API design predates my involvement in the project so I don't know. If I had to guess, it tried to mimick bitcoind's API design, but since python already bundles the XMLRPC server, they went with that. I agree that the implementation is bad, both with respect to consistency as well as coding (e.g. you could use the factory pattern, have the individual handlers return a dict and the parent would convert it into json). The implementation was even worse before, but at least there was some refactoring to make it less bad.

**Comment by g1itch** [comment]
> e.g. you could use the factory pattern, have the individual handlers return a dict and the parent would convert it into json

Looks similar to what I've done in my current `api` branch. But I commented [that statement](../../../g1itch/PyBitmessage/blob/api/src/api.py#L162) because I think if it's the XML-RPC server both requests and responses should be XML. Sure it can be wrapped to act as JSON-RPC with config and plugin. Compare:

```python
# now
import xmlrpclib
import json

api = xmlrpclib.ServerProxy("http://username:password@127.0.0.1:8442/")
addrs = json.loads(api.listAddresses())['addresses']
```

```python
# XML-RPC
import xmlrpclib

api = xmlrpclib.ServerProxy("http://username:password@127.0.0.1:8442/")
addrs = api.listAddresses()['addresses']
```

```python
# JSON-RPC
import jsonrpclib

api = jsonrpclib.Server("http://username:password@127.0.0.1:8442/")
addrs = api.listAddresses()['addresses']
```

**Comment by PeterSurda** [comment]
I would prefer JSON-RPC. I don't like XML, and apparently there are also some security problems with how python handles it. However there is backwards compatibility to consider.

**Comment by g1itch** [comment]
> apparently there are also some security problems with how python handles it.

8de44cf

**Comment by g1itch** [comment]
> However there is backwards compatibility to consider.

fd95a19

**Comment by g1itch** [comment]
> I would prefer JSON-RPC.

d9f1983

**Comment by g1itch** [comment]
There are also differences in error handling in `jsonrpclib`. It uses only `ProtocolError` and codes from this doc: https://www.jsonrpc.org/specification#error_object.
