### ISSUE TITLE
daemon = true in keys.dat doesn't work

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1385]
Probably some of the recent changes broke it. I don't have time to debug, but the symptom is that with `daemon = true` and pyqt absent in the system, upon launch it will complain that pyqt is missing and refuse to start. When run with `-d`, it's fine. Latest `v0.6`. It worked correctly in the past.

I saw reports about this in the chan, but I thought they don't know how to use it because it wasn't described very well. I had to run a daemon on one of my systems, and turned out that after doing a pull, it broke. Now I think that they were describing the problems I encountered.

**Comment by g1itch** [comment]
I cannot reproduce it with 58bc170 ):

**Comment by PeterSurda** [comment]
Is pyqt installed?

**Comment by g1itch** [comment]
Oh, it was a problem with my portage. I had actually `PyQt4` installed (:
[problem source](../blob/v0.6/src/bitmessagemain.py#L184) - it should be below, under `if daemon:`

**Comment by g1itch** [comment]
It's probably very old issue

**Comment by PeterSurda** [comment]
It worked in May

**Comment by g1itch** [comment]
```diff
diff --git a/src/bitmessagemain.py b/src/bitmessagemain.py
index 4eefceb0..f05e0874 100755
--- a/src/bitmessagemain.py
+++ b/src/bitmessagemain.py
@@ -181,7 +181,6 @@ class Main:
                 sys.exit()
             elif opt in ("-d", "--daemon"):
                 daemon = True
-                state.enableGUI = False  # run without a UI
             elif opt in ("-c", "--curses"):
                 state.curses = True
             elif opt in ("-t", "--test"):
@@ -205,6 +204,9 @@ class Main:
                     os.path.join(app_dir, 'tests', 'apinotify_handler.py')
                 )
 
+        if daemon:
+            state.enableGUI = False  # run without a UI
+
         # is the application already running?  If yes then exit.
         if state.enableGUI and not state.curses and not depends.check_pyqt():
             sys.exit(
```

**Comment by PeterSurda** [comment]
looks ok
