### ISSUE TITLE
Please convert to Qt5

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#1403]
Qt4 has been deprecated in Dec 2015. FreeBSD is removing it in Mar 2019, and the bitmessage port is labeled for deprecation for this reason.

**Comment by PeterSurda** [comment]
Duplicate of #897.

@g1itch has been working on this, I hope it will be ready to merge soon. His approach uses PySide as an intermediate glue so that the code works with either Qt4 or Qt5. I tested it on Debian and it seems to work.
