### ISSUE TITLE
api.deleteAddress exception handling

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1407]
Came over BM:

> Got this deleting address via api.deleteAddress() call. Happens every time.
>
> 2018-12-07 00:36:03,366 - CRITICAL - Unhandled exception
>Traceback (most recent call last):
>  File "/src/bitmessageqt/__init__.py", line 4077, in tableWidgetAddressBookItemChanged
>    self.rerenderComboBoxSendFrom()
>  File "/src/bitmessageqt/__init__.py", line 2189, in rerenderComboBoxSendFrom
>    addressInKeysFile, 'enabled')  # I realize that this is poor programming practice but I don't care. It's easier for others to read.
>  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
>    v = self.get(section, option)
>  File "/src/bmconfigparser.py", line 71, in get
>    raise e
>NoSectionError: No section: 'BM-2cWboeMc4KPNRDzdocBEH4gr8okATMnWmR'

**Comment by g1itch** [comment]
It seems the steps to reproduce are incomplete.

**Comment by g1itch** [comment]
It seems outdated:
[`__init__`, 4077](../blob/v0.6/src/bitmessageqt/__init__.py#L4077): `messageTextedit.setTextColor(QtGui.QColor())`
[`__init__`, 2189](../blob/v0.6/src/bitmessageqt/__init__.py#L2189): `QtCore.Qt.ForegroundRole)`

**Comment by PeterSurda** [comment]
I'll close then.
