### ISSUE TITLE
Endgame

### ISSUE THREAD

**Issue by iljah** [Bitmessage/PyBitmessage#1427]
Have any plans or thoughts been collected somewhere about how many people could theoretically use BM and how to increase that number?

Apparently facebook transfers around 1e11 messages each day (https://s21.q4cdn.com/399680738/files/doc_financials/2018/Q3/Q318-earnings-call-transcript.pdf) or about 1e6 / s on average. They can probably handle 10-1000x that during peak usage (https://spectrum.ieee.org/tech-talk/computing/software/how-facebooks-software-engineers-prepare-messenger-for-new-years-eve) so let's say 1e9 messages / s to aim really high.

Is there any way to transfer that many messages while maintaining privacy anywhere close to current BM protocol? No user would have that kind of bandwidth so global network where everyone receives every message cannot work. If https://bitmessage.org/wiki/Stream is still up to date then everyone would advertise their streams to everyone else which would also probably choke the network. Is it so that one cannot tell just by looking at some address to which stream it belongs?

**Comment by PeterSurda** [comment]
The streams number is a part of the address, so there is no need to advertise anything. The protocol allows for up to 2^64 streams, even though the "addr" command is limited to 2^32.

**Comment by iljah** [comment]
So should section "Advertising" should be removed from wiki page?

**Comment by PeterSurda** [comment]
The wiki page you're referring to was probably written for old protocol. The current protocol will not work that way. Even if other streams aren't fully implemented, pubkey objects are created for the stream specified in the address, and when receiving objects, it will drop those that are for streams you're not interested in.

**Comment by iljah** [comment]
By the way, libp2p has publish+subscribe protocol that resembles bitmessage streams (topics in their docs): https://github.com/libp2p/specs/tree/master/pubsub , https://docs.libp2p.io/concepts/publish-subscribe/ . Topics seem to be only used when deciding which messages are valid, requested and relayed to others. There is no PoW or similar spam protection but building that on top doesn't seem difficult. Not sure how well libp2p protects metadata.
