### ISSUE TITLE
Stream as part of PoW

### ISSUE THREAD

**Issue by iljah** [Bitmessage/PyBitmessage#1428]
Currently it seems that streams are bit awkward to use as participation must be decided manually and addresses are tied to particular stream (https://bitmessage.org/wiki/Stream). How about making stream be part of PoW? PoW for default/global stream would stay as is but PoW of other streams could be for example prefixed (most significant bits replaced) by stream number. This way addresses wouldn't be tied to particular streams.

For example if PoW for default/global stream is `000000...` then PoW for stream af4 would be `af4000000...` or with fewer zeros after stream number if spam is smaller problem in that stream.

**Comment by iljah** [comment]
Also I suspect existing spam protection could partition global BM network automatically into different subnets. Autodetecting and/or negotiating random subnets between accounts that message each other often might also be possible, it should also involve detecting that intermediate nodes don't drop messages of that subnet and/or finding nodes that don't.

**Comment by PeterSurda** [comment]
The recipient must somehow advertise his reachability, otherwise others can't send messages to him. The way the protocol is designed is that the stream is a part of the address. I don't understand how it would work in your proposal. It only seems to cater for routing, but there doesn't appear to be anything for the sender and recipient to agree on the recipient's stream.

The streams aren't fully implemented, but will be probably similarly to what is described in the original whitepaper. But I want to add commands for querying statistics so that a node can make a fast decision about which stream to use for new addresses.

**Comment by iljah** [comment]
> sender and recipient to agree on the recipient's stream

Not built into protocol but it wouldn't be needed if streams are visible from address. Stream-specific PoW might allow automatic partitioning so that most messages don't have to be sent to everyone. Minimum PoW for different streams could also be much smaller, not sure if that's possible currently. For example if there are 100 substreams their PoW could be 100x smaller than global PoW, at least when not being spammed.

**Comment by PeterSurda** [comment]
> Not built into protocol but it wouldn't be needed if streams are visible from address.

I don't understand. Who determines the stream, and how does he signal to the other party which stream to use? In the current protocol, the recipient determines the stream, and signals inside the address to the sender.

**Comment by PeterSurda** [comment]
I think that there some useful ideas here. The main objections I have are things like backwards compatibility, there may not be enough space in 8 bytes to show both the stream and PoW data, and that the PoW creation and checking would become more difficult. Currently, it only needs to check if the hash is smaller than a static number, but this would add some bitwise operators and so on. I think that #1631 is preferable, it keeps an indicator of the target stream as a separate variable, but allows the height in the tree to adjust without people having to generate a new address.
