### ISSUE TITLE
Mac OS appication code signature missing

### ISSUE THREAD

**Issue by Oclair** [Bitmessage/PyBitmessage#1440]
Bitmessage wants to connect to bootstrap8080.bitmessage.org on TCP port 8080
The process has no code signature. The executable can be maliciously modified without being detected. See the following url for more information about applications without a code signature.

https://help.obdev.at/littlesnitch/adv-code-signature#nocodesignature

**Comment by PeterSurda** [comment]
The code signing device that I originally bought turned out incompatible with OSX. I got a new one and tested it on OSX. The next release will be code-signed. In the meantime you can use the detached PGP signature to authenticate the dmg file.

**Comment by Oclair** [comment]
Hey awesome, keep up the great work!
