### ISSUE TITLE
Official AppImage

### ISSUE THREAD

**Issue by tradewatcher** [Bitmessage/PyBitmessage#1450]
Hi,

can you provide an AppImage for easy use, portability and cross-platform support?

I was able to compile it with guide but its horrible to get it running without problems in portable mode.
Take a look at AppImage its really awesome.

**Comment by PeterSurda** [comment]
Not sure why you need portable mode on Linux. While it probably works, it isn't being tested. Using the BITMESSAGE_HOME variable instead is recommended. Ideally, you'd install bitmessage with a package manager that comes with your disto, but we're not there yet.

**Comment by tradewatcher** [comment]
I'm a beginner on Linux and it took me ~1 hour to compile, run, search files and make it portable. 

*) Easy for beginner
*) Automatic Portable feature from AppImage
*) 1 File - faster transfer
*) Cross platform support
*) Independence from package manager
*) No extra installation and sharing of dependencies (Greetings from Spectre..)
*) Assisting "AppImage" improve the Linux ecosystem and make it easier for newcomer
*) Good chances for better support of AppImage on Win10 if the ecosystem is growing.

Why portable on Linux? Encrypted usb drive with software and clean Kali/Tails distro improve security and usability.


Helpful Links to create an AppImage:
https://github.com/AppImage/AppImageKit
https://github.com/AppImage/AppImageKit/releases (AppImage of Kit)
https://discourse.appimage.org/t/how-to-create-an-appimage/155 (Help Board)

**Comment by tradewatcher** [comment]
AppImage is portable if you create a folder "FILENAME.AppImage.home" and/or "FILENAME.AppImage.config"

It takes much less effort to create an AppImage compared to ex. snap packages.

**Comment by mr-tron** [comment]
>  A single thing you still need to compile is C PoW.
and install python2 and qt4, which can be a problem in modern OS.

**Comment by g1itch** [comment]
> > A single thing you still need to compile is C PoW.
> 
> and install python2 and qt4, which can be a problem in modern OS.

When I wrote it, python2 was still available in most distros.

There is a [branch for Qt5](https://github.com/g1itch/PyBitmessage/tree/qt5-wip).
