### ISSUE TITLE
[Feature Request] User settings

### ISSUE THREAD

**Issue by Dokument** [Bitmessage/PyBitmessage#147]
The ability for the user to change settings such as default known nodes, maximumAgeOfAnObjectThatIAmWillingToAccept, and other coded values from the UI would be nice. 

Settings > Advanced could be one place to house all of these settings. 

With those two settings, a user could connect to a knownnode that stores messages for long periods of time (month/year) and obtain messages that they missed while they had their client offline for an extended period of time.

**Comment by PeterSurda** [comment]
I think I can close this. You can have a trusted peer (I think you have to edit the keys.dat manually for this though), and you can change the difficulty settings in the GUI. Complain if you still need work done on this.
