### ISSUE TITLE
own addresses cannot be added to addressbook

### ISSUE THREAD

**Issue by surbhicis** [Bitmessage/PyBitmessage#1485]
here when I tried adding my own address to address book,it adds that without any error and I think it should not be like that.

**Comment by navjotcis** [comment]
here I have add one more check for checking configparser addeess with the entered address book address so when user try to save it it will show him an error: you can not add your own address in the address book.

![image](https://user-images.githubusercontent.com/33522186/92305457-3ff6c280-efa5-11ea-9a18-2d7523b24095.png)

![image](https://user-images.githubusercontent.com/33522186/92305437-fad29080-efa4-11ea-865c-c75466c7dee0.png)

**Comment by navjotcis** [comment]
here when I am trying to save my own address to the address book then it is saving it but it should not happen so have tried to
put one more validation method in shared.py module for checking that the entered address is the user own address or not 
![image](https://user-images.githubusercontent.com/33522186/92461633-2218a000-f1e7-11ea-8eb1-31194f1d51b2.png)

and I have put the check-in bitmessageqt/init.py module now it is fixed and the user can not able to save his own address in the address book
![image](https://user-images.githubusercontent.com/33522186/92461707-3361ac80-f1e7-11ea-8fd7-4cbc11fd0d5d.png)
