### ISSUE TITLE
Scope out recipient segmentation work

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1503]
- [ ] implement streams
  - [ ] connecting to streams
  - [ ] generating address in other streams (free select)
  - [ ] sending to other streams from client
- [ ] segmentation
  - [ ] protocol change
  - [ ] add algorithm for selecting destination streams

(later)
- [ ] stats to help with stream selection
- [ ] implementing routing
  - [ ] bitfield
  - [ ] sending to router
  - [ ] sending from router

**Comment by kuangxu** [comment]
comment

**Comment by mserturk** [comment]
comment

**Comment by PeterSurda** [comment]
There isn't any further work planned on this so I'm closing.
