### ISSUE TITLE
SQL statement error when deleting in QT interface

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1504]
`2019-08-16 08:12:03,023 - CRITICAL - Major error occurred when trying to execute
 a SQL statement within the sqlThread. Please tell Atheros about this error mess
age or post it in the forum! Error occurred while trying to execute statement: "
DELETE FROM inbox"  Here are the parameters; you might want to censor this data 
with asterisks (***) as it can contain private information: ('REDACTED',). Here is the actual error message thrown by the sqlThread: Incorrect number of bindings supplied. The current statement uses 0, and there are 1 supplied.`

There was an independent report in a chan, but I somehow triggered it as well. @g1itch you did some refactoring with this recently, can you check it out?

**Comment by g1itch** [comment]
Where it appeared? While deleting from which folder? Because I cannot reproduce it by deleting from chan's inbox. And more strange there is no result for `grep -r " DELETE FROM inbox" src`. I cannot found delete statement with leading space.

**Comment by g1itch** [comment]
Oh, I see. You are deleting from trash. Maybe some regression in 0c1e5169

**Comment by PeterSurda** [comment]
Yes, I believe it was from trash, but I'm not 100% sure.

**Comment by g1itch** [comment]
```diff --git a/src/bitmessageqt/__init__.py b/src/bitmessageqt/__init__.py
index 507e6ca0..2c5f1485 100644
--- a/src/bitmessageqt/__init__.py
+++ b/src/bitmessageqt/__init__.py
@@ -3270,8 +3270,8 @@ class MyForm(settingsmixin.SMainWindow):
             tableWidget.model().removeRows(r.topRow(), r.bottomRow()-r.topRow()+1)
         idCount = len(inventoryHashesToTrash)
         sqlExecuteChunked(
-            "DELETE FROM inbox" if folder == "trash" or shifted else
-            "UPDATE inbox SET folder='trash'"
+            ("DELETE FROM inbox" if folder == "trash" or shifted else
+             "UPDATE inbox SET folder='trash'") +
             " WHERE msgid IN ({0})", idCount, *inventoryHashesToTrash)
         tableWidget.selectRow(0 if currentRow == 0 else currentRow - 1)
         tableWidget.setUpdatesEnabled(True)
```

**Comment by PeterSurda** [comment]
That makes sense.
