### ISSUE TITLE
Preparatory work for supporting "drafts" folder

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1505]
`class_singleWorker.py` and `class_singleCleaner.py` don't filter all requests for `folder = 'sent'`. This would cause problems with having other folders (it probably already causes problems with trashed messages). Other files may also be affected.

**Comment by cis-navjot-g** [comment]
ok

**Comment by PeterSurda** [comment]
e.g. https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleCleaner.py#L183 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleCleaner.py#L194 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L98 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L111 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L509 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L546 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L669 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L679 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L717 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L732 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L769 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L812 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L833 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L1027 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L1175 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L1281 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L1326 https://github.com/Bitmessage/PyBitmessage/blob/e8bd427b9f1507f33e4797e3c1b07a81817605de/src/class_singleWorker.py#L1411

**Comment by g1itch** [comment]
The problem with `sent` is that it is not a folder but a separate table with own folders.

**Comment by PeterSurda** [comment]
@g1itch that should be ok to work with, otherwise a lot of refactoring is needed.

**Comment by navjotcis** [comment]
I am running kivy and QT app both but in kivy app, there is Draft message feature that is not in the QT app and the draft message is using same database table which sent message is using only folder field is used to differentiate which type of message it is. so in class_singleWorker.py and class_singleCleaner.py file there is no filter in the sent table on the bases of folder=' sent' so I have implemented all the queries of both files with filter folder=' sent'.

**Comment by PeterSurda** [comment]
Fixed in #1508
