### ISSUE TITLE
uuid instead of empty msgid for new messages in sent fold

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1524]
newly created messages have a empty msgid, which is later updated by the worker thread. This creates problems. I recommend using `uuid.uuid4().bytes` instead, which will again be replaced by the worker thread later. This can probably be done in `helper_sent` (except bitmessageqt which doesn't use that, so that needs to be refactord to use helper_sent). The signals the worker thread sends back should also be modified to send the old msgid if it differs from the new msgid, and not to use `updateSentItemStatusByToAddress` anymore.

The interfaces (curses, qt, api, kivy) need to be adjusted accordingly, so that they can replace the msgid if they get a new one from the signal.

- [ ] all interfaces that insert into sent table should use `helper_sent.insert`
  - [ ] Qt
  - [ ] kivy
  - [ ] curses
- [ ] `helper_sent.insert` should check the first argument is empty or None, and if yet, replace it with uuid, and return said uuid (otherwise return the first argument)
- [ ] the UI should retrieve this UUID and adjust the UI accordingly
  - [ ] Qt
  - [ ] kivy
  - [ ] curses

**Comment by g1itch** [comment]
Why don't use sighash as msgid? Also I decided to remove `helper_sent` in my branch [refactoring-sql](../../../g1itch/PyBitmessage/commits/refactoring-sql) because it's useless.

**Comment by PeterSurda** [comment]
It looks like I missed something, the `ackdata` is unique and it is generated prior to inserting, it just isn't done in a standardised way. So I think it should be refactored to call `genAckPayload` into `helper_sent.insert`, and this should return the `ackdata`. This allows a standardised usage from all interfaces.

**Comment by navjotcis** [comment]
I have replaced all the sent table insertion queries with helper_sent.insert method in QT and curses app and also I have replaced all the empty msgid with UUID which will be later updated by the worker thread.
