### ISSUE TITLE
C PoW module unavailable. Please build in

### ISSUE THREAD

**Issue by ArtPus** [Bitmessage/PyBitmessage#1532]
I can't connect to the net - "C PoW module unavailable. Please build in". How can I build this module? Any suggestions?

C:\Users\User\PyBitmessage-0.6.3.2\PyBitmessage-0.6.3.2>python2 checkdeps.py
bitmsghash.cpp
src/bitmsghash/bitmsghash.cpp(19) : fatal error C1083: Cannot open include file:
 'openssl/sha.h': No such file or directory
Building the bitmsghash module failed.
You may be missing a C++ compiler and/or the OpenSSL headers.
Missing optional dependencies: pyopencl msgpack
If you install pyopencl, you will be able to use GPU acceleration for proof of w
ork.
You also need a compatible GPU and drivers.
python-msgpack is recommended for improved performance of message encoding/decod
ing
All the dependencies satisfied, you can install PyBitmessage

**Comment by PeterSurda** [comment]
What you're missing is at least one of the following: C++ compiler or OpenSSL headers (or they aren't configured).

It looks like you're using Windows. Building on Windows is a bit tricky, but should work, either MinGW or MSVS

**Comment by PeterSurda** [comment]
Building on native windows isn't officially supported as it's a PITA. You may still be able to build it but I don't provide support for such build process. Now the windows binaries are cross compiled on linux, through `buildscripts/winbuild.sh`. For building a 32bit binary on a 64bit system, execute as `i386 buildscripts/winbuild.sh`.
