### ISSUE TITLE
Monero Implementation

### ISSUE THREAD

**Issue by OIEIEIO** [Bitmessage/PyBitmessage#1549]
Hi, Has anyone been successful in implementing PyBitmessage in Monero.

I guess my question is less about monero but more about using the messaging system through a cryptocurrency wallet on cli. 

I am a blockchain developer and would like to try to implement the message service at a cli level.

Has it been successfully done yet?

**Comment by PeterSurda** [comment]
You should be able to use the API.

**Comment by OIEIEIO** [comment]
Thank you for responding.

I will look into the API

Has the api been successfully used in a Cryptocurrency project yet?

**Comment by PeterSurda** [comment]
Yes it's being used by some Monero features: https://www.reddit.com/r/bitmessage/comments/abs9vo/pybitmessage_use_case_help_make_monero_multisig/
