### ISSUE TITLE
Fedora 31 support

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1553]
I received a report that it crashes on Fedora 31. Investigating.

**Comment by dimyme** [comment]
without messages.dat it works one time but then its almost impossible to keep it working reliably. follow https://github.com/Bitmessage/PyBitmessage/wiki/7-traps-&-gotchas

**Comment by dimyme** [comment]
I believe it has to do with faulty Qt4 binaries by Fedora. Given that Peter's Fedora 31 is reported to work OK and curses TUI mode works even on my crashy Fedora, I think it is not worth investigating much further. The python code works unless Qt4 GUI mode is being used. kernel dumps can be py-backtraced in gdb but looks kinda inconclusive.

**Comment by PeterSurda** [comment]
I tested it on a fresh fedora install and other that misleading reports from checkdeps.py I was unable to reproduce any crash so far.

**Comment by dimyme** [comment]
Let's blame it on Fedora, PeterSurda, and close casket. :coffin:

**Comment by PeterSurda** [comment]
My guess is it has to do with faulty custom libraries or python modules, possibly indeed qt. I know centos has problems due to gimped openssl, but I don't recall having issues on fedora in the past.

**Comment by dimyme** [comment]
the kernel dumps seem to indicate Qt4 libs are kinda to blame. As this kerneldumping is only one one single machine (i.e. mine), this seems to tell us that the pyBM python2 code is probably clean. Else it would break on other peoples machines as well, in all likelyhood.

**Comment by g1itch** [comment]
I don't confirm crashes: it passes most of out tests, including qt-based, which are ran while building the container.
https://travis-ci.org/github/g1itch/PyBitmessage/jobs/735332402
