### ISSUE TITLE
Missing defaults for "Resends Expire" settings

### ISSUE THREAD

**Issue by g1itch** [Bitmessage/PyBitmessage#1558]
Hello!

I reproduced the issue reported in chan: when user saves settings in freshly installed PyBitmessage the following message box appears

![bm_settings_resend](https://user-images.githubusercontent.com/4012700/68864774-5a9c3a00-06fa-11ea-819f-a0688174791a.png)

I introduced it in 8a3074f

**Comment by dimyme** [comment]
same here!
