### ISSUE TITLE
[Enhancement] Directories and files should be in accordance with XDG base directory spec

### ISSUE THREAD

**Issue by omyno** [Bitmessage/PyBitmessage#157]
On Linux, Pybitmessage uses `~/.PyBitmessage`. Instead, it should respect the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), which means `~/.config/pybitmessage` ($XDG_CONFIG_HOME) for keys.dat and so on.

**Comment by PeterSurda** [comment]
Hasn't this been fixed already?

**Comment by PeterSurda** [comment]
Ok, so now it puts everything into XDG_CONFIG_HOME, if the variable exists. While I understand what the standard wants to achieve, I am not sure it's a good fit for PyBitmessage, since the directory structure would differ from portable mode. It needs to be investigated.

**Comment by PeterSurda** [comment]
I agree with my previous post, solitting this into 3 directories doesn't fit into the design of PyBitmessage.
