### ISSUE TITLE
cannot handle stream numbers of 0

### ISSUE THREAD

**Issue by 6r1d** [Bitmessage/PyBitmessage#1574]
Hello, recently I was testing BitMessage with my friends and one of them decided to change his address. He sent me his new one, which I can't use.

While trying to send my message, I see this one popping up:

    Concerning the address BM-AA11AAA1AAAAAAAAA1AAAA1AAAAAAA11,
    Bitmessage cannot handle stream numbers of 0.
    Perhaps upgrade Bitmessage to the latest version.

(__I replaced letters and digits with A and 1.__)

I noticed that new address is a bit shorter; I wonder if length of an address matters in any way.

I am using v0.6 from Git, last commit is `e47b573b3eda9c93f56ecdb86b9c6c66fe4698f1`. I also see 5 connected peers and I can send messages to myself.

**Comment by PeterSurda** [comment]
Well only stream 1 is currently supported so the address is unusable. Not sure how it was generated. Moreover, stream 0 is outside of the specification so even if streams are implemented it still wouldn't work.
