### ISSUE TITLE
Unable to send messages

### ISSUE THREAD

**Issue by sashamd** [Bitmessage/PyBitmessage#1578]
I have two nodes with different IPs, a daemon connected to the network and a gui with the daemon as trustedpeer = xxx.xxx.xxx.xxx:8444. A message from the gui to the daemon is 'Waiting for their encryption key. Will request it again soon'. Another message from the daemon to the gui has status 'awaitingpubkey'. 24 hours have passed but nothing changed.

**Comment by PeterSurda** [comment]
This can happen with 0.6.3.2 due to unfinished dandelion implementation. Try the latest code from the v0.6 branch.

**Comment by sashamd** [comment]
I have sent today another message from the daemon to the gui and suddenly all previous messages appeared at their destinations. Probably this was some kind of random program delay. Thank you for the comment.

**Comment by PeterSurda** [comment]
The bug can be worked around by restarting a node, or by making/receiving new connections, so maybe that's what you're experiencing. I really recommend using the code from v0.6 branch instead of 0.6.3.2 release unless you for some reason can't.

**Comment by sashamd** [comment]
I suppose it's already v0.6.

`git status`
On branch v0.6

`git log`
commit e47b573b3eda9c93f56ecdb86b9c6c66fe4698f1
