### ISSUE TITLE
About encoding v3 addresses for very short ripe hashes

### ISSUE THREAD

**Issue by teruteru128** [Bitmessage/PyBitmessage#1611]
I have two addresses.
BM-GtE4KjZbHfpvD3pRVpzKFJwbeGPdJWNZ
BM-pLHGovVQKxCYBp4tsWhAahaTiqyo9

Both are v3 addresses for the same ripe hash.
The current PyBitmessage implementation generates the former address for short hashes.
Which address is appropriate?

**Comment by teruteru128** [comment]
As an additional note, Abit cannot send messages to the former address.
Also, messages sent from Abit to the latter will be displayed as messages with v4 addresses.

**Comment by teruteru128** [comment]
In Abit, the former address cannot find the public key.

**Comment by PeterSurda** [comment]
> Both are v3 addresses for the same ripe hash.
It looks like an unclarity of the specification and differences in implementation. The ripe begins with 4 zeroes. PyBitmessage doesn't like when ripe of a v3 address begins with more than 2 zeroes and decides it's invalid. For v4 addresses it shouldn't be an issue. My recommendation is to use v4 addresses.

> As an additional note, Abit cannot send messages to the former address.
Try a v4 address instead.

>  Also, messages sent from Abit to the latter will be displayed as messages with v4 addresses.
Messages don't contain a recipient address. The recipient address is assigned by the recipient after decoding the message.

**Comment by teruteru128** [comment]
Yeah, I created a tool and generated a v4 address at the same time as v3.
I will use that in the future.
Thank you for your answer.

**Comment by PeterSurda** [comment]
Well the v3 and v4 addresses work almost the same, in particular they use the same keys, so unless there are some strange technical reasons there is no need to use v3.
