### ISSUE TITLE
Nodes don't get added into knownnodes

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1640]
Upon looking through the code, I noticed that nodes of incoming connections aren't added to `knownnodes`. Pre-asyncore, if you received an incoming connection, you added its data into knownnodes. It appears I removed it during refactoring and never re-added it. It means that knownnodes gets filled with obsolete crap. It may also be contributing to #1597.

The code should call `knownnodes.addKnownNode` for each incoming stream during `set_connection_fully_established` for inbound connections.

**Comment by g1itch** [comment]
Incoming connections usually report `127.0.0.1`: https://github.com/Bitmessage/PyBitmessage/blob/v0.6/src/protocol.py#L300

**Comment by PeterSurda** [comment]
Yes, but you see their IP in `self.destination` and this you can add to `knownnodes`. This is how it used to work in the past. Maybe only bootstrap servers should do this, after checking that the node is accessible from the outside.

**Comment by PeterSurda** [comment]
I think #1654 resolved this.
