### ISSUE TITLE
Search and UTF-8 chars

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1644]
Received over BM:

> Can't search message using Cyrillic letters
> The letters in the search text field
> 
> А а     Б б     В в     Г г     Д д     Е е     Ё ё
> Ж ж З з     И и     Й й     К к     Л л     М м
> Н н     О о     П п     Р р     С с     Т т     У у
> Ф ф     Х х     Ц ц     Ч ч     Ш ш Щ щ Ъ ъ    
> Ы ы     Ь ь     Э э     Ю ю     Я я         

@g1itch haven't you make some changes to search recently?

PS I haven't tried to reproduce this.

**Comment by g1itch** [comment]
I cannot reproduce it on current v0.6. Most likely it is because of `str(text)` in 045a2ef, fixed in c69deca.

**Comment by PeterSurda** [comment]
Can't reproduce.
