### ISSUE TITLE
Offline mode first time network settings

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1656]
Reported in bitmessage chan:

> I am reporting a bug.
> To reproduce:
>
> 1. Backup $HOME/.config/PyBitmessage and remove the directory
> 2. Start bitmessagemain.py
> 3. When dialog popped, select "Work offline" and push "OK"
> 4. On "Settings" menu, go "Network Settings"
>   and select "Proxy server / Tor" "Type:" "SOCKS5",
>   then push "OK"
>   (In this case Tor is required, but I guess any changes may work)
> 5. Select "Network Status" tab, and wait few minutes
> 6. The client will be automatically connected to some nodes
>
> Tested on latest git version: commit e237534335d66748b27fb6251faf6cb72912ebd1

I'm not sure if this is just unintuitive UI, or there is a check to see if you're changing network settings for the first time which mis-checks.

**Comment by g1itch** [comment]
It seems to be here: https://github.com/Bitmessage/PyBitmessage/commit/18392017c63c538f99fa0cf833c8d494b54bd449#diff-8c46c5f54d96f9eb2b91bb2b6bdd7d9fR316
