### ISSUE TITLE
Missing dependencies- fabvenv, pybloomfilter

### ISSUE THREAD

**Issue by suliuzh** [Bitmessage/PyBitmessage#1687]
Hi
As we can see, ** fabvenv and pybloomfilter** are used as dependencies in source code. Here I show fabvenv in the following screenshot and pybloomfilter also can be found in other source code files. So if it is a must, I am wondering if these dependencies should be listed in setup.py or requirements.txt. If not , why?
![image](https://user-images.githubusercontent.com/27858725/98521078-f16bea00-22ad-11eb-8dd3-4aed4cdf6769.png)

**Comment by g1itch** [comment]
The files on your screenshots are not source files. It's some abandoned garbage. As for pybloomfilter, it has never been adopted. Moreover, I cannot find a working implementation not failing my tests: 58ee16e.

**Comment by g1itch** [comment]
Also `requirements.txt` is for tests. The bitmessage itself has no requirements, only optional dependencies.

**Comment by suliuzh** [comment]
Ok, so maybe such codes should be removed from cloned repository if they are abandoned. To prevent misunderstandings.
