### ISSUE TITLE
[Enhancement] define another background-color for the Inbox

### ISSUE THREAD

**Issue by rubo77** [Bitmessage/PyBitmessage#169]
I always get confused, if I am looking at the inbox or the sentbox.

It would help the eye a lot, if you could define another backgroundcolor for the sentbox

**Comment by PeterSurda** [comment]
I don't know. The new UI in https://github.com/mailchuck/PyBitmessage now shows folders on the left, so it's probably not necessary. But I'm not a usability expert. If you think it's still needed with the new UI, reopen.
