### ISSUE TITLE
No module named 'openssl'

### ISSUE THREAD

**Issue by ultramassiveblackhole** [Bitmessage/PyBitmessage#1714]
In the PyBitmessage/src/pyelliptic/cipher.py file the `from openssl import OpenSSL` is wrong. 
```

(venv) u@vm:~/bitmessage/PyBitmessage/src$ python3 bitmessagemain.py
ERROR: PyBitmessage does not support Python 3+. Python 2.7.4 or greater is required.
ERROR: check_openssl failed unexpectedly.
Traceback (most recent call last):
  File "/home/u/bitmessage/PyBitmessage/src/depends.py", line 434, in check_dependencies
    has_all_dependencies &= check()
  File "/home/u/bitmessage/PyBitmessage/src/depends.py", line 277, in check_openssl
    import pyelliptic.openssl
  File "/home/u/bitmessage/PyBitmessage/src/pyelliptic/__init__.py", line 12, in <module>
    from .cipher import Cipher
  File "/home/u/bitmessage/PyBitmessage/src/pyelliptic/cipher.py", line 9, in <module>
    from openssl import OpenSSL
ModuleNotFoundError: No module named 'openssl'
PyBitmessage cannot start. One or more dependencies are unavailable.

```

I installed a few other modules like PyOpenSSL and even tried to import the module outside of the virtual environment: 

```
Python 3.9.1 (default, Dec  8 2020, 07:51:42) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openssl'
>>> from openssl import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openssl'
>>> 
```

cc / @PeterSurda @g1itch @navjotcis

**Comment by PeterSurda** [comment]
As it says, python 3 isn't supported at the moment.

**Comment by ultramassiveblackhole** [comment]
Debian 11 only supports python3 and there is no python-msgpack anymore. 
https://github.com/Bitmessage/PyBitmessage/issues/1712

I'm looking forward for a python3 version of PyBitmessage!

**Comment by PeterSurda** [comment]
Unfortunately you'll have to wait a bit. Internally we do have a python3 version, but it has bad code quality and lots of other problems. This is why we need a plan to make the migration work properly.

It may take a bit of time. In the meantime I would like to add support for appimage/flatpak/snap to the delivery pipeline so that users like you can keep using PyBitmessage even if the dependencies aren't supported by your distro.

**Comment by ultramassiveblackhole** [comment]
@PeterSurda I would like to test it or help to rewrite the code. Can you give me access to the pathon3 version of program? 
This is a Debian 11 based distribution but I run quiet a few VM as well.
