### ISSUE TITLE
[Request] Retry decrypting broadcast messages

### ISSUE THREAD

**Issue by Wabba** [Bitmessage/PyBitmessage#173]
Currently, it appears that when broadcasts are first received the client tries to decrypt them with the addresses in the user's subscriptions. 

This could be changed so that whenever a new address is added to the user's subscriptions, it tries again to decypt the broadcast messages in inventory with the new address.  This would show any broadcasts from that address for the last ~2 days.

This would be useful for new users starting up the application, then finding and adding the mailing list addresses to their subscriptions. I noticed when starting a new client, by the time I added the common mailing lists, all of the broadcasts had already been processed by the client. I then would only get new broadcasts from that time forward. New users would be more likely to stay with bitmessage if they can immediately get the recent broadcasts instead of waiting for hours for a new one to be sent.

**Comment by g1itch** [comment]
It seems to be implemented back in 2013: 

https://github.com/Bitmessage/PyBitmessage/commit/44618ffcc2095de10051af7dcb447846768a060d#diff-daf5347c7c82ada9587538c6f1b40a286e007b9adee2acb80821ac5e8afbdd59R2134
