### ISSUE TITLE
Separate view key like in Monero

### ISSUE THREAD

**Issue by jluttine** [Bitmessage/PyBitmessage#1752]
I'm not familiar with Bitmessage details, but as far as I understand, the private key is used in decrypting a message but also in creating a message. Otherwise, I don't know how this sentence from the whitepaper could hold: "The **sender** of a message cannot be spoofed." Have I understood correctly?

If so, I would suggest that the key for decrypting a message was different from the key used to create a message. So, similarly as in Monero, have a public key, view key and private key:

- public key is used for the address to which people send messages
- view key is used to decrypt (=read) messages
- private key is used to create messages

With this kind of setting, one could use a server which listens to messages and then a light client that can create messages. The server isn't able to create messages, only read them, so there are less risks. One might even let some trusted server to have the user's view-key so that the user doesn't need to run such a server themselves. There is a reduction in privacy, yes, but it might be a good practical compromise for the user. Or, the user could run the server themselves to have "perfect" privacy but still for security reasons not have the private keys on that server but on the thin light client that connects to that server whenever the user is actively using it.

**Comment by jluttine** [comment]
With this kind of setting, one could of course further encrypt the message inside the bitmessage so that the view-key holder cannot read the actual message content. For instance, encrypt the message content with PGP or whatever. This way the view-key holder is only able to see that the user received a message (and possibly some other metadata), but still couldn't read the PGP-encrypted message content.

I'm just thinking of ways to set up thin light clients securely with a minimal effect on privacy.

**Comment by PeterSurda** [comment]
The whitepaper contains some obsolete parts. There actually are two keys in the protocol, one for encryption and one for signing. However there are going to be some changes in the protocol and will only use one key. There are also plans to add forward secrecy, which may not be compatible with the model you describe.

**Comment by jluttine** [comment]
Ok, thanks for the response! If there are going to be changes in the protocol, I would very much hope that it supported something similar to what I described: a key that can be used to just detect if the message is for that key, but without being able decrypt the message content.

I think this would be a big thing for wider adoption of bitmessage as the users would have a bit easier-to-user option that doesn't require running their own daemon/server all the time just to receive messages. It'd be easy to implement light clients to mobile devices etc. Well, why don't those people just use the already existing solutions like Riot and stay away from Bitmessage? Because then they couldn't send messages to people who don't want to make such compromises and prefer to use Bitmessage. So, every user can make the choice themselves while still being able to communicate with each other. Also, I'd assume this kind of setup would still be more private than many other alternatives with end-to-end encryption because in this case the other servers don't know the recipient, only the one server that has the view key. So, it's a very minimal and optional compromise to privacy: just one server that the user chooses themselves knows about the user receiving messages.

But yeah, I have no idea if it's possible, but I would like to encourage you to think if the protocol could be adjusted so that it was.

**Comment by PeterSurda** [comment]
In Bitmessage the design decision for lighter clients consists mainly of two future developments, streams and simplified recipient verification. Streams allow the recipients to be separated into multiple segments, and SRV allows to verify if a message is for you by downloading just its headers rather than the whole body. These approaches are described in other issues. Both reduce bandwidth needed by the client at the cost of reducing anonymity. But we'll probably have an android port first and then optimise the protocol gradually.
