### ISSUE TITLE
tests for `BMConfigParser._reset`

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1754]
Write tests and re-enable in Python 3

**Comment by kdcis** [comment]
Hi @PeterSurda 
You can close this issue. I've raised a PR for this, Please check #1766 
https://github.com/Bitmessage/PyBitmessage/pull/1766

**Comment by g1itch** [comment]
> Hi @PeterSurda
> You can close this issue. I've raised a PR for this, Please check #1766

Excuse me, but it works in other way: when the tests for python3 pass you write in the last commit message something like ["Fixes: #1754"](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue) and this issue will be closed by PR merge.

**Comment by kdcis** [comment]
Okay, Got it. Will do that.
