### ISSUE TITLE
Windows executable broken in last two snapshots

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1758]
I got a report that the latest windows executable doesn't work, maybe has to do with `six`

**Comment by g1itch** [comment]
I didn't merge #1756 which introduces `six` usage. Strictly speaking the latest release was two years ago, [on 14 Feb 2018](https://github.com/Bitmessage/PyBitmessage/releases/tag/0.6.3.2). Any details would help debugging.

**Comment by PeterSurda** [comment]
Someone said the latest snapshot doesn't work, and the one before that worked. It was posted on one of the chans, maybe bitmessage. I haven't tried to reproduce it.

**Comment by g1itch** [comment]
Yes, I read the message: "There is no other explanation given, and no relevant information is in the debug.log file."

**Comment by g1itch** [comment]
I'm downloading https://download.bitmessage.org/snapshots/20210429/ and will try to debug

**Comment by g1itch** [comment]
Same Fatal error with 20210427

**Comment by g1itch** [comment]
Please remind me, can I take an executable built by buildbot for a PR and how?

**Comment by g1itch** [comment]
The source of the issue: https://github.com/Bitmessage/PyBitmessage/commit/49f9620236cf559501a3046980f9c576414682a8#diff-b95eac6665d2cc32e4e1a47882925bc45383206ffda00b5e0615b808396fe8e9R13

Hidden import I guess.
