### ISSUE TITLE
[OSX] Can't paste content in PyBitmessage

### ISSUE THREAD

**Issue by Cubox-** [Bitmessage/PyBitmessage#179]
Hi,

Just downloaded and run PyBitmessage (last commit is fe32ed5d4c10e89e68152d6f10d6606ea2b21e36)

I am unable to paste things in PyBitmessage. I tried with the address from your website, and the paste option in right click menu is gray. Command+V don't work either. I am able to paste this address in other applications.

**Comment by PeterSurda** [comment]
I'll see if I can reproduce this.

**Comment by PeterSurda** [comment]
I cannot reproduce this. I installed Chrome on my Mac and it works fine. Both Alt-V (I don't have a Mac keyboard) and right-click & paste. And "copy" works with both Alt-C and right-click & copy. And copy & past from inside PyBitmessage to another tab works too.

Please try with the latest mailchuck fork. If it still doesn't work, maybe there's something wrong with your computer.

**Comment by Cubox-** [comment]
Maybe the issue is two years old and got fixed due to other code edits.

Thanks for looking into it, a little bit late through.

**Comment by PeterSurda** [comment]
Sorry about that. I just joined about a month ago and there's loads of open issues to walk through. Atheros doesn't have a Mac, and I bought a Mac just for PyBitmessage testing/releases.
