### ISSUE TITLE
python uses 100% CPU

### ISSUE THREAD

**Issue by rubo77** [Bitmessage/PyBitmessage#183]
On my Xubuntu 12.10 with xfce-desktop sometimes (not always) pyBitmessage causes a python process that uses 100% of one complete CPU:

```
#ps aux|grep bitmes
```

---

```
ruben     2703 88.3  1.7 1870944 70304 ?       Sl   20:44  19:14 python bitmessagemain.py
```

---

If I close the GUI, that process stays and continues to waste the CPU

only

```
#kill -kill 2703
```

stops bitmessage and releases the CPU

**Comment by marcomarsala** [comment]
Bitmessage_x64_0.6.2.exe on Windows always uses 100% of 1 core when idle. The whole GUI is slow and unresponsive. Objects to be synced is 0.
