### ISSUE TITLE
Can’t install BitMessage on Whonix 16

### ISSUE THREAD

**Issue by Cottonwoodhill** [Bitmessage/PyBitmessage#1845]
Hi @,

I need some help regarding an issue described in the following link below :

https://forums.whonix.org/t/cant-install-bitmessage-following-the-wiki/12395

Your help would be much appreciated.

Thanks in advance and regards.

**Comment by PeterSurda** [comment]
Try the appimage: https://appimage.bitmessage.org/releases/

**Comment by Cottonwoodhill** [comment]
Hi `PeterSurda `and thank you for your message,
Works perfectly, many thanks :)
Best regards
