### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by g1itch** [Bitmessage/PyBitmessage#1855]
Hello!

I suddenly discovered that your RTFD is broken: https://pybitmessage.readthedocs.io/en/latest/
while mine is still OK: https://pybitmessage-test.readthedocs.io/en/latest/

If you didn't change the config, it's related to the recent changes in the code.

**Comment by PeterSurda** [comment]
Not sure it ever worked. I logged in to rtd.io, and `latest` was setup to follow the `master` branch. I reconfigured it to `v0.6` and rebuilt manually, and it looks ok now.

**Comment by g1itch** [comment]
> Not sure it ever worked.

I remember it working in the past

**Comment by PeterSurda** [comment]
> I remember it working in the past

My guess is `v0.6` worked but `latest` didn't.
