### ISSUE TITLE
Error on send message via API

### ISSUE THREAD

**Issue by teruteru128** [Bitmessage/PyBitmessage#1898]
If you send a message to an address registered in the address book via API, an error will be returned.

```log
2021-12-11 02:50:58,436 - ERROR - too many values to unpack
Traceback (most recent call last):
  File "api.py", line 1514, in _dispatch
  File "api.py", line 1487, in _handle_request
  File "api.py", line 1137, in HandleSendMessage
ValueError: too many values to unpack
```

OS: Windows 10 21H1
PyBitmessage: 0.6.3.2 20211207

**Comment by g1itch** [comment]
Could I see your code?

**Comment by teruteru128** [comment]
The first thing you can prepare is written in C, is that okay?

**Comment by g1itch** [comment]
> The first thing you can prepare is written in C, is that okay?

I'm not afraid (;

The line number of your traceback seems to point to decoding of base64 in subject argument

**Comment by teruteru128** [comment]
https://github.com/teruteru128/study/blob/develop/src/bmsendmsg.c
https://github.com/teruteru128/libstudy/blob/master/src/bmapi.c

**Comment by teruteru128** [comment]
Hmm ... should I submit something made with python?
I think it's probably not difficult because it depends on whether there is a corresponding record in the address book using the XML-RPC API.

**Comment by g1itch** [comment]
> The line number of your traceback seems to point to decoding of base64 in subject argument

Oh, I see it's really about the label: https://github.com/Bitmessage/PyBitmessage/blob/v0.6/src/api.py#L1137

**Comment by g1itch** [comment]
> Hmm ... should I submit something made with python? I think it's probably not difficult because it depends on whether there is a corresponding record in the address book using the XML-RPC API.

Yes, if you can reproduce it in python. Don't you get this exception when using JSON-RPC? It seems not related.

**Comment by g1itch** [comment]
Perhaps try to remove the comma in the line. Does it help?

Пт, 10 груд. 2021 20:23 користувач Teruteru ***@***.***> пише:

**Comment by teruteru128** [comment]
Um ... I'm sorry, I'm using PyBitmessage distributed as a binary on Windows, so I can't modify the source code and test it right away.

**Comment by teruteru128** [comment]
However, the indication of removing the comma seems correct.

**Comment by g1itch** [comment]
OK, so I have to write a test and merge the fix or at least build a new
continuous release. Maybe tomorrow.

Пт, 10 груд. 2021 20:46 користувач Teruteru ***@***.***> пише:

**Comment by teruteru128** [comment]
The source code has been updated. I think this makes it easier to see.
https://github.com/teruteru128/study/blob/9324573/src/bmsendmsg.c
https://github.com/teruteru128/libstudy/blob/d3475a2/src/bmapi.c#L88-L126

**Comment by PeterSurda** [comment]
The `ValueError` is confusing me. However I was able to reproduce a scaled down version of the exception, maybe it will help (I don't have more time at the moment to look into it).

```
>>> r = [[[0, 0, 0], 0, 0]]
>>> toLabel, = r[0][0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack
```

If I had to take a wild guess, I would say there are duplicate records in the address book, or the `label` column is stored in an unusual storage type (a blob instead of a string, maybe). This type of problem should still be handled better in PyBM though.

**Comment by g1itch** [comment]
Try bytes:
toLabel = b'test'

Сб, 11 груд. 2021 03:20 користувач Peter Šurda ***@***.***>
пише:

**Comment by PeterSurda** [comment]
> Try bytes: `toLabel = b'test'`

Yep looks like you're right:

```
>>> r = [[b'sldfkjas']]
>>> toLabel, = r[0][0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack
```

**Comment by PeterSurda** [comment]
Well the same happens with a string, makes sense for python2. So the comma shouldn't be there, it's a bug.

**Comment by g1itch** [comment]
> OK, so I have to write a test and merge the fix or at least build a new continuous release. Maybe tomorrow.

The test is written, the fix is already available on my [continuous release page](https://github.com/g1itch/PyBitmessage/releases/tag/continuous). Note, it's built in slightly different way than official ones.

**Comment by teruteru128** [comment]
> > OK, so I have to write a test and merge the fix or at least build a new continuous release. Maybe tomorrow.
> 
> The test is written, the fix is already available on my [continuous release page](https://github.com/g1itch/PyBitmessage/releases/tag/continuous). Note, it's built in slightly different way than official ones.

I was able to confirm that the problem was fixed! :thumbsup:

**Comment by g1itch** [comment]
> > The test is written, the fix is already available on my [continuous release page](https://github.com/g1itch/PyBitmessage/releases/tag/continuous). Note, it's built in slightly different way than official ones.
> 
> I was able to confirm that the problem was fixed! +1

So, let's wait for merging of #1899. Thank you for report! It's been a while since the API refactoring.

**Comment by teruteru128** [comment]
@g1itch
> > OK, so I have to write a test and merge the fix or at least build a new continuous release. Maybe tomorrow.
> 
> The test is written, the fix is already available on my [continuous release page](https://github.com/g1itch/PyBitmessage/releases/tag/continuous). Note, it's built in slightly different way than official ones.

Hi, I've tried this unofficial release, but it doesn't seem that jsonapi is available. Should I create a new issue?
```log
2021-12-13 15:39:08,928 - WARNING - defusedxml not available, only use API on a secure, closed network.
2021-12-13 15:39:08,928 - WARNING - jsonrpclib not available, failing back to XML-RPC
```

**Comment by teruteru128** [comment]
> @g1itch
> 
> > > OK, so I have to write a test and merge the fix or at least build a new continuous release. Maybe tomorrow.
> > 
> > 
> > The test is written, the fix is already available on my [continuous release page](https://github.com/g1itch/PyBitmessage/releases/tag/continuous). Note, it's built in slightly different way than official ones.
> 
> Hi, I've tried this unofficial release, but it doesn't seem that jsonapi is available. Should I create a new issue?
> 
> ```
> 2021-12-13 15:39:08,928 - WARNING - defusedxml not available, only use API on a secure, closed network.
> 2021-12-13 15:39:08,928 - WARNING - jsonrpclib not available, failing back to XML-RPC
> ```

I have confirmed that the same issue occurs with the officially released snapshot binaries.
https://download.bitmessage.org/snapshots/20211207/

**Comment by PeterSurda** [comment]
> > @g1itch
> > > > OK, so I have to write a test and merge the fix or at least build a new continuous release. Maybe tomorrow.
> > > 
> > > 
> > > The test is written, the fix is already available on my [continuous release page](https://github.com/g1itch/PyBitmessage/releases/tag/continuous). Note, it's built in slightly different way than official ones.
> > 
> > 
> > Hi, I've tried this unofficial release, but it doesn't seem that jsonapi is available. Should I create a new issue?
> > ```
> > 2021-12-13 15:39:08,928 - WARNING - defusedxml not available, only use API on a secure, closed network.
> > 2021-12-13 15:39:08,928 - WARNING - jsonrpclib not available, failing back to XML-RPC
> > ```
> 
> I have confirmed that the same issue occurs with the officially released snapshot binaries. https://download.bitmessage.org/snapshots/20211207/

Thank you I'll open a separate issue for this.
