### ISSUE TITLE
Appimage build broken?

### ISSUE THREAD

**Issue by PeterSurda** [Bitmessage/PyBitmessage#1941]
received over BM:

> Hi!
>
> The appimage from  20220304 raises the exception:
> 
> 2022-03-04 20:03:52,500 - CRITICAL - Unhandled exception
> Traceback (most recent call last):
>  File "/tmp/.mount_PyBitm6T4Aoc/usr/bin//pybitmessage", line 11, in <module>
>    execfile(script_file, new_globals)
>   File "/tmp/.mount_PyBitm6T4Aoc/usr/lib/python2.7/dist-packages/pybitmessage/bitmessagemain.py", line 425, in <module>
>     main()
>   File "/tmp/.mount_PyBitm6T4Aoc/usr/lib/python2.7/dist-packages/pybitmessage/bitmessagemain.py", line 421, in main
>     mainprogram.start()
>   File "/tmp/.mount_PyBitm6T4Aoc/usr/lib/python2.7/dist-packages/pybitmessage/bitmessagemain.py", line 153, in start
>     state.thisapp = singleinstance("", daemon)
>   File "/tmp/.mount_PyBitm6T4Aoc/usr/lib/python2.7/dist-packages/pybitmessage/singleinstance.py", line 34, in __init__
>     import bitmessageqt
>   File "/tmp/.mount_PyBitm6T4Aoc/usr/lib/python2.7/dist-packages/pybitmessage/bitmessageqt/__init__.py", line 18, in <module>
>     from PyQt4 import QtCore, QtGui
> ImportError: /usr/lib64/libgobject-2.0.so.0: undefined symbol: g_uri_ref

**Comment by Cottonwoodhill** [comment]
Hi,
I also have an issue with the Appimage 0.6.3.2 which doesn't connect anymore for some days.
Would a developer please report if there is any problem we can resolve?
Thanks
