### ISSUE TITLE
PyQt4 module is not availabale anymore

### ISSUE THREAD

**Issue by vsnits** [Bitmessage/PyBitmessage#2148]
I'm getting error message that says "you have no PyQt4" while I have installed PyQt5. PyQt4 is no longer maintained :(
   Maybe I have wrong dependencies. Who knows?

**Comment by shportix** [comment]
I had the same problem. The only solution i found is to install environment that maintains PyQt4 (I choose Ubuntu 18.04)

**Comment by vsnits** [comment]
Hm .. suddenly. Tend to become (if not already) abandonware

**Comment by PeterSurda** [comment]
There is a PR for QT5 support, but we don't have automated GUI tests.
