### ISSUE TITLE
openSUSE

### ISSUE THREAD

**Issue by AlexTalker** [Bitmessage/PyBitmessage#221]
I installed and after running in the console I see this (it's only the bottom portion of the log may have gone a lot). The GUI does not start. Help fix it. http://www.tomclaw.com/tomswap/index.php?f=279

**Comment by PeterSurda** [comment]
I just tried the latest mailchuck fork on OpenSUSE 42.1 with Russian locale and it works fine. It must be something that was fixed in the meantime. I can try Arch linux too but I think it will be the same.
