### ISSUE TITLE
Maximized Window bug

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#243]
# Issue
A Maximized window is not restored properly from a minimized state.
# Affects
Windows
# Steps to reproduce
* Open bitmessage and change the window size, so it will not fill up the entire screen.
* Maximize the window
* Minimize the window
* Restore the window (make it visible again)
* Click on the maximize Icon on the top right again. The window will not go back to the previous size it had.

# Solution
It seems like the window size is stored somewhere. This should be removed and the window handling should be done by windows.

**Comment by PeterSurda** [comment]
I confirm I can still reproduce the bug.

**Comment by PeterSurda** [comment]
I can't find a way to fix it, I'll try a bounty.
