### ISSUE TITLE
Inbox message textbox retains formatting

### ISSUE THREAD

**Issue by nimdahk** [Bitmessage/PyBitmessage#248]
After viewing a message as HTML which changes the font via a style tag, and clicking in the text which is altered, subsequent messages viewed will retain the style.

sample:

&lt;html>
&lt;style type="text/css"> 
    #header { font-size: 12px; color: #555; } 
&lt;/style>
&lt;div id="header">Click here, then view another message&lt;/div>

**Comment by PeterSurda** [comment]
Duplicate of mailchuck#106.

**Comment by PeterSurda** [comment]
Fixed in https://github.com/mailchuck/PyBitmessage/commit/78734d81a17bcd3672db6fc764b380c2813634d4
