### ISSUE TITLE
[Enhancement] Message subject should contain only readable characters

### ISSUE THREAD

**Issue by bashrc** [Bitmessage/PyBitmessage#255]
Based upon the recent spam flood it may be a good idea to have an explicit check that the subject line of a message contains only readable characters.  This wouldn't prevent spam, but it would perhaps prevent the easiest type of spam attack where what looks like random characters are being transmitted.

**Comment by PeterSurda** [comment]
I got rid of fixPotentiallyInvalidUTF8Data (at least for the subject), it now uses python's unicode with the __errors = "replace"__ argument. If it's not adequate, please let me know and I'll reopen.
