### ISSUE TITLE
Maybe we created too many threads.

### ISSUE THREAD

**Issue by linkerlin** [Bitmessage/PyBitmessage#270]
In the file of class_singleListener.py :
＃Only one singleListener thread will ever exist. It creates the
＃receiveDataThread and sendDataThread for each incoming connection.
In my view, we can use only one thread for sending all data from all threads.Or we can use gevent's coroutine for replacing real os-thread.

**Comment by PeterSurda** [comment]
Is this still a problem? I haven't experienced any practical negative effects from the number of threads.

**Comment by PeterSurda** [comment]
The network subsystem was redesigned and now it uses fewer threads.
