### ISSUE TITLE
Hardcoded colors in GUI

### ISSUE THREAD

**Issue by neko259** [Bitmessage/PyBitmessage#279]
Some colors are hard-coded (not taken from the system theme). When I use the dark theme I don't see stream number in the last tab because the table has light background and white text. Also, after disabling and enabling an identity it becomes black instead of the default color (white in my theme).

**Comment by PeterSurda** [comment]
@neko259 Is this still a problem? I need to look at it again because the UI is changing. I'll keep this open until I make sure the new UI also takes this into account.

**Comment by PeterSurda** [comment]
I definitely noticed that the default color in the trees, addressbooks and messagelists is taken from the palette. The color after disabling/enabling is only partially solved but I should fix that soon. I'm closing this one, if you still have problems, please reopen.
