### ISSUE TITLE
Option to rescan existing messages when subscribing to an address

### ISSUE THREAD

**Issue by ghost** [Bitmessage/PyBitmessage#292]
This is a feature request.

When subscribing to an address, you only get messages sent after you add the subscription, even if there may be some messages you've already downloaded that were sent to that address.

I'd like to have an option for scanning the pool of messages already downloaded for messages matching that subscription, so that the last days worth of messages can be read.

UI wise, it could be a checkbox in the address entry window that you get when adding a new subscription. The default value is a somewhat arbitrary decision; I know I would want it on always, not sure what others may think.

**Comment by g1itch** [comment]
This seems to be fixed a long time ago in 44618ff
