### ISSUE TITLE
remove the ebuild in the repo

### ISSUE THREAD

**Issue by hasufell** [Bitmessage/PyBitmessage#331]
While it's nice that you provide one, it has a lot of issues and I already imported pybitmessage live ebuild (git based) into gentoo.

When you make a release/tag I can add a version-specific ebuild as well.
http://packages.gentoo.org/package/net-p2p/pybitmessage

**Comment by hasufell** [comment]
Why has this been closed without a comment?

**Comment by PeterSurda** [comment]
I thought this was done. Is it not?

**Comment by hasufell** [comment]
https://github.com/Bitmessage/PyBitmessage/tree/master/ebuildpackage it's still there

**Comment by PeterSurda** [comment]
ok I'll look at it

**Comment by PeterSurda** [comment]
Can I contact you before making the next release to make sure it will build correctly?

**Comment by hasufell** [comment]
sure

**Comment by mailchuck** [comment]
Would you prefer that:

- "ebuildpackage" is removed entirely
- it prints an error telling you to use the official gentoo ebuild

?

**Comment by hasufell** [comment]
Remove it entirely. Gentoo ebuilds don't even work as a single file, unlike archlinux PKGBUILDs. You have to have a real repository.

**Comment by PeterSurda** [comment]
Ok will delete.
