### ISSUE TITLE
Lag in sent tab with big messages

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#366]
If I send big messages (for example with images) it takes ages, until I can select the specific message in the sent tab and delete it after it was sent.
Can you please either:
A: truncate the message, as you do in the Inbox tab
B: display sent messages as HTML per default (it's my message after all)

**Comment by PeterSurda** [comment]
Is this still a problem?

**Comment by AyrA** [comment]
I don't know. I have stopped using the bitmessage client completely after I implemented the gateway.

**Comment by PeterSurda** [comment]
I was able to trigger this by chance it actually is quite annoying. The new code does lazy rendering, the contents will incrementally be appended as you scroll down the message, in 10kB chunks, as long as the scroll bar is close to the bottom. It's as smooth as I think you can do without screwing up something heavily.
