### ISSUE TITLE
Portable mode is not implemented correctly

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#379]
## Issue
if bitmessage runs in portable mode, relative paths are used to store the files, however, these paths are relative to the Currently selected directory and not the application

### Working example

1. Create a folder "BM" directly on the C: drive.
2. Put bitmessage.exe in it and switch to portable mode
3. exit bitmessage
4. Open a command prompt ([WIN]+[R] -> "CMD")
5. Type: **CD /D C:\BM**
6. Type **bitmessage.exe**, The application works as expected

### Invalid example
1. Repeat all steps above, but change the commands from step 5 and 6:
2. 5: Type: **CD /D C:\**
3. 6: Type **BM\bitmessage.exe**, The application starts, but thinks it is in C:\

## Solution
Two possible approaches:
* A: Change the Current Directory from bitmessage. This actually may break batch files if it is not reset
* B: Instead of using raw file names, prepend the path to the bitmessage.exe to the strings

**Comment by PeterSurda** [comment]
The path now works when running it on the checked out directory in terminal, and in bundled Windows and OSX. I haven't tried the portable mode yet or the start on login though.

- [x] Windows bundle
- [x] OSX bundle
- [ ] Portable mode
- [ ] Start on login

**Comment by PeterSurda** [comment]
@AyrA I fixed it the proper way (B), it detects the directory of the executable, or if running from python manually, the directory with the source code (doesn't make much sense but I think it's the correct approach).

@VADemon It works on Windows startup as well.

@grant-olson The same problem probably affected OSX and this probably fixes it too (I'm too lazy to check).

**Comment by PeterSurda** [comment]
Update re: OSX: if you run it from the DMG archive, portable mode doesn't work, and it's not handled very cleanly. If you run it from the unpacked Bitmessage.app, it will put it into Bitmessage.app/Contents/MacOS. I don't know if that's the correct location but I suppose that's acceptable.

**Comment by PeterSurda** [comment]
https://github.com/mailchuck/PyBitmessage/commit/9a789c4e24da3bad5b193be232ed4e4da707be76 disables the "Portable mode" checkbox if the app directory is not writable. This fixes the freezes on OSX, and probably some other cases where it wouldn't work.
