### ISSUE TITLE
Bitmessage requires a professional security audit

### ISSUE THREAD

**Issue by DivineOmega** [Bitmessage/PyBitmessage#381]
"Bitmessage is in need of an independent audit to verify its security."
-- https://bitmessage.org/wiki/Main_Page

"remove Bitmessage until it has been audited"
-- A commit made to the https://prism-break.org/ website in issue https://github.com/nylira/prism-break/issues/465

---

I feel it is important for the project that a professional security audit is seriously looked into soon and funded if necessary. A few points need to be considered and discussed in my opinion.
- How do we consider a security audit 'professional' and thus who performs the task?
  - Individual(s) with relevant (?) qualifications
  - Security audit performed by a specialist company
  - Freelance or corporate penetration testers
- What would be considered a succesful audit?
  - A single professional audit in which no security vulnerabilities are found
  - 2, 3 or more (?) professional audits in which no security vulnerabilities are found
- How often should/can a professional security audit be performed?
  - Possible financial restrictions due to the nature of the project
- How should the professional security audit(s) be funded (if required)?
  - Donations via a crypto-currency would be the obvious choice
  - Other payment methods (?)
  - Possible trust issues of where the funds are held (?)

I'm sure I've not thought of everything by any stretch, but I felt it would be wise to officially set up an issue to discuss these points and any other points that might be relevant.

I suppose one of the most important questions to ask is, does anyone know a person or company suitable to perform such an audit?

**Comment by pedroapero** [comment]
Can this count as an audit? https://odinnsecurity.com/anonymity/in-depth-analysis-of-bitmessage/

**Comment by g1itch** [comment]
> Can this count as an audit? https://odinnsecurity.com/anonymity/in-depth-analysis-of-bitmessage/

No. The overview text written in 2015 about Bitmessage protocol (mistakenly calling it BitMessage) has no relation to code audit.

**Comment by g1itch** [comment]
I'm closing this in favor of more recent #1136
