### ISSUE TITLE
Send to label from address book, not to BM adress

### ISSUE THREAD

**Issue by iShift** [Bitmessage/PyBitmessage#386]
If i have address book, when i send message to specified adress it is more beautiful to show not BM adress -> we need to show label

It is more user frendly !

![1](https://f.cloud.github.com/assets/426427/929583/e1d0b01e-ffea-11e2-8910-903776eb2ea7.PNG)
![2](https://f.cloud.github.com/assets/426427/929584/e1ebddb2-ffea-11e2-8c4e-670bc32226a7.png)
![3](https://f.cloud.github.com/assets/426427/929585/e205d83e-ffea-11e2-81bc-0335e7faf134.PNG)
![4](https://f.cloud.github.com/assets/426427/929586/e20fc362-ffea-11e2-8552-da8e407e3252.PNG)

**Comment by PeterSurda** [comment]
I've come accross this. I need to think about it because there are issues with it.

**Comment by PeterSurda** [comment]
Fixed in mailchuck@ce6f5384ab94ed1b2bb05354eaed66da880462f1
