### ISSUE TITLE
clicking tray icon does not "show pybitmessage"

### ISSUE THREAD

**Issue by super-nathan** [Bitmessage/PyBitmessage#395]
running kde 4.10 I am having pybitmessage start in the system tray. When I left click it does nothing. I must click right and select "show pybitmessage". I believe that this is an incorrect action. Furthermore, there is no way to minimize it back to the tray only. Once I  have shown bitmessage it must be closed and restarted in order to have it only exist in the tray.

**Comment by PeterSurda** [comment]
This has been fixed in https://github.com/mailchuck/PyBitmessage/commit/88ce2c43fbdc6469261cedb06dc79621021dadfe. Tested on Windows 10, OSX El Capitan and Ubuntu 14.04.
