### ISSUE TITLE
Upload OSX installers using GitHub Release feature

### ISSUE THREAD

**Issue by patcon** [Bitmessage/PyBitmessage#408]
Just thinking that it might be better to host the files with the project on github rather than separate locations:

http://sourceforge.net/projects/bitmessagemac/

Would likely also make sense to tag the releases with git tags for organization as well. It's actually rather confusing without tagged releases.

**Comment by PeterSurda** [comment]
Definitely, this is what I want to do (both tagging and releasing OSX releases through github).

**Comment by PeterSurda** [comment]
I consider this basically solved. On my fork, since 0.5.0 I have a mac where I build it on, I release it through github. It will be integrated into 0.6. I also provide PGP signatures for the binaries.
