### ISSUE TITLE
TCP listener runs, evne through proxy.

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#415]
I developed a portable SOCKS proxy for windows and used bitmessage to debug it.
Interesting so far:
It looks like bitmessage (when asked to connect through proxy) still leaves the listener open for some reason. I have bitmessage running through my socks proxy, the listener is still active and I even had an incoming connection from a TOR exit node.
Bitmessage is running through my proxy since about 2 hours.

![Screenshot](https://ayra.ch/images/screens/2013_08_16__23_44_44.png)

**Comment by PeterSurda** [comment]
The listener thread is running when you turn on socks, but if sockslisten is off, then it will not accept the connections, rather they will stuck and not be processed. I just tested it as well. I think that this solution is ok, because it will handle settings change without having to restart.
