### ISSUE TITLE
No coding convention/mixed coding convention

### ISSUE THREAD

**Issue by remyroy** [Bitmessage/PyBitmessage#416]
I have been reading through the code and I feel like this project need some kind of structured coding convention.

[PEP8](http://www.python.org/dev/peps/pep-0008/) would be a good start in my humble opinion.

It would help in reading, understanding and modifying the code.

**Comment by PeterSurda** [comment]
I tried to adhere to PEP8 when writing new code, but when changing old one I don't want to rearrange everything. Maybe at some stage in the future all will be rewritten, but for the time being this is not a priority, notwithstanding my personal preferences.
