### ISSUE TITLE
web app using webrtc

### ISSUE THREAD

**Issue by gedw99** [Bitmessage/PyBitmessage#420]
I use these technologies at work.
Wondering is anyone thinks a mobile client would be useful so you can run this on your mobile phone ?

network - 
webrtc has a datachannel that is pluggable for different signaling
ts UDP and so birectional duplex.

storage -
for file storage / db leveljs which is an implemntation based on the indexdband works in all modern browser as well as mobile ones.
this is a key valeu store and can be quickly indexed and queried too.
Very simple to get going ?

GUI
- easy.

**Comment by PeterSurda** [comment]
I would also like a web / mobile client, but I agree that unless this has to do with pybitmessage it shouldn't be here.
