### ISSUE TITLE
Bitmessage is unscaled for service providers

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#433]
## Issue
I monitored the performance of the bitmessage.ch master server and noticed, that the client actually causes a lot of CPU usage, even when doing nothing. The reason are the 1000 addresses, that are registered on the system, causing the client to try to decrypt the message with every possible private key.

## Possible solutions
Below are a few possible solutions how this can be solved.
### Simple Checksum
Add a Checksum that the receiver can read, without actually need to decrypt the message. The checksum could be as simple as two chars from the bitmessage address (BM-prefix excluded), or a CRC32 sum of the public key.
### Sophisticated checksum
A seperate random string with minimum length to fill on block when encrypting. So only the first block needs to be tried.

**Comment by PeterSurda** [comment]
I also came accross this issue. This is an issue with ECDSA decryption, not PoW. The PoW optimisation does not fix this. I looked at OpenCL-acceleration of ECDSA, but it looks like it can't provide a major improvement. However, https://github.com/bitcoin/secp256k1 can (it didn't exist when you opened this ticket).

Also, you and me are probably the only ones who can actually trigger this problem at the moment. I would like to test libsecp256k1, however, after I can successfully test whether pybitmessage can be build for smart phones. On smart phones, such performance optimisation may affect more people.
