### ISSUE TITLE
OpenSSL on Debian

### ISSUE THREAD

**Issue by rricci2009** [Bitmessage/PyBitmessage#47]
Debian 6.0.6
Kernel 3.7.8
Python 2.6.6
PyOpenSSL and OpenSSL installed.

python bitmessagemain.py 
Traceback (most recent call last):
  File "bitmessagemain.py", line 55, in <module>
    import highlevelcrypto
  File "/home/rricci/Build/sources/PyBitmessage/highlevelcrypto.py", line 1, in <module>
    import pyelliptic
  File "/home/rricci/Build/sources/PyBitmessage/pyelliptic/__init__.py", line 16, in <module>
    from .openssl import OpenSSL
  File "/home/rricci/Build/sources/PyBitmessage/pyelliptic/openssl.py", line 427, in <module>
    raise Exception("Couldn't load the OpenSSL library. You must install it. Error message:"+err)
TypeError: cannot concatenate 'str' and 'exceptions.AttributeError' objects

**Comment by PeterSurda** [comment]
I tested latest mailchuck fork on Debian 8.2 without problems. I also reworked the search for library a bit. If your python or openssl are too old I can't do much about it, but you should have a way of having an openssl library in a different directory to override the system one. I changed how the directory search order works so you may have better luck now. If it still doesn't work, use pyinstaller to bundle the correct openssl version, and then it should load it from the bundle.

**Comment by gabrix73** [comment]
**debian 11**

[](url)https://ibb.co/Rg8nJkX

**Comment by PeterSurda** [comment]
> **debian 11**
> 
> https://ibb.co/Rg8nJkX

Try the appimage: https://appimage.bitmessage.org/releases/
