### ISSUE TITLE
After redirecting stdout, helper_startup breaks through

### ISSUE THREAD

**Issue by merlink01** [Bitmessage/PyBitmessage#487]
All prints are redirected but the prints from:
helper_startup.py line36 are breaking through on windows somehow?

"print 'Loading existing config files from', shared.appdata"

Is it possible to use a logger here?

![prints](https://f.cloud.github.com/assets/1200220/1096918/e7ef57a0-1707-11e3-8a2e-4956211f27c2.jpg)

**Comment by PeterSurda** [comment]
Yea I agree the excessive printouts should be switched to a log.

**Comment by PeterSurda** [comment]
Almost everything is done through a logger now, only about 2 or 3 spots at the very beginning that are printed out before the logger is initialised. The logger is also configurable but it's not documented in the wiki.

**Comment by g1itch** [comment]
It seems solved.
