### ISSUE TITLE
add 'emptyTrash' and 'emptySentTrash' api calls

### ISSUE THREAD

**Issue by chovy** [Bitmessage/PyBitmessage#504]
There needs to be a way to delete the trash from the API. Otherwise trashed message still reside on disk and can be a liability.

```
DELETE FROM inbox WHERE folder ="trash"
DELETE FROM sent WHERE folder ="trash"
```

**Comment by PeterSurda** [comment]
I plan to have a trash expiration.

**Comment by PeterSurda** [comment]
Actually, if your focus is API only, my fork does have this: https://github.com/mailchuck/PyBitmessage/commit/a5c99ad0eef126b886cf29866f9cc059e95f33d0

Issue the "deleteAndVacuum" call, and it will clean trash from inbox, sent and also vacuum the database. I was having some merging problems so the commit looks crappy, but I'll put it correctly into 0.6.

**Comment by PeterSurda** [comment]
With respect to GUI, there is a menu item under "File" labeled "Delete all trashed messages". I didn't realise that.
