### ISSUE TITLE
Logger from Bitmessage overwrites the root logger while used in deamon mode

### ISSUE THREAD

**Issue by merlink01** [Bitmessage/PyBitmessage#513]
I'm using the Bitmessage native API: https://github.com/merlink01/PyBitAPI

I'm writing a Feedreader which should use Bitmessage as a Plugin.

But if I start the Plugin, the Root Logger kills all my logging output from the Main Program.

Secondly, the Bitmessage Client trashes the stdout with so many messages, that writing a commandline program is really problematic.

First of all I think we should use logging or printing, not both.

Secondly I'm thinking about a solution not to overwrite my root logger.

Any Ideas?

**Comment by PeterSurda** [comment]
It looks like it's closed, reopen if you still have this problem.
