### ISSUE TITLE
Quotation chars and word wrap

### ISSUE THREAD

**Issue by snitko** [Bitmessage/PyBitmessage#540]
One feature I think BitMessage really needs and one that would be relatively easy to implement is this:

1. It would be really cool to have the previous message cited not below "---------------", but rather with > characters, like this:

http://www.ghidinelli.com/wp-content/uploads/2010/11/thunderbird_reply_partial_quote.png

(blue highlighting is optional, though would be cool).

2. Hard word wrap. This one goes hand in hand with quotation chars, actually. It would be impossible to have proper quotation chars without a word wrap. The idea is that a text should not be more than N chars wide (back in the days it was 80, but I don't think it should be this these days). Whenever a user typing the text reaches this N character in line, after he finishes typing the current word a newline is automatically added.

With these two features, the quality of communication would really increase.

**Comment by PeterSurda** [comment]
It actually does word wrap already and I have been using it already. It should be in the latest stable, 0.4.4. If you still experience this issue, try the latest https://github.com/mailchuck/PyBitmessage fork. Reopen if you still have problems with this .
