### ISSUE TITLE
sending a message to a chan from GUI is voodoo magic

### ISSUE THREAD

**Issue by themighty1** [Bitmessage/PyBitmessage#546]
When we add a chan, it is listed in "Your identities"
So when I want to send a message to a chan, I go to the Send tab, select From "mychan", To...click Load From Address Book, but the chan is not there!

It really requires non-trivial knowledge to figure out that the chan address must be copied and pasted into the To field.

I suggest that the chan should be added to the Address Book as well.
And when the user chooses a chan in the From list, the To field must be automatically populated with the chan name.

**Comment by PeterSurda** [comment]
The new UI has this improved, but there are still some clumsy things.

**Comment by PeterSurda** [comment]
- [x] chans should be in addressbook since https://github.com/mailchuck/PyBitmessage/commit/676ea5544ee418a895a7fdc288d6f6880f09dbe3
- [ ] reply-to-user should be an option, see mailchuck#2

**Comment by PeterSurda** [comment]
Since https://github.com/mailchuck/PyBitmessage/commit/cf383855891e5f72e8c9196882e8cf289a361b4a you can choose to reply to chan or sender if replying in a chan.
