### ISSUE TITLE
Linux/Ubuntu - Minimize to tray when hitting X button not working.

### ISSUE THREAD

**Issue by ripplecripple** [Bitmessage/PyBitmessage#564]
My opinion on this is that it should support minimize to tray feature when hitting X button for better user experience. I pretty understand that it is not supported now on Linux OS but it is pretty necessary.

**Comment by PeterSurda** [comment]
You're right, I tried to reproduce and it's still like that, even though the settings option "minimize to tray" is enabled.

**Comment by PeterSurda** [comment]
There is now a separate checkbox "Close to tray".
