### ISSUE TITLE
Feature Request: add Sender to Blacklist

### ISSUE THREAD

**Issue by merlink01** [Bitmessage/PyBitmessage#584]
In the Message List there could be an entry in the rightclick menu:

Add Sender to Blacklist, this could be practical :-)

**Comment by PeterSurda** [comment]
This was requested by several people, it appears to be important.

**Comment by PeterSurda** [comment]
This has been done in mailchuck:c09981bd420d3c0233132967235d5e0eb40acb07 and mailchuck:51232d3dd9b9620d0c53af56c6dcd1ef7801971e and the feedback has been very positive, it really appears to significantly improve the user experience with spam.
