### ISSUE TITLE
Exporting message to HTML shifts if new arrive

### ISSUE THREAD

**Issue by MidnightLightning** [Bitmessage/PyBitmessage#589]
If you right-click and choose "Save Message as...", and then on the file location box if you sit and wait for a new message to come in, when you then hit save, the message that gets saved is not the one you originally clicked on, but one newer.

It seems the index offset in the list is what's grabbed and queued for export, not the message itself. That should be fixed, to ensure the message you want is actually the one you get.

Running on OSX 10.6.8

**Comment by PeterSurda** [comment]
I can't reproduce this (OSX 10.11.2).
