### ISSUE TITLE
OSX shouldn't raise error messages if growl isn't installed.

### ISSUE THREAD

**Issue by grant-olson** [Bitmessage/PyBitmessage#607]
User on DevTalk reported error messages because they don't have growl installed.  growl provides the pop up status updates on OSX.  It is apparently no longer open source and costs $3.99 to install.

The app should silently ignore things and not attempt to do a status update if growl isn't installed.

I'll get a PR together this weekend.

**Comment by PeterSurda** [comment]
I have 10.11 El Capitan. I did a clean base OS install and then got the packages through homebrew as described in the building instructions. I can't reproduce anything like this. I am not an OSX expert, but PyBitmesage does seem to use some sort of notification system on OSX, and it appears to work just like on my linux machine. I don't know what it's called but I didn't have to pay for anything or install anything unexpected. It works both when I run python manually from the terminal, as well as when I run in from the bundle crate by py2app.
