### ISSUE TITLE
Second bitmessage instance should pop up the window of the first one and quit, and not run in parallel

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#630]
I launched the second copy of bitmessage from the same user on the same display, and it launched. It showed two windows and two tray icons.

This shouldn't happen. It should locate the first instance, make its window active and quit. Chrome browser, for example, does this.

The second instance also shouldn't be allowed to launch off the same database on another screen, since this doesn't make sense.

It is possible to find the window of the original instance through the window manager.

**Comment by PeterSurda** [comment]
This is a very valid point.

**Comment by PeterSurda** [comment]
I did a quick test on Windows. It looks like when you launch it in a different way, for example, once from the command line using python, and once from the bundled EXE, it doesn't detect the second instance correctly. Only if you run two instances from python at the same time, or run the EXE twice at the same time, will it detect the second instance correctly.

**Comment by thelink2012** [comment]
Perhaps using a UUID as the `basename` in `singleton.py` of the lock file would resolve the issue instead of taking it off argv.

**Comment by PeterSurda** [comment]
I think that a combination of current UID and configuration path would be better, or maybe even only the configuration path.
