### ISSUE TITLE
Message status in the wrong language for current session.

### ISSUE THREAD

**Issue by Steinhagelvoll** [Bitmessage/PyBitmessage#644]
My Bitmessage is set to german. Behind the Messages that I send during the current session it says: "Acknowledgement re...."

Behind the Messages that I send in a previous session it says: "Bestätigung erhal..."(which is nice and german)

The "Doing work ..." part is always in english.
![screenshot 2014-02-13 17 32 00](https://f.cloud.github.com/assets/6518935/2162015/29ff8898-94cd-11e3-8ecd-64bd4ab77a25.png)

**Comment by PeterSurda** [comment]
I speak German, I'll fix this.
