### ISSUE TITLE
Connected "light" stays yellow after the IP address change

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#645]
I had bitmessage running, when my internet service went down for a while and then came back with a different IP address.

Now bitmessage only has yellow light (not green), even though firewall settings didn't change at all. Restarting it makes a green light come back.

I think bitmessage client assumes that IP address never changes, and keeps the old value forever, and after an IP change this causes connectivity problems.

Maybe, when the client connects to the peer, peer response should also include the IP address of this client as the peer sees it, so that it will be easy to detect a mismatch.

**Comment by PeterSurda** [comment]
The client does not distribute its own listening IP address, only its port. The remote side determines the IP address based on the incoming connection. It may take some time for this new IP address to propagate. I think if you waited, it would have fixed itself. Maybe it was waiting for timeouts for outgoing connections, and that's what was keeping your new IP from propagating. When you restarted it, it tried to connect immediately, so it propagated its new IP immediately too.
