### ISSUE TITLE
trashMessage bug

### ISSUE THREAD

**Issue by stevedekorte** [Bitmessage/PyBitmessage#649]
I'm using the XMLRPC API with a headless pybitmessage and the trashMessage API appears to work at first but if the message is relatively new, it reappears after a while. 

Could it be that pybitmessage doesn't keep a record of which messages have been deleted and periodically fetches the message again from the memory pool of other nodes it's connected to?

**Comment by PeterSurda** [comment]
I do the same thing, I run an email gateway. I haven't experienced this issue. Maybe the recent updates fixed it, or maybe you're not using the XMLRPC correctly (watch out for threading). Reopen if still an isue.

**Comment by stevedekorte** [comment]
I'm not sure if it's still a problem. In order to deal with it, I have my client maintain an independent database of what it's deleted.

**Comment by PeterSurda** [comment]
Ok I'll keep it closed. If you want, you can check out the current master branch and retest it.

**Comment by stevedekorte** [comment]
I'm working on other projects atm but will try to remember to take a look when I get back to this. Thanks for looking at this bug.
