### ISSUE TITLE
Debian Directory Prevents PyBitmessage From Being Officially Packaged In Debian

### ISSUE THREAD

**Issue by appleorange1** [Bitmessage/PyBitmessage#651]
If PyBitmessage is to appear in the Debian repositories, it seems that the Debian directory needs to be removed from upstream. For an explanation as to why, please see: https://wiki.debian.org/DebianMentorsFaq#What.27s_wrong_with_upstream_shipping_a_debian.2F_directory.3F

**Comment by PeterSurda** [comment]
It looks like this was merged.
