### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by hasit** [Bitmessage/PyBitmessage#655]
How about adding standard keyboard shortcuts?
for example:
shift + command + D -> send message (for osx)

I am interested in adding this feature. Would someone guide me? I am new to it QT but familiar with coding in Python.

**Comment by PeterSurda** [comment]
Also, Delete key should work on the messagelist even if other part of the window is in focus.

**Comment by PeterSurda** [comment]
There are now following keybindings (no Ctrl/Shift/Meta needed):
(N)ext, (P)revious, (R)emply, (C)ompose, (F)ind

Also Del works if the focus is on the message body too (not when on the tree because that might cause confusion when someone wants to delete an account or something).
