### ISSUE TITLE
Running multiple servers on one machine

### ISSUE THREAD

**Issue by stevedekorte** [Bitmessage/PyBitmessage#671]
I have a bitmessage client and also a marketplace app built on top of bitmessage that I'd like to run on the same machine. Ideally, I'd like to run them as separate servers on the same machine and for each to have it's own set of identities/config. Is this possible atm? It seems to me this will be a common use case if other applications are built on top of bitmessage and telling users of such apps to just avoid running a bitmessage client or other BM based apps seems like a less than ideal solution.

**Comment by Abdullah114** [comment]
@stevedekorte do you mean you want to create your own Bitmessage network? Have you managed to do it? If yes, how? I want to create my private Bitmessage network to test some new features.

**Comment by stevedekorte** [comment]
@Abdullah114 No, we just wrote an alternative client.
