### ISSUE TITLE
Minimum supported Python version

### ISSUE THREAD

**Issue by bmng-dev** [Bitmessage/PyBitmessage#689]
I think it is about time that the minimum supported version of Python be determined. Littered throughout [reddit](https://pay.reddit.com/r/bitmessage/), the [forums](https://bitmessage.org/forum/) and this [issue tracker](https://github.com/Bitmessage/PyBitmessage/issues) are posts from users experiencing difficulties running PyBitmessage. Most of these boil down to using older versions of Python. Since PyBitmessage has for a while now mandated Python 2.7.5 on OS X and just recently extended this to Windows (there doesn't seem to be any documentation for the rationale behind these constraints) it shouldn't be too hard to require that on all platforms.

**Comment by strypey** [comment]
Minimum supported Python version now needs to exclude all 2.x versions on all OS, as [Python 2 is no longer being maintained from the start of 2020](https://pythonclock.org/).

**Comment by PeterSurda** [comment]
PyBitmessage isn't fully ported to python 3 yet, so there's nothing I can do about it at the moment.

**Comment by strypey** [comment]
@Peter Šurda wrote:
> PyBitmessage isn't fully ported to python 3 yet, so there's nothing I can do about it at the moment.

OK. Seems like finishing that port is a top priority if you don't want
unmaintained Python dependencies creating security flaws in Bitmessage.
