### ISSUE TITLE
AttributeError: Dialog instance has no attribute 'set_background_title'

### ISSUE THREAD

**Issue by atoponce** [Bitmessage/PyBitmessage#711]
When running the curses interface, I get the following Traceback when hitting the [Enter] key under the "Your Identities" tab to create a new address:

    Loading existing config files from /home/aaron/.config/PyBitmessage/
    An Exception occurred within isOurOperatingSystemLimitedToHavingVeryFewHalfOpenConnections: invalid version number '#1 SMP Debian 3.14.2-1 (2014-04-28)'
    Running with curses
    Loading inbox messages...
    Loading sent messages...
    Loading address book...
    Traceback (most recent call last):
      File "./src/bitmessagemain.py", line 272, in <module>
        mainprogram.start()
      File "./src/bitmessagemain.py", line 243, in start
        bitmessagecurses.runwrapper()
      File "/home/aaron/src/bitmessage/src/bitmessagecurses/__init__.py", line 984, in runwrapper
        curses.wrapper(run)
      File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
        return func(stdscr, *args, **kwds)
      File "/home/aaron/src/bitmessage/src/bitmessagecurses/__init__.py", line 1030, in run
        handlech(stdscr.getch(), stdscr)
      File "/home/aaron/src/bitmessage/src/bitmessagecurses/__init__.py", line 383, in handlech
        d.set_background_title("Your Identities Dialog Box")
    AttributeError: Dialog instance has no attribute 'set_background_title'

Information about my operating system:

    $ cat /etc/issue
    Debian GNU/Linux jessie/sid \n \l
    $ uname -a
    Linux pinyin 3.14-1-amd64 #1 SMP Debian 3.14.2-1 (2014-04-28) x86_64 GNU/Linux
    $ dpkg -l python
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                 Version         Architecture    Description
    +++-====================-===============-===============-=============================================
    ii  python               2.7.8-1         amd64           interactive high-level object-oriented langua
    $ dpkg -l python-dialog
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                 Version         Architecture    Description
    +++-====================-===============-===============-=============================================
    ii  python-dialog        2.7-1           all             Python module for making simple Text/Console-

**Comment by PeterSurda** [comment]
I was unable to get the curses interface running at all.

**Comment by PeterSurda** [comment]
I got another question regarding curses, so I looked at it. Once I got around some of the most problematic problems that require a newer version of pythondialog, I see that it's in an unfinished state and barely works at all. I will probably scrap it, and instead add SMTP/IMAP interface so that you can integrate it with a terminal email client like mutt. That will give you a better user experience, more flexibility and is a better use of my time.

**Comment by PeterSurda** [comment]
I forgot, during the mailchuck updates, I added a cli for the API, you can use that instead, at least that works fine:

    python src/bitmessagecli.py
