### ISSUE TITLE
Ubuntu SLOW with many terminal messages

### ISSUE THREAD

**Issue by ShepTanner** [Bitmessage/PyBitmessage#724]
I started as per wiki.  I have Py 2.7.6.  Bitmessage window opens but runs SLOW while many debug messages are whizzing by on the terminal window.

**Comment by PeterSurda** [comment]
You can redirect the output. Just add 

    &> /dev/null

at the end of the line, for example

     src/bitmessagemain.py &> /dev/null

Alternatively, run it from the Launcher, the bitmessage distribution contains a file in desktop/pybitmessage.desktop that you can use to add bitmessage to the Launcher. For example,

  cp desktop/pybitmessage.desktop ~/.local/share/applications

You may have to adjust the line which says Exec for the correct path etc. Let me know if it still doesn't work well.
