### ISSUE TITLE
crash on start (OS X)

### ISSUE THREAD

**Issue by davidak** [Bitmessage/PyBitmessage#728]
i had 0.3.5 working on OS X 10.6.8, now i updated to the newest 0.4.4 and it don't start anymore.

```
Process:         launchd [41724]
Path:            /Applications/Bitmessage.app/Contents/MacOS/Bitmessage
Identifier:      org.pythonmac.unspecified.Bitmessage
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [235]

Date/Time:       2014-10-20 20:04:05.342 +0200
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          210986 sec
Crashes Since Last Report:           3
Per-App Crashes Since Last Report:   1
Anonymous UUID:                      7C4F96F2-E52A-4BEB-B70E-58F1A76B44BD

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Crashed Thread:  Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0xfffffffffffffff8

Binary images description not available

Model: iMac11,3, BootROM IM112.0057.B00, 4 processors, Intel Core i7, 2.93 GHz, 16 GB, SMC 1.59f2
```

**Comment by halo** [comment]
For me, the downloaded BitMessage `0.4.4` binary launches just fine on a freshly installed OS X `10.10.1` (I have the command line tools installed though).

**Comment by davidak** [comment]
it works on OS X 10.9.5

**Comment by 3a299d0c** [comment]
I have a machine with Mac 10.7.5 on it.  I am not a coder, but if you'd like to give me explicit, step-by-step instructions on what I need to do, I'd be happy to help.

**Comment by PeterSurda** [comment]
@3a299d0c Check out the official building instructions: https://bitmessage.org/wiki/Compiling_instructions#With_Homebrew_package_manager

The first step is obsolete, you should replace it with the installation explained here:

http://brew.sh/

I use homebrew so I recommend you do too. I had no OSX experience prior to this and I found it easy.

**Comment by PeterSurda** [comment]
Well my test/build machine has the latest OSX (10.11.2). I installed 10.7.2 in a VM and the binary doesn't work because it's missing a compatible sqlite3 library. I'll see if I can get it working.

**Comment by PeterSurda** [comment]
I now have an environment on 10.7.5. PyBitmessage runs and builds on it. I hope I can make future releases that run on 10.7.5 and newer.

**Comment by PeterSurda** [comment]
The 10.7.5 build runs both on 10.7.5 and 10.11.2. So from 0.5.6 on I should be able to maintain backwards compatibility.
