### ISSUE TITLE
Dialog buttons are not localized

### ISSUE THREAD

**Issue by digital-dreamer** [Bitmessage/PyBitmessage#737]
Standard buttons like “OK” and “Cancel” always appear in English. Is it just a problem on my system, or do you see it too? These translations are bundled in QT, but maybe we need to enable them somehow.

**Comment by PeterSurda** [comment]
What OS are you using and what language settings do you have?

**Comment by PeterSurda** [comment]
I can reproduce this. QT does not automatically localise QMessageBox buttons, it needs to be done separately.

**Comment by PeterSurda** [comment]
It looks like you have to load QT locales and this didn't happen. This fixes it, but I still need to test / refix for frozen (Windows / OSX executable).

**Comment by PeterSurda** [comment]
Yea it doesn't work in frozen right away, needs to be addressed separately.

**Comment by PeterSurda** [comment]
Together with https://github.com/mailchuck/PyBitmessage/commit/a9f45c80611ba2d3e5c8ccea1da3286c68d8861e and https://github.com/mailchuck/PyBitmessage/commit/5ed6df743614ab5a78a0c93651e0945f256cab02 the problem is fixed.
