### ISSUE TITLE
Problems with context menu of app icon on clock bar for Yosemite

### ISSUE THREAD

**Issue by e5faf2** [Bitmessage/PyBitmessage#743]
I have some of suggestions about Mac OS X context menu.
First item is status of connectivity. So, it will be good if it will be named as "Status: Connected", or something. Also its label must be not selectable, because its selection doesnt perform any action. It will be helpful to have connect/disconnect feature here.
Second menu item "Show Bitmessage" works bad, because if bitmessage app window behind of any other app window, this "show" feature doesnt present bitmessage app window to the front side.
All other items on this context menu with the same problem. If user select context menu item app must goes to the front side.
Mac OS X. bitmessage v0.4.4.

**Comment by PeterSurda** [comment]
I'll take a look at it.

**Comment by PeterSurda** [comment]
I'll keep "Connected" as it is, I think it's better this way.

With respect to the other thing, you're right, it doesn't work (I recall a similar issue on linux).
