### ISSUE TITLE
Split receive pub. messages & decrypt

### ISSUE THREAD

**Issue by TheCherry** [Bitmessage/PyBitmessage#744]
Hi,

is there anyway to use a BM-Client just to receive the public messages, copy them to a offline decive there it can be decrypted?
Do save the BM-Client a big "BlockChain" with all messages or delete it a message directly after no successfully decrypt? If this need some work in the sourcecode, give me a hint there I have to start.

**Comment by PeterSurda** [comment]
The node does not know if the message is for itself or not without decrypting it. The inbox/sent folders are saved separately from the P2P network data and don't know about each other. For the time being it does not look like a realistic request.
