### ISSUE TITLE
Package from PPA installs in Debian but doesn't create menu entry and won't connect to network

### ISSUE THREAD

**Issue by gasull** [Bitmessage/PyBitmessage#746]
The package from PPA installs on Debian testing, but it doesn't create an entry in the menu (I'm using Xfce4).

Starting it from the command line with `pybitmessage` opens the program but it never connects to the network, timing out connecting to every node, and always showing the red dot.

I used the [PPA from fuzzgun/motters/bashrc](https://launchpad.net/~fuzzgun/+archive/ubuntu/pybitmessage) that I assume is semi-official, since [he wrote code in the debian directory of the project](https://github.com/Bitmessage/PyBitmessage/tree/master/debian).

(I'm not sure if this the place to report this.  Please correct me if I'm wrong.   Should it be reported in Launchpad instead?)

**Comment by vxbinaca** [comment]
Use the git version and just remember to ```git pull``` within the directory instead of relying on apt to manage it's updates.

**Comment by gasull** [comment]
Having a working .deb package would be a first step towards having PyBitmessage included in Debian and Debian-based distros like Ubuntu.

**Comment by g1itch** [comment]
This is obsolete.
