### ISSUE TITLE
Messages with same content

### ISSUE THREAD

**Issue by ungenannter** [Bitmessage/PyBitmessage#748]
If the client receives several messages with the same content it shows only one message in the inbox (acknowledgement is sent like normal). Even if one message is already in the trash and the inbox is empty.
Can someone confirm that ?

**Comment by Kagami** [comment]
@Atheros1 Could we please disable this behavior? I think it may cause great confusion for the users. There was forum thread some days ago: https://bitmessage.org/forum/index.php?topic=4258, also I experienced the same problem recently: https://www.reddit.com/r/bitmessage/comments/2utvh8/email_to_bitmessage_gateway_service_launched_in/corsak8

I think the current behavior is completely nonintuitive.

**Comment by Atheros1** [comment]
Yes, I think that that would be a good idea. I can take it out.

**Comment by Atheros1** [comment]
Actually, how about this: The signature of a message, or a hash thereof, can be used as a temporary UUID since it contains a randomly generated component. We can store the hash of the signature and check if it is unique instead of the sender + receiver + subject + message.

**Comment by Kagami** [comment]
Why we can't just use inventory hash (hash of the object message payload) to distinguish duplicated objects? If some component of the object was changed, then it would be another inventory hash.

**Comment by Atheros1** [comment]
Because the inventory hash includes the nonce which can be changed by attackers. The attacker would simply find the next nonce and rerelease the object. The object would have a different inventory hash and would show up as a duplicate message in the recipient's client.

**Comment by Kagami** [comment]
Ah, I see. Haven't thought at all about that kind of attack vector.
So yes, you are right, it can be some hash of the rest of the object or just the signature.

**Comment by Kagami** [comment]
Also, I'm wondering that is the original motivation to sign everything except the nonce? I know several appliances where it can be useful (e.g. doing the POW and encryption on a different computers), but it the same time it allows some kind of replay attacks.

**Comment by Atheros1** [comment]
Is your question "Why sign the time?"? Or is your question "Why not sign the nonce?"?

**Comment by Kagami** [comment]
Why not sign the nonce?

**Comment by Atheros1** [comment]
We cannot sign the nonce because the nonce covers the signature. We cannot create a nonce without a signature.

**Comment by PeterSurda** [comment]
Re: Atheros1: "Because the inventory hash includes the nonce which can be changed by attackers."

I suspected it is something like this, this sounds like the infamous malleability attack on Bitcoin. I thought that this is the reason why it was implemented like this, but I don't know that much about the protocol, so I'll wait until someone else fixes it properly.

**Comment by Atheros1** [comment]
Indeed, it is similar to the malleability attack. Any part of any object can be changed by anyone if the attacker is willing to recompute the POW. The only part of the object that the attacker can change that won't result in the object being rejected by the receiver is the nonce.

**Comment by Kagami** [comment]
Cool, thanks!

**Comment by ungenannter** [comment]
:+1:
