### ISSUE TITLE
Error creating address

### ISSUE THREAD

**Issue by AyrA** [Bitmessage/PyBitmessage#761]
A print statement seems to create a division by 0 exception

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\AdminRoot\TBM\PyBitmessage\src\class_addressGenerator.py", line 101,in run
    print 'Address generator calculated', numberOfAddressesWeHadToMakeBeforeWeFoundOneWithTheCorrectRipePrefix, 'addresses at', numberOfAddressesWeHadToMakeBeforeWeFoundOneWithTheCorrectRipePrefix / (time.time() - startTime), 'addresses per second before finding one with the correct ripe-prefix.'
ZeroDivisionError: float division by zero
```

Sidenote: the ```dotimingattackmitigation``` was set to false

**Comment by AyrA** [comment]
For me this is a critical error, since the generatd address is never stored on the file, as the offending print statement is located before the code that saves the address.

The error seems to happen if the device is quick enough, that start and end time are on the same half second.

**Comment by Atheros1** [comment]
Thank you AyrA
