### ISSUE TITLE
Raspbian - "invalid version number"

### ISSUE THREAD

**Issue by gnumech** [Bitmessage/PyBitmessage#763]
Running Raspbian on a model A; starts up fine and connects to well over 50-60 peers, but cannot seem to accept incoming messages.  Port is forwarded in network router and iptables, the only clue I get is a non-fatal traceback during startup:  
  
    An Exception occured within isOurOperatingSystemLimitedToHavingVeryFewHalfOpenConnections: invalid version number '#730 PREEMPT Fri Dec 19 18:31:24 GMT 2014'
    Exception in thread Thread-7:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
        self.run()
    File "/home/$USER/Git/PyBitmessage/src/class_outgoingSynSender.py", line 49, in run
        peer = self._getPeer()
    File "/home/$USER/Git/PyBitmessage/src/class_outgoingSynSender.py", line 34, in _getPeer
        peer, = random.sample(shared.knownNodes[self.streamNumber], 1)
    KeyError: 1  
  
The version number is that of a stable Raspbian from Raspberry Pi's [download page](http://www.raspberrypi.org/downloads/).  Doing some digging, it looks as if a threading.py routine is unable to comprehend the version number syntax, which may mean this is a bigger issue with Python.  Can PyBitmessage sidestep this with a "Raspbian clause" in OS checking or some other workaround until threading.py and Raspberry Pi distro naming play nice?

**Comment by Atheros1** [comment]
Thank you for reporting the potential problem. 
The 'isOurOperatingSystemLimitedToHavingVeryFewHalfOpenConnections' code is already wrapped in an error handler in case something goes wrong. It spits a warning out to the console and just keeps going. So that's okay. 
The traceback shown is separate and is not okay. I've seen that part of the code throw that exception when the knownNodes list is empty. Can you imagine a reason why this might have happened? (Like where you hacking around with something?)

**Comment by timothyparez** [comment]
I've had the same problem with the code clones directly from this repo, no changes made.

**Comment by Atheros1** [comment]
When you say that you had the same problem, was that the 'Invalid version number" problem? Or the

    peer, = random.sample(shared.knownNodes[self.streamNumber], 1)  
    KeyError: 1

problem?

**Comment by timothyparez** [comment]
The invalid version number problem

**Comment by PeterSurda** [comment]
There was a bug that was triggered on some systems where one thread was too slow and it caused another thread to access knownNodes before it was initialised. I fixed it in mailchuck@d48af87b1425746da94297d4da56dcd5d9d3f108. Let me know if it reappears.
