### ISSUE TITLE
inv/getdata max message size

### ISSUE THREAD

**Issue by Kagami** [Bitmessage/PyBitmessage#767]
Spec says that message payload length must not exceed 262144 bytes.
At the same time inv/getdata payload may be up to the `50000*32 + 3 = 1600003` bytes in size which is bigger.
PyBitmessage currently doesn't check for payload limit for inv/getdata messages, only object messages are checked. Is it wrong behaviour? Should other Bitmessage implementations ignore the payload limit in order to be compatible with the PyBitmessage?
Thanks.

**Comment by Atheros1** [comment]
This is the correct behaviour. I tried to make this clearer on the wiki.

    The maximum allowable length of an object (not to be confused with the objectPayload) is 2^18 bytes. 

I don't see where it says that the message payload length must not exceed 262144 bytes.

**Comment by Kagami** [comment]
>I don't see where it says that the message payload length must not exceed 262144 bytes

Here: https://bitmessage.org/wiki/Protocol_specification#Message_structure
>4 	length 	uint32_t 	Length of payload in number of bytes. The length may not exceed 2^18 bytes. Longer messages must be ignored.

**Comment by Atheros1** [comment]
Oh my. Right you are! That is a mistake. I've fixed it.

PyBitmessage has a sanity check for message size:
https://github.com/Bitmessage/PyBitmessage/blob/master/src/class_receiveDataThread.py#L134

**Comment by Kagami** [comment]
Ok, thanks.

**Comment by Kagami** [comment]
I've found that in fact version messages may be larger than 1.6M per spec (though it's impractical):
4 + 8 + 8 + 26 + 26 + 8 + (9 + 2^64) + (9 + 2^64*9) = 184467440737095516258 = more than 171798691840GB.

@Atheros1, what do you think, should we limit `user_agent` and `stream_numbers` lengths in version message?

**Comment by Atheros1** [comment]
Wouldn't PyBitmessage's 
    if payloadLength > 1600100:
check already cover this? If someone packs a ton of data into a version message, or any other message, it would get caught by this check and thrown out.

**Comment by Kagami** [comment]
Yes, you are right. I mean that per spec this messages are fully valid. So I asked about spec changing.

**Comment by Atheros1** [comment]
I'm not sure. What do other protocol specs do in the face of potentially insane but valid behavior? 
We could, perhaps, say that using a user agent longer than 2000 characters, or listing more than 160000 streams is NOT RECOMMENDED where "NOT RECOMMENDED" is defined in RFC2119.

**Comment by Kagami** [comment]
Yea, something like this would be ok.
Or we can simply forbid user agent longer than 2000 characters and listing more than 160000 streams in version messages (addr/inv/getdata messages have similar limits).

**Comment by Atheros1** [comment]
Okay. We can make it mandatory. Let's use 5000 characters and 160000 streams so as to be as lax as we reasonably can be.

**Comment by Atheros1** [comment]
I've made the change to the wiki.

**Comment by Kagami** [comment]
Thanks!

**Comment by Atheros1** [comment]
Thank You!
