### ISSUE TITLE
Stream state in receiveDataThread may become corrupted

### ISSUE THREAD

**Issue by Kagami** [Bitmessage/PyBitmessage#776]
Hi. As I understand this lines of code: https://github.com/Bitmessage/PyBitmessage/blob/master/src/class_receiveDataThread.py#L134-L139
If `paylodLength` specified in message header is too big we cut as many bytes from data buffer as we can and go to the next cycle.
The problem is that we don't check whether we've fetched all message already (though this is right decision because sender may specify up to 4G bytes in this field), we just cut it and try to assemble new message.
So the stream may get the following state:

Buffer at first iteration:
```
[[length] [.........................big payload...................]] [[length2] [payload2]]
                                  ^ cut here
```

Buffer at second iteration:
```
[.......big payload...................]] [[length2] [payload2]]
```

At the second iteration we try to match message fields (magic, command, length, etc.) from the begging of the data buffer. And we will constantly fail now because buffer doesn't start with a message.

I think we should try to match magic field as mentioned in spec, shouldn't we?

**Comment by Atheros1** [comment]
Yes, that's true, we could search for the magic bytes. I believe, though, that if we simply read data off of the wire and clear it if it doesn't start with the magic bytes, once the remote node stops sending whatever it is sending, then, after that, there is a high probability that the next data to arrive would start with the magic bytes. It's worked well so far. 
One might say that, if anything, it would be more useful to put work into code which disconnects from the remote node seeing as it is misbehaving. Although seeing as there are probably about half a million ways to misbehave and waste bandwidth, this probably isn't worth it either.

**Comment by Kagami** [comment]
>once the remote node stops sending whatever it is sending, then, after that, there is a high probability that the next data to arrive would start with the magic bytes

Yea, seems like in normal circumstances stream should normalize after some time. Anyway, normal nodes shouldn't send messages of that size, it may be also other unfixable implementation errors. This issue is rather "good to have" and enhancement than some serious bug.
The only use case which comes to my mind is to improve communication between partially compatible Bitmessage implementations (e.g. between node which implements protocol v3 and node which implements some protocol vX with bigger messages).

>Although seeing as there are probably about half a million ways to misbehave and waste bandwidth

I think "error counter" may be used to address this issue. If node does a lot of strange things, we may disconnect and ban it for some time.

**Comment by Atheros1** [comment]
I believe that bitcoin-core has such an error counter. I don't know how they behave exactly but I do know that it has had the side effect that Tor users can be excluded from the network without much trouble. There are some tradeoffs. Surely some people are aware of the correct balance between the tradeoffs but I am not yet. The fact that Bitcoin has an error punishing mechanism leads me to believe that it provides compelling benefit.
