### ISSUE TITLE
display more than 1 GB traffic

### ISSUE THREAD

**Issue by davidak** [Bitmessage/PyBitmessage#780]
maybe it is stuck or will change if it is over 2 GB.

it should display `1,25 GB` (maybe `.` in english localization)

![bildschirmfoto 2015-02-10 um 15 02 25](https://cloud.githubusercontent.com/assets/91113/6128448/4540152e-b136-11e4-8b84-ba54e73fdc35.png)

**Comment by Atheros1** [comment]
Yes, it will go to 2 GB eventually.

**Comment by davidak** [comment]
could you format that integer to have always 2 decimal places?
