### ISSUE TITLE
When using trustedpeer, flooding check should not be done.

### ISSUE THREAD

**Issue by Atheros1** [Bitmessage/PyBitmessage#786]
When using a trustedpeer, these checks shouldn't be done because if there are more than 200K objects active in the network then we won't get all of them.

https://github.com/Bitmessage/PyBitmessage/blob/33848692995f172f55ef51a86f7bc1b50776cca7/src/class_receiveDataThread.py#L407
https://github.com/Bitmessage/PyBitmessage/blob/33848692995f172f55ef51a86f7bc1b50776cca7/src/class_receiveDataThread.py#L432

**Comment by Atheros1** [comment]
Thanks to BM-2cTWtwwQvhcTMnEgT1bhWDYrC6VpF9Jxve for reporting.

**Comment by PeterSurda** [comment]
Makes sense and looks like I can do that.

**Comment by PeterSurda** [comment]
@Atheros1 If you want you can review it. I didn't test it extensively, I just check that trustedPeer is not broken.
