### ISSUE TITLE
POW uses excessive CPU

### ISSUE THREAD

**Issue by stevedekorte** [Bitmessage/PyBitmessage#793]
I'm using a high pow setting and when I send a message, the bitmessage server appears to launch 8 processes (on a 4 core laptop) which all attempt to consume all available CPU resources. Maybe a config option to set the max # of processes used to do the pow (e.g. 1) would solve this issue?

**Comment by xiaokangwang** [comment]
And by doing so, the POW will be 4 times slower. (theoretically)

**Comment by stevedekorte** [comment]
Yeah, that's ok. Taking a few minutes for the pow is acceptable but making the desktop unusable is not.

**Comment by stevedekorte** [comment]
Looks like there is a hidden config option called maxcores that does this - problem solved.
