### ISSUE TITLE
"minimize on close" - option

### ISSUE THREAD

**Issue by Adeor** [Bitmessage/PyBitmessage#803]
would it be possible to add a "minimize on close" - option to the settings?

**Comment by PeterSurda** [comment]
Minimize into tray bar is not a good solution?

**Comment by ungenannter** [comment]
Well, you need to click on the TrayIcon to minimize the Window. Bitmessage does not minimize using a keyboard shortcut for closing the window. I always close my windows with a shortcut. Would be a great feature.

**Comment by koyuawsmbrtn** [comment]
This bugged me too. Every time I closed the window, I expected that it was minimized, but the whole program exited.

**Comment by PeterSurda** [comment]
Forgot to close. @koyuawsmbrtn just use https://github.com/mailchuck/PyBitmessage if you don't want to wait until 0.6.
