### ISSUE TITLE
Is there any way to know how many (active) peers are there in the network?

### ISSUE THREAD

**Issue by Abdullah114** [Bitmessage/PyBitmessage#814]

**Comment by PeterSurda** [comment]
A node keeps a list of nodes that it

- received from bootstrapping
- received from other nodes

It tries to keep up to 1000 of those that have been online in the last 48 hours, and up to 2000 total (this description is not fully accurate but a good approximation). You can modify these limits to obtain information about the whole network. These limits are in
- receiveDataThread.recaddr (total limit)
- outgoingSynSender.run (last 48 hours)

The aforementioned recaddr prints the number of addresses it keeps in memory:

    print 'knownNodes currently has', len(shared.knownNodes[self.streamNumber]), 'nodes for this stream.'

so you just need to run it in foreground or capture the output.
