### ISSUE TITLE
Development Team Mailing List?

### ISSUE THREAD

**Issue by mendaxi** [Bitmessage/PyBitmessage#830]
Is there an *Email Address* the we can have designated as a mailing list for the dev team? I'm working on packaging and I don't necessarily want to list myself.

**Comment by PeterSurda** [comment]
how about a channel instead?

**Comment by mendaxi** [comment]
I was thinking more of an email address that people could send bug reports and the likes to.
I'm tweaking with things in the packaging files, and I suppose it would be a good idea to have one to list as the "maintainer".

And I do believe there is a DevTalk mailing list, but it's long dead.

**Comment by PeterSurda** [comment]
Actually I just committed a change which adds a "Contact support" menu item that sends a report to me. Over longer term, it's supposed to put it into my ticketing system but I would need to add some functions into the mailchuck gateway and that's not a high priority.

**Comment by mendaxi** [comment]
ah

**Comment by PeterSurda** [comment]
ok so i'm closing this. I'll see how well the new system works.

**Comment by bartmika** [comment]
Question: Do we have an official BitMessage development channel? I am looking at https://bitmessage.org/forum/index.php/topic,1689.0.html and I see **DevTalk** at **BM-2D9QKN4teYRvoq2fyzpiftPh9WP9qggtzh**. Can you confirm @PeterSurda?

**Comment by PeterSurda** [comment]
@bartmika Based on the description, it is supposed to be run by @grant-olson . However, the address appears to be offline. Maybe a chan would be better, how about this one:
    bitmessage BM-2cWy7cvHoq3f1rYMerRJp8PT653jjSuEdY
