### ISSUE TITLE
Add shortcut navigation

### ISSUE THREAD

**Issue by Jzarecta** [Bitmessage/PyBitmessage#849]
Would be nice to have keyboard navigation, I always used it for gmail. Using the VIM-friendly navigation keys doesnt sound like a bad idea:
- j left
- k right
- u up
- l down
- n next message
- p previous message
- r reply
- f forward

On Qt, this tutorial might help, using Qsequence:
http://doc.qt.io/qt-5/qshortcut.html

Regards.

**Comment by PeterSurda** [comment]
See mailchuck@54b5c9c862f735eab18487aa776fadb8469d823e. It will be merged soon, or you can try out the fork directly now if you prefer.

**Comment by krikmo** [comment]
@PeterSurda your link is broken. If anyone finds this issue, go [here](https://github.com/mailchuck/PyBitmessage/commit/54b5c9c862f735eab18487aa776fadb8469d823e).

**Comment by PeterSurda** [comment]
Fixed link.
