### ISSUE TITLE
Is BitMessage Dead?

### ISSUE THREAD

**Issue by espress0** [Bitmessage/PyBitmessage#850]
Current version (Beta)

0.4.4
October 17, 2014

**Comment by Atheros1** [comment]
It is not dead. When bugs are fixed in a different branch then it will be pulled into this upstream branch and binary files will be repackaged.

**Comment by PeterSurda** [comment]
I expect the merging and 0.6 to happen in the next couple of weeks. There isn't much left to do. In the meantime, you can try out https://github.com/mailchuck/PyBitmessage/releases if you like.
