### ISSUE TITLE
kde doesn't start bitmessage on startup

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#857]
I compare it to qTox. They were running side by side, but after reboot qTox is restarted and bitmessage isn't. I think it probably depends on the .desktop file.

bitmessage has this .desktop file:

```
[Desktop Entry]
Type=Application
Name=PyBitmessage
GenericName=PyBitmessage
Comment=Send encrypted messages
Exec=pybitmessage %F
Icon=pybitmessage
Terminal=false
Categories=Office;Email;
```

qTox has this .desktop file:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=qTox
GenericName=Tox client 
Comment=Qt 5 based Tox client
TryExec=qtox
Exec=qtox %u
Icon=qtox
Categories=InstantMessaging;AudioVideo;Network;
Terminal=false
MimeType=x-scheme-handler/tox;application/x-tox;
```

I suspect the problem is because TryExec line is missing. It is used to determine if the program is installed.

You also probably want to add InstantMessaging and Network to categories.

**Comment by PeterSurda** [comment]
Thanks for the report. I haven't tried it with KDE, I'll look at it. It's possible that it does not work correctly with GNOME either, I always run it manually. There is no way to configure this from inside Bitmessage at the moment anways, that is only supported on Windows for the time being.
