### ISSUE TITLE
v0.6.0 : some translations are mixed (inter languages)

### ISSUE THREAD

**Issue by koeur2pi** [Bitmessage/PyBitmessage#860]
From v0.6.0 : some translations are mixed (inter languages). For example French seems mixed with some Finish language.

Perhaps that this log may help :

Info: we could not tell whether your OS is limited to having very few half open connections because we couldn't interpret the platform version. Don't worry; we'll assume that it is not limited. This tends to occur on Raspberry Pis. : invalid version number '#37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015'
2016-05-12 12:33:59,466 - ERROR - Failed to set locale to fr_FR.ISO8859-1
Traceback (most recent call last):
  File "/home/me/PyBitMessage/src/bitmessageqt/__init__.py", line 111, in change_translation
    pythonlocale.setlocale(pythonlocale.LC_ALL, lang)
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale `setting`

**Comment by PeterSurda** [comment]
I noticed this too, it looks like there was an error during uploading of Norwegian translations into Transifex and it overwrote some French ones. I fixed it in the meantime, it just hasn't been merged into github. If you'd like you can help with the rest of the French translations: https://www.transifex.com/bitmessage-project/pybitmessage/language/fr/

**Comment by koeur2pi** [comment]
Issue fixed with v0.6.1 release.
