### ISSUE TITLE
[feature suggestion] Create chan and add chan should offer to retrieve already available messages in this chan

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#864]
Since BM keeps the database of messages, it is possible that there are already some messages for this chan (even in case of creation). So it is both possible and useful to have an option to retrieve preexisting messages for this chan.

**Comment by PeterSurda** [comment]
I think there's already an issue about this.

**Comment by g1itch** [comment]
This duplicates #632
