### ISSUE TITLE
Failed to set locale

### ISSUE THREAD

**Issue by vinctux** [Bitmessage/PyBitmessage#872]
Hi, while running the latest master branch, I encountered the following error:
```
ERROR - Failed to set locale to en_US.ISO8859-1
```

A quick lookup with `locale -a` showed that my system has many locales, but none matching the required one. Although a bit weird, as the line, causing the error, namely:
```python
pythonlocale.setlocale(pythonlocale.LC_ALL, lang)
```
is calling only `pythonlocale.LC_ALL` which eventually is turned into `en_US.ISO8859-1` by Python's `locale.py`. So is it a Python-and-my-system-related bug or somewhat else, like a PyQT issue?

**Comment by PeterSurda** [comment]
Hi,

this is a known bug (it does not try UTF-8 but defaults to the default locale encoding), I just haven't opened a ticket. You can work around it in the meantim by using locale-gen to generate the locale that's missing.

**Comment by vinctux** [comment]
@PeterSurda May I ask why we aren't trying to load UTF-8? I guess because of compatibility issues with specific chars? It would be far more universal if there UTF-8 (or maybe even UTF-16) would be used.

**Comment by PeterSurda** [comment]
I fixed a bug and that opened a new one. I'll fix this one too, don't worry.

**Comment by vinctux** [comment]
I'm not worrying, I'm here to help :smile:

**Comment by PeterSurda** [comment]
Please retry with the latest v0.6 branch and close if it's fixed. It will still complain but it will then try UTF-8 and that should succeed.

**Comment by vinctux** [comment]
It works now. At least it didn't throw any errors regarding locale.
