### ISSUE TITLE
Contains malware (according to 5 antivirus detectors)

### ISSUE THREAD

**Issue by rebroad** [Bitmessage/PyBitmessage#874]
https://bitmessage.org/download/windows/Bitmessage.exe file with sha256 of 09aa2dae8f62767fd00c50f9a6b432dce60f79c07e1d86012c3d092883a8318a is reported by virustotal.com to contain malware, e.g. Sality.

Report here: https://www.virustotal.com/en/file/09aa2dae8f62767fd00c50f9a6b432dce60f79c07e1d86012c3d092883a8318a/analysis/

**Comment by PeterSurda** [comment]
This is a false positive triggered by pyinstaller, see https://github.com/pyinstaller/pyinstaller/issues/599.
