### ISSUE TITLE
build-process request: usage of python-setuptools.

### ISSUE THREAD

**Issue by ghost** [Bitmessage/PyBitmessage#875]
As I messaged @PeterSurda some time ago and provided a starting point for a setup.py,
using python-setuptools would help/benefit most if not all package maintainers who currently work around your in-repo provided methods.

I don't want you to put PyBitmessage on pypi, but I'd rather like to make most maintainers work easier. It can use setuptools without being on pypi.
From the technical side this might be considered not much of a priority, but I addressed this before the 0.6 release and nothing happened so far.

This is a non-trivial fix, but it would help the distribution of PyBitmessage and make maintainers happy with less lines of code to work around issues.
I have had an almost working setup.py, but I do not like to commit half finished work.
If Peter does not include it, I can search for it again, upload it to a public place and someone else with more insight on python-setuptools and PyBitmessage can fix it up.

**Comment by ng-0** [comment]
This would close #883 if it is applied.

**Comment by ng-0** [comment]
I will assign this to myself and create a functional setup.py which you can extend.

**Comment by PeterSurda** [comment]
There is now a setup.py.
