### ISSUE TITLE
Please don't install bitmsghash/Makefile and bitmsghash/bitmsghash.cpp

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#883]
These should only be used in build, and should not be not installed.

**Comment by bmng-dev** [comment]
Can you provide more information? Are you referring to the pybitmessage-git package on the Arch User Repository?

**Comment by yurivict** [comment]
'make install' installs those files on FreeBSD.

**Comment by PeterSurda** [comment]
You can now use setup.py on FreeBSD too (I tested it) and it leaves it up to setuptools to build and install it.

**Comment by yurivict** [comment]
Thanks!
