### ISSUE TITLE
"All accounts" shows that chan has new messages, but in the chan itself nothing is shown as new

### ISSUE THREAD

**Issue by yurivict** [Bitmessage/PyBitmessage#884]
Icon counter also shows new messages.

This is the the current rev. 8e066ea

**Comment by keithieopia** [comment]
Can confirm this happens, even when every message has been read and trashed and there's no messages shown in the inbox.

**Comment by yurivict** [comment]
The opposite also happens: the chan shows it has new messages but "All accounts" and icon indicator doesn't. Overall this problem became worse in 8e066ea compared to 0.6.0.

**Comment by PeterSurda** [comment]
Ok I'll look at it.

**Comment by g1itch** [comment]
@yurivict, @keithieopia, can you please check the latest v0.6? I hope #1117 fixed it.

**Comment by yurivict** [comment]
Sorry, I can't check now due to ETOOBUSY.

**Comment by keithieopia** [comment]
@g1itch I just did a fresh `git clone` to get 4a3f8f4 / your #1117 pull request. Thank you for taking time time to address this issue despite it's age.

IIRC, this issue on my end seemed to be intermittent but would happen at least once in 24 hours. At the time, I wasn't running 8e066ea so it wasn't as frequent as *yurivict* reported.

Let's give my new instance a max of 2 days running. I'm confident the issue would show up again in that time if it hasn't been successfully fixed. That said, your commit seems like pretty solid work. I see no reason why it wouldn't be fixed.

Please @ me here if I don't report back, so GitHub sends me a nag email.

**Comment by keithieopia** [comment]
I've had the client running for many hours and have gone through several rounds of new and deleted messages. It seems that the issue has been fixed thanks to thanks to @g1itch's work. 

@PeterSurda, I feel this issue can be safely closed if @yurivict is still too busy to check.
