### ISSUE TITLE
Rename image files

### ISSUE THREAD

**Issue by ghost** [Bitmessage/PyBitmessage#885]
I'd like someone to rename these not very unique files:

desktop/can-icon.svg
desktop/icon14.xpm
desktop/icon24.png

I propose to prepend or append "pybitmessage"
with a leading or trailing hyphen to the filenames.

Related, you might want to fix the can-\* names in src/images/ in a similar way.

This is based on what I personally do with your software and what other package maintainers do.
Renaming the files on your side will decrease our lines of code a bit.

This is very trivial, which is why I ask first and not just sent in a patch.

**Comment by g1itch** [comment]
Setup script does it starting from de53194.
