### ISSUE TITLE
fix shebangs

### ISSUE THREAD

**Issue by ng-0** [Bitmessage/PyBitmessage#887]
If possible, could you fix the python shebangs in "src/bitmessagemain.py" and
"src/bitmessagecli.py"?
Our shebang fixer did not stumble on more, but if you had more like those two they could get fixed too.
`#!/usr/bin/env python2.7.x' `#!/usr/bin/env python2.7' should get fixed in my opinion.

If you regard it as not necessary, could you please explain why.

**Comment by PeterSurda** [comment]
Merged your pull request in 60c447f56baee1d8be50d943da361c8b925c6d00
