### ISSUE TITLE
Signed Releases?

### ISSUE THREAD

**Issue by reelsense** [Bitmessage/PyBitmessage#889]
How are we suppose to verify the integrity of the file download or it's authenticity? I don't seem to be able to find the sigs for any version of this software.

The Mumble project is a [good example](https://github.com/mumble-voip/mumble/releases).

**Comment by PeterSurda** [comment]
Atheros had some technical issues for the 0.6.1 release and that's why there are no sigs. I now have access to this repo and 0.6.1 will have my sigs, just like I did when I was working on my own repo: https://github.com/mailchuck/PyBitmessage/releases
