### ISSUE TITLE
Bitmessage gets some errors on starting

### ISSUE THREAD

**Issue by Zwoerni2000** [Bitmessage/PyBitmessage#896]
Today in the morning PyBitmessage worked well. But now I get some errors:

`Traceback (most recent call last):
File "../PyBitmessage/src/bitmessagemain.py", line 17, in <module>
import singletonFile 
"/home/system/PyBitmessage/src/singleton.py", line 8, in <module>
import sharedFile 
"/home/system/PyBitmessage/src/shared.py", line 982, in <module>
from debug import loggerFile "/home/system/PyBitmessage/src/debug.py", line 26, in <module>
helper_startup.loadConfig()
File "/home/system/PyBitmessage/src/helper_startup.py", line 48, in loadConfigshared.config.read(shared.appdata + 'keys.dat')
File "/usr/lib/python2.7/ConfigParser.py", line 305, in readself._read(fp, filename)
File "/usr/lib/python2.7/ConfigParser.py", line 512, in _readraise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.file: /home/system/.config/PyBitmessage/keys.dat, line: 1`

Using PyBitmessage with Linux OS

**Comment by bmng-dev** [comment]
>ConfigParser.MissingSectionHeaderError: File contains no section headers.

Your keys.dat is empty or otherwise malformed. Did you make any changes to it since PyBitmessage last worked?

**Comment by Zwoerni2000** [comment]
No I didn't

**Comment by Zwoerni2000** [comment]
That's the problem

**Comment by PeterSurda** [comment]
There should be a backup file if something goes wrong with keys.dat. It looks like "keys.dat.20160830123456". Backup the broken file and copy the old backup as keys.dat, let's see if that helps.

**Comment by Zwoerni2000** [comment]
Where should this file be?

**Comment by Zwoerni2000** [comment]
Just installed everything new and there are problems with python: http://hastebin.com/fusuraradi.rb / http://pastebin.com/u3ZHbE0m

**Comment by PeterSurda** [comment]
The new messages are informative, even though it says ERROR and prints a stack trace. You can try the "v0.6" branch if you want the default logs to be less chatty.

The backup file should be alongside the normal keys.dat, which on Linux is `~/.config/PyBitmessage/`, or if you have the environment variable `XGD_CONFIG_HOME` set, under `$XDG_CONFIG_HOME/PyBitmessage`.

**Comment by bmng-dev** [comment]
Perhaps informative ERRORs should have a reduced severity?

Personally though, I don't like the idea of informative errors - they are generally an indication of poor code or an incomplete function/class/module/feature and should be resolved. For example checking the existence of namecoin.conf before attempting to open it would eliminate the `IOError: [Errno 2] No such file or directory: '/home/system/.namecoin/namecoin.conf`. Not everything will be that simple of course but it demonstrates the point.

**Comment by PeterSurda** [comment]
I already reduced severity in recent commits, but thank you for the suggestion, I can add that too.

**Comment by PeterSurda** [comment]
@bmng-dev Is that better?

**Comment by bmng-dev** [comment]
@PeterSurda, you don't need my approval you know. You are in control and can do whatever you want. I'm just providing hopefully constructive criticism. Anyway it's a start and as long as it doesn't stop there I'm fine with it.

**Comment by PeterSurda** [comment]
Ok I reworked this and got no more complaints so I'm closing this.
