### ISSUE TITLE
Addresses not showing up on "Send" tab, only Identicons

### ISSUE THREAD

**Issue by anonimou0** [Bitmessage/PyBitmessage#898]
As you can see by the image, the addresses are not showing up on Send tab.
It was, but suddenly they are not. I've tried to delete all the folders of PyBitmessage (/home/user/.config/PyBitmessage and the downloaded PyBitmessage folder). Both without luck! Is there anything I could try?
Linux 4.4.0-34-generic Mint 18 xfce 
![screenshot_2016-09-22_22-44-35](https://cloud.githubusercontent.com/assets/14253996/18771560/4cfdab1c-8116-11e6-9557-43d8dd3bb067.png)

**Comment by PeterSurda** [comment]
Which exact version are you using and if it's from git, which branch? Does that also happen if you switch to English?

**Comment by anonimou0** [comment]
Version 0.6.1, from github. i'm guessing the main branch? (git clone https://github.com/Bitmessage/PyBitmessage $HOME/PyBitmessage)
I've tried to switching to U.S. English and restarting the software. No luck..
When I start using PyBitmessage, it was showing up. I have a small glitch of memory that this started happening when I changed the language, but not sure. I use system interface in U.S. English, but locales are setted to PT-BR. Now, PyBitmessage is setted to U.S. english, didn't work

**Comment by PeterSurda** [comment]
Just in case, try switching to the latest code ("git checkout v0.6") and retry. Also try to build the C PoW ("make" in src/bitmsghash), there were some bugs in the python PoW in 0.6.

**Comment by bmng-dev** [comment]
I can reproduce. It is nothing to do with the language. The issue is the addresses have no label. There are two possible solutions:
- Users should name their addresses (double click the address in the Identities tab and enter a label)
- The dropdown should either fallback to displaying the address if the label is empty (or contains only whitespace/non-visible characters) or display the address in brackets after the label (like in the Identities tab)

**Comment by PeterSurda** [comment]
@bmng-dev I see, I'll add the address to the drop down menu then. @anonimou0 , try labeling your addresses (by double clicking or pressing F2). I should have Mint installation finished in a couple of minutes just in case it's something else.

**Comment by PeterSurda** [comment]
Yep, looks like @bmng-dev is correct as usual. There is nothing unusual about PyBitmessage on Mint, but when a label is missing, it results in the described behaviour.

**Comment by anonimou0** [comment]
Hello, good morning. 
I'm not with my PC right now. However, it might be that. Will try later.

As a suggestion, if it works, when there is no label on the address, it could show the BM-address, instead of void. I'll try later.

Thanks, anyway, for the great job you guys are doing.

**Comment by anonimou0** [comment]
As stated by @bmng-dev and confirmed by @PeterSurda, it was not really a bug. When a label is inserted, it shows up there. Not sure why I thought that there was the address there. Sorry by the inconvenience.
As a suggestion, as stated before, if no label is inserted, the address could show up there. What you think?
Thanks!!!
