### ISSUE TITLE
A received message hangs bitmessage-qt, possibly an insecurity?

### ISSUE THREAD

**Issue by kirkawolff** [Bitmessage/PyBitmessage#900]
I received the attached message, and whenever I would attempt to select it from the qt interface, the program would hang and consume 100% CPU.  The only way I could recover is to kill the program, then run bitmessagemain.py with the -c option, and delete the message.  It appears the contents of the program are a DOS program.  Nevertheless, this could be an inseurity in bitmessage and should be looked at. I can assist in a debug session if necessary.
[Re: rapidgator premium available at a discount.txt](https://github.com/Bitmessage/PyBitmessage/files/542261/Re.rapidgator.premium.available.at.a.discount.txt)

**Comment by kirkawolff** [comment]
There is a message floating around general2 noting this problem:

> Subject: Re: to new BM users: if your pyBM keeps freezing up ... remove the .EXE file
>
> 99% of bitmessage users won't know how to do this.
> 
> ------------------------------------------------------
> 
> sadly, some dumbass posted an EXE-file on BM recently, which screws up many clients (Linux etc.).
> 
> you have to open the message.dat file with the SQLiteBrowser , go to inbox table,
> 
> and remove  (open and CLEAR) the   .MZ.....  bullshit content.
> 
> also compact the whole database with SQLite.
> 
> else BM will freeze while navigating through the messages.
> 
>  In 27 days this poisoned BM will be dropped. (so if you can still read this BM on beamstat, you're not safe yet...)

**Comment by PeterSurda** [comment]
Thank you for the report, as you noticed yourself, this already has been reported, also what it triggers and a possible workaround. I'm working at a proper fix right now.

**Comment by PeterSurda** [comment]
Can you test with 448ceaa74ca6929f626fa36962c4f3c0ca0f0659 (or later) if it still happens?

**Comment by kirkawolff** [comment]
it has no apparent effect.  problem still present.

**Comment by PeterSurda** [comment]
It looks like there were two separate issues, one with the renderer on windows, and one with the regexp parser. The first commit fixes the first one, the second one the second one. I can't reproduce the problem anymore, can you retry?

**Comment by kirkawolff** [comment]
It only locks up for one second now.  I am able to delete the message from the UI now.

**Comment by PeterSurda** [comment]
Works for me now both on linux and windows, I'm closing the ticket.
