### ISSUE TITLE
interface lag/hang when sending messages

### ISSUE THREAD

**Issue by ProZiro** [Bitmessage/PyBitmessage#920]
OS: Arch Linux
BM Version: 0.6.1

Experiencing a lag/hang of the interface upon sending a message. There does not apear to be any error associated with this, thus I have none to supply.

The only errors being seen are connection timeouts against various IPs and this one: ERROR - sock.sendall error: [Errno 9] Bad file descriptor

Though the later does not seem to be showing up since first start and no connectivity issues are being experienced.

So, the issue seems to be issolated to the interface.

**Comment by PeterSurda** [comment]
Hello, this is a known issue. Please switch to the v0.6 branch and/or build the C PoW module ("make -C src/bitmsghash"), preferably do both.

Also, there are an packages for Arch: https://aur.archlinux.org/packages/?O=0&SeB=nd&K=pybitmessage&outdated=&SB=p&SO=a&PP=50&do_Search=Go, I recommend the ones by dmp1ce.

**Comment by ProZiro** [comment]
That is actually the very package that is installed and am using.

**Comment by PeterSurda** [comment]
It looks like you're using the one by klexx. Use the one by dmp1ce (either 0.6.1 or the -dev, depending on your preference).

**Comment by ProZiro** [comment]
Awe, yes, you are right... and that extra package seems to help. Thanks
