### ISSUE TITLE
Website down (SSL error)

### ISSUE THREAD

**Issue by PaulBags** [Bitmessage/PyBitmessage#921]
Probably the wrong way to bring this up but http://bitmessage.org/ redirects to https://bitmessage.org/ which fails unresolvably because, as firefox puts it, "OCSP response has an invalid signature. Error code: SEC_ERROR_OCSP_BAD_SIGNATURE".

I can't add an exception to get past it because the browser's not even getting the cert.

**Comment by PeterSurda** [comment]
See: https://beamstat.com/chan/general/71659f2cff1b36e9be0b96aa61ff70ddea3bc5714570047997b6edd9302778f0

**Comment by PaulBags** [comment]
See what exactly? A list of unrelated threads that go no-where?

**Comment by PeterSurda** [comment]
"What is happening is that StartCom, the CA issuing the certificate for bitmessage.org, has a broken OCSP (online revocation verification) service that returns garbage. If your browser's OCSP check of bitmessage.org cache expired or if you never visitied bitmessage.org, you'll receive this message."

**Comment by clement-analogue** [comment]
Using Firefox, my websites are not accessible anymore. It seems it is related to this bug. Before, I had this error randomly. Refreshing the page eventually worked, but today it is not working at all:
https://www.forumanalogue.fr/
Any chance it will be fixed soon? :)

**Comment by Wikinaut** [comment]
Switch to Let's Encrypt!

StartCom will (or is already) be deprecated in Firefox, see https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

**Comment by Atheros1** [comment]
Switched to Let's Encrypt successfully.
