### ISSUE TITLE
https://bitmessage.org : OCSP response invalid signature. Error code: SEC_ERROR_OCSP_BAD_SIGNATURE

### ISSUE THREAD

**Issue by Wikinaut** [Bitmessage/PyBitmessage#923]
https://bitmessage.org  error during connection !!

**Comment by Wikinaut** [comment]
pls. fix your site

**Comment by Atheros1** [comment]
I am able to reproduce. StartCom says that the error will hopefully be resolved in several hours. I am still checking if there is anything I can do on my end.

**Comment by Atheros1** [comment]
This issue is related to #921

**Comment by Wikinaut** [comment]
Switch to Let's Encrypt!

StartCom will (or is already) be deprecated in Firefox, see https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

**Comment by Atheros1** [comment]
Switched to Let's Encrypt successfully.
