### ISSUE TITLE
ERROR - SOCKS5 error. (5, 'Connection refused')

### ISSUE THREAD

**Issue by 2SI3NX** [Bitmessage/PyBitmessage#935]
Using Tor as daemon in Ubuntu xenial, ive configured Bitmessage to 127.0.0.1 and 9050,
Bitmessage eventually connects, but when i output Bitmessage to a log file i see many errors of this:

ERROR - SOCKS5 error. (5, 'Connection refused')

Any idea why? and is this a bug or anything to worry about ?

**Comment by PeterSurda** [comment]
This is normal. Most of the addresses in the host list are unreachable and this is the expected error message.
