### ISSUE TITLE
UTF characters in path for portable mode on WinXP cause problems

### ISSUE THREAD

**Issue by BitWaspBitWasp** [Bitmessage/PyBitmessage#978]
I started the programm(Windows XP) but after 3 days still NOT CONNECTED.
How to fix the problem ?

**Comment by PeterSurda** [comment]
Which version of bitmessage are you using? Aren't you getting a notice that:

- your proxy settings are wrong?
- your time is wrong?

**Comment by BitWaspBitWasp** [comment]
Bitmessage_x86_0.6.2.exe
no
no

**Comment by PeterSurda** [comment]
Freshly installed XP Home SP2, without any updates, downloaded firefox, then bitmessage and it connected right away. I think that there's something wrong with your network settings (or time). Or maybe you are using a VPN, or you have too many other nodes on your LAN already connected to the network. Your maybe you forgot to allow connections in the firewall, or your computer is infected.

**Comment by BitWaspBitWasp** [comment]
I don't use any firewall, network etc. - all settings are Ok

**Comment by PeterSurda** [comment]
Try deleting knownnodes.dat, maybe that will help.

**Comment by BitWaspBitWasp** [comment]
I found out the problem.
If I change settings and try to work in Portable Mode - I have the problem
but for me it is very important to work exactly in Portable Mode.

**Comment by PeterSurda** [comment]
I'll look at it.

**Comment by PeterSurda** [comment]
Well I tried it in portable mode, and it works too. Try deleting knownnodes.dat, that may speed up the initial connection.

**Comment by BitWaspBitWasp** [comment]
I have found in what this problem consisted
When I tried to use Portable mode the path to my files was:
C:\Documents and Settings\Admin\Рабочий стол\bm

Decision: the path shouldn't contain the RUSSIAN letters

**Comment by PeterSurda** [comment]
Thank you for the report, this means it's a bug and I should fix it.

**Comment by PeterSurda** [comment]
Please don't close, I need to review and fix this.

**Comment by BitWaspBitWasp** [comment]
Sorry

**Comment by g1itch** [comment]
Duplicate #165
