### ISSUE TITLE
new release v0.6.2

### ISSUE THREAD

**Issue by HuguesDohmen** [Bitmessage/PyBitmessage#980]
Closing the aplication is not possible. I have to shut down the aplication via task manager.
"CTRL+Q" doesn't work. The red cross in the upper right corner doesn't work.

Seems to be a little bug?
Can this be fixed?

Regards,

Hugues

**Comment by PeterSurda** [comment]
It should ask you for confirmation, but it's true that it often takes very long (several minutes).

**Comment by g1itch** [comment]
This issue looks outdated.

**Comment by dimyme** [comment]
0.6.2 works OK here on Fedora 31

**Comment by PeterSurda** [comment]
@HuguesDohmen Probably related to shutdown procedure. It has been improved and while there still are some minor issues, it mostly works now.

@dimyme 0.6.2 contains a vulnerability, don't use it.
