### ISSUE TITLE
Generated python modules vs loading the ui-files

### ISSUE THREAD

**Issue by g1itch** [Bitmessage/PyBitmessage#982]
Hello!

I noticed that most of the widget modules is generated from ui-files via pyuic but in the recently updated modules like `networkstatus` the function `widgets.load()` used which loads ui-file. Have you already decided which is the proper approach for you project?

**Comment by PeterSurda** [comment]
Good question. As you noticed, it's mixed at the moment. I would like to move everything into the `widgets.load()` method, but not all ui files fully match the corresponding .py files, so an audit would have to be done simultaneously.

**Comment by g1itch** [comment]
It's clear. So I do.
