### ISSUE TITLE
Please, commit your changes or stash them before you can merge. Aborting ?? help on updating!

### ISSUE THREAD

**Issue by 2SI3NX** [Bitmessage/PyBitmessage#983]
After a few months of not updating Bitmessage, i do a git pull on Ubuntu in PyBitmessage
 dir, and shows this error in terminal:
"Please, commit your changes or stash them before you can merge. Aborting"

Please help on forcing git pull for easy update after long time?

Also another question,
I ended up doing:
```
git clone https://github.com/Bitmessage/PyBitmessage "/home/$USER/PyBitmessage/"
rsync -h --progress --stats -r -t --modify-window=1 -l -D --update "/home/$USER/PyBitmessage/" "$BitmessageDir"
```

Would this be considered an alternative and safe way while keeping settings intact?

**Comment by WhiteCat6142** [comment]
```
git stash
git pulls 
git stash apply
```

**Comment by PeterSurda** [comment]
Maybe you're running in portable mode? It's possible to do that on linux but it makes much less sense than on windows/osx, and a better way is to simply `export XDG_CONFIG_HOME=/wherever/you/want/your/config` before running PyBitmessage if you want to save the config in a non-standard directory.

**Comment by 2SI3NX** [comment]
@PeterSurda Yes i am running in portable mode. Although git stash doesnt work for me, as i dont want to register the changes on github. such as: 
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"


**All i want to do is pull changes and update it in portable mode in a simple manner.**
What is the best way to update in portable mode if git pull wont work?
Will my commands i posted above be considered correct (because it did work) or is there an easier way?

**Comment by PeterSurda** [comment]
Ok, so
- your name / email will only get out if you push the changes to a remote repository, or someone pulls from your local repository
- I recommend using the XGD_CONFIG_HOME variable and putting the config in a different directory than the source.

**Comment by 2SI3NX** [comment]
@PeterSurda thanks can you tell me where/how exactly do i set the XGD_CONFIG_HOME variable for bitmessage only?  I dont want to redirect all other ubuntu apps in the same XGD_CONFIG_HOME. So i dont want to change the global XGD_CONFIG_HOME variable if you know what i mean. 

So is XGD_CONFIG_HOME specific for Bitmessage? where can i change that..

**Comment by PeterSurda** [comment]
Why do you even want to use portable mode? Is your /home/$USER/PyBitmessage on a different filesystem than /home/$USER/.config? If no, then portable mode makes very little sense.

**Comment by PeterSurda** [comment]
Oh wait, I noticed the $Bitmessagedir

You can just

`XGD_CONFIG_HOME=/mnt/encrypted/bmconfig python2.7 /mnt/encrypted/bmsource/src/bitmessagemain.py`

(all in one line)

**Comment by WhiteCat6142** [comment]
ADD configdir to gitignore as default

**Comment by 2SI3NX** [comment]
@PeterSurda & @WhiteCat6142  In the USB theres the portable folder "PyBitmessage"   I dont know where the config dir is, i have been trying to find it.  I know that the keys.dat, messages.dat, etc is under src but where is the config dir?? and where exactly do i set XDG_CONFIG_HOME ?  please help make this a bit clearer.  appreciate it

**Comment by PeterSurda** [comment]
In portable mode, the config is in the same directory as the binary (if running in frozen mode) or the source (if running from the source). You can set XDG_CONFIG_HOME to whatever you want, but that's for non-portable mode. So you should probably create a new directory on your USB, say config, set XDG_CONFIG_HOME to it, run bitmessage, turn off portable mode. Or you could just symlink `~/.config/PyBitmessage`.

I'm not sure what you're trying to achieve, but why are you using a USB stick in the first place, and why do you want to have both the source and the config on it? Maybe you're overcomplicating it.

**Comment by 2SI3NX** [comment]
The only thing i want to do, is run portable mode on a USB so that i can use it on other ubuntu pc's too **which i have been doing** till the update git pull was giving errors and wanted me to stash first.  i want to be able to update it easily in portable mode without stashing.
So thinking that i can move the config dir somewhere else on another folder on a USB would simplify the update process. if this is not true and im misunderstanding then inform me please? thanks.

on a sidenote, this:
/home/user/.config/PyBitmessage/pybitmessageqt.conf  is under .config which i dont know why because all configs are under /src like you said.

**Comment by PeterSurda** [comment]
Well, you could try to find out which files are conflicting with the pull as @WhiteCat6142 suggested, or use two directories as I suggested earlier.

The pybitmessageqt.conf is handled separately, by PyQT, that's why it's not always in the same directory as the rest of the config, but I plan on fixing that some time in the future.

**Comment by WhiteCat6142** [comment]
confilict src/debug.log
not message.dat because that was already ignored.

**Comment by PeterSurda** [comment]
Well you can just delete debug.log unless you need it for something.

**Comment by 2SI3NX** [comment]
The files which were conflicting was a whole lot of them, so its difficult to ignore each one.

What im doing is cloning PyBitmessage and then merging the folder with my current folder and everything seems good, just like my commands in my first comment.

**Comment by PeterSurda** [comment]
> ... merging the folder with my current folder ...

There's your problem. You shouldn't be merging unless you want to run different code. You're not only causing pull conflicts but may end up with broken code. You should just be pulling the changes.

**Comment by 2SI3NX** [comment]
Ok please try and understand.  Im not a professional in programming and am still kinda new to bitmessage.

I asked a few times where exactly you set XDG_CONFIG_HOME and its still not clear.

i ran the command: XDG_CONFIG_HOME=/my/usb/bmconfig python2.7 /my/usb/bmsource/src/bitmessagemain.py
It started up bitmessage and i saw in the config folder: folder ibus and file: Trolltech.conf
Are these even config files?

Was this command supposed to run only once so that the config files are placed in the separate config folder? ie. when i shutdown BM and open it again, do i have to run it with the above command again??

Other than that, i dont understand why i should move the config to a separate folder if my main problem is updating bitmessage from 0.6.1 to 0.6.2 using git pull.

these are the files it was conflicting with when i do git pull:

```
Updating 2616a9d..b304872
error: Your local changes to the following files would be overwritten by merge:
	.gitignore
	Makefile
	archpackage/PKGBUILD
	compiletest.py
	debian/changelog
	debian/compat
	debian/control
	debian/copyright
	debian/docs
	debian/manpages
	debian/pybm
	debian/source/format
	debian/source/include-binaries
	desktop/pybitmessage.desktop
	puppypackage/icon14.xpm
	puppypackage/pybitmessage-0.3.5.pet.specs
	pyinstaller/bitmessagemain.spec
	rpmpackage/pybitmessage.spec
	slackpackage/slack-desc
	src/addresses.py
	src/api.py
	src/bitmessagecli.py
	src/bitmessagecurses/__init__.py
	src/bitmessageqt/__init__.py
	src/bitmessageqt/about.py
	src/bitmessageqt/account.py
	src/bitmessageqt/bitmessageui.py
	src/bitmessageqt/blacklist.py
	src/bitmessageqt/foldertree.py
	src/bitmessageqt/languagebox.py
	src/bitmessageqt/messageview.py
	src/bitmessageqt/networkstatus.py
	src/bitmessageqt/newaddresswizard.py
	src/bitmessageqt/newchandialog.py
	src/bitmessageqt/newchandialog.ui
	src/bitmessageqt/safehtmlparser.py
	src/bitmessageqt/settings.py
	src/bitmessageqt/settings.ui
	src/bitmessageqt/support.py
	src/bitmessageqt/uisignaler.py
	src/bitmessageqt/utils.py
	src/bitmessageqt/widgets.py
	src/bitmsghash/Makefile
	src/bitmsghash/bitmsghash.cpp
	src/class_addressGenerator.py
	src/class_objectHashHolder.py
	src/class_objectProcessor.py
	src/class_objectProcessorQueue.py
	src/class_outgoingSynSender.py
	src/class_receiveDataThread.py
	src/class_sendDataThread.py
	src/class_singleCleaner.py
	src/class_singleListener.py
	src/class_singleWorker.py
	src/class_smtpDeliver.py
	src/class_smtpServer.py
	src/class_sqlThread.py
	src/debug.py
	src/defaultKnownNodes.py
	src/helper_bootstrap.py
	src/helper_generic.py
	src/helper_inbox.py
	src/helper_msgcoding.py
	src/helper_startup.py
	src/highlevelcrypto.py
	src/l10n.py
	src/message_data_reader.py
	src/namecoin.py
	src/openclpow.py
	src/proofofwork.py
	src/protocol.py
	src/pyelliptic/cipher.py
	src/pyelliptic/ecc.py
	src/pyelliptic/openssl.py
	src/shared.py
	src/singleton.py
	src/socks/__init__.py
	src/tr.py
	src/translations/bitmessage.pro
	src/translations/bitmessage_de.qm
	src/translations/bitmessage_de.ts
	src/translations/bitmessage_en.ts
	src/translations/bitmessage_eo.qm
	src/translations/bitmessage_eo.ts
	src/translations/bitmessage_fr.qm
	src/translations/bitmessage_fr.ts
	src/translations/bitmessage_ja.qm
	src/translations/bitmessage_ja.ts
	src/translations/bitmessage_pl.qm
	src/translations/bitmessage_pl.ts
	src/translations/bitmessage_ru.qm
	src/translations/bitmessage_ru.ts
	src/translations/bitmessage_sk.qm
	src/translations/bitmessage_sk.ts
	src/translations/bitmessage_zh_cn.qm
	src/translations/bitmessage_zh_cn.ts
	src/upnp.py
	upstart/bitmessage.conf
Please, commit your changes or stash them before you can merge.
```

Forgive me if this seems dumb, but im not sure why the mission was to move the config folder, it doesnt seem like the above files are config files. as far as i know, only the .dat files are configs of BM.

The only thing i tried now which seemed to work was: **git reset --hard FETCH_HEAD**
and then git pull and then it seemed like it updated the files very quickly, i started BM and i saw that my settings were there and version went to 0.6.2.  **Is this the correct way to do a git pull in portable mode or is there a SIMPLER method?**

Also forgive me if i didnt see, but i have been looking all over the BM wiki to try and find documentation which describes what to actually do step by step if GIT PULL does not work and there is nothing.

git stash does not work for me and prefer not to use it.

**please confirm if the above git reset command does the job of updating BM portable mode correctly without losing any settings or without breaking the code?**

**Comment by 2SI3NX** [comment]
Also, i wont mind if i lose any changes since i didnt make any changes to any code, the only changes i dont want to lose are my settings/configs.

**Comment by PeterSurda** [comment]
> Ok please try and understand. Im not a professional and am still kinda new to BM.

So please pay attention when I'm telling you not to use `git merge`. That's the reason for your problems.

> I only run in portable mode so i dont need to change this right XDG_CONFIG_HOME?

Setting XDG_CONFIG_HOME is an alternative to portable mode, when for some reason you can't have config in the same directory as the source. But it turns out that that's not the problem you're having.

> My main concern is updating bitmessage Portable from 0.6.1 to 0.6.2 using git pull.

There shouldn't be any problem doing a `git pull`...

> these are the files it was conflicting with when i do git pull:

... unless of course you did a `git merge` in the past. Please don't do that if you don't understand what it does.

> Also forgive me if i didnt see, but i have been looking all over the BM wiki to try and find documentation which describes what to actually do step by step if GIT PULL does not work and there is nothing.

Because this is not a BM issue but a git issue.

> `git reset --hard FETCH_HEAD`

`git reset --hard` without `FETCH_HEAD` would do just fine.

> Also, i wont mind if i lose any changes since i didnt make any changes to any code, the only changes i dont want to lose are my settings/configs.

If you're not doing any changes to the code, please don't use `git merge`. If you don't understand what `git merge` does, please don't use it either.

**Comment by 2SI3NX** [comment]
Thanks for your response.
Just to make things clear, i think you might have misread, i never said i used 'git merge' at all and i never used 'git merge' ever before either.

I said i merged the folders meaning, like i said in a few previous posts i did a clone of Pybitmessage to homedir. and then i copied it over to my existing pybitmessage (which included my settings) and i merged the two folders, meaning i ran this command: 

```
rsync -h --progress --stats -r -t --modify-window=1 -l -D --update "/home/$USER/PyBitmessage/" "$BitmessageDir"
```
which means its a straight copy and merge to replace old BM files with existing pybitmessage portable folder and it worked for me and updated BM to 0.6.2


>     My main concern is updating bitmessage Portable from 0.6.1 to 0.6.2 using git pull.
> 
> There shouldn't be any problem doing a git pull...

Not sure why it happened to me, but doing a 'git pull' gives those conflicting files.

However using `git reset --hard FETCH_HEAD`  also worked for me perfectly, so i think this would be the easiest solution.

thanks for your understanding and help!

**Comment by PeterSurda** [comment]
> I said i merged the folders meaning, like i said in a few previous posts i did a clone of Pybitmessage to homedir. and then i copied it over to my existing pybitmessage (which included my settings) and i merged the two folders, meaning i ran this command:

Ok, but that would also have created the same problem. Perhaps even worse.

> Not sure why it happened to me, but doing a 'git pull' gives those conflicting files.

Because you added obsolete source files into the working source directory, breaking your repository. I'm surprised your PyBitmessage continued working at all. Git noticed that something was where it shouldn't be and started worrying that it pull would break it even more, refused to deal with it and wanted you to deal with it instead.

> However using git reset --hard FETCH_HEAD also worked for me perfectly, so i think this would be the easiest solution.

Yep, do that. Don't merge folders, unless you understand how git works.

**Comment by adham21** [comment]
Try this
`git stash save ""`
and try pull again

**Comment by rajucs** [comment]
> 
> 
> ```
> git stash
> git pull
> git stash apply
> ```
> 
> Just use stash

use stash will solve the problem

after using stash use git pull origin
