### ISSUE TITLE
v0.6.3: "Failed to build C PoW module. Please build it manually."

### ISSUE THREAD

**Issue by koeur2pi** [Bitmessage/PyBitmessage#991]
From v0.6.3, when I start pyBitmessage, I read at the bottom of the window : "Failed to build C PoW module. Please build it manually."

I had not this issue with v0.6.2
OS: Linux Mint 18.1 (ubunt 16.04)

I have no idea how to build manually the "C PoW module" (nor the idea of what this mean to not have C PoW module). Any URL or answer would be welcome.

**Comment by PeterSurda** [comment]
Short reply: `apt-get install libssl-dev g++`

Slightly longer reply: the recommended installation procedure is [using setup.py](https://bitmessage.org/wiki/Compiling_instructions#setuptools) which in most cases will explain to you what is missing.
