### ISSUE TITLE
PyBitmessage (v0.6.2) does not respect the maximum upload rate

### ISSUE THREAD

**Issue by koeur2pi** [Bitmessage/PyBitmessage#992]
Since PyBitmessage 0.6.2 (I have the feeling that it was not the case with previous versions), I see that my PyBitmessage does not respect the "maximum upload rate" (Network settings).

If set to 50 KB/s, I see it sometimes up to 200 KB/s ! (and most of the time between 50 and 100 KB/s).

OS: Linux (Mint)

**Comment by WhiteCat6142** [comment]
That may means "maximum upload rate per connections".  Then it mostly works nothing.

**Comment by PeterSurda** [comment]
It's mostly an averaging issue (it tries to limit the average, not the maximum) speed. The whole networking subsystem is being redesigned, it can't be addressed properly in the synchronous transfer model.

**Comment by PeterSurda** [comment]
Please check the latest code, since you're on linux, I presume you're running from source, so just check out the v0.6 branch.

**Comment by koeur2pi** [comment]
For me (Linux) it's better with the latest code : when it reach ~ 110% of the upload allowed, the upload decrease to zero (!) for several dozens of seconds (or minutes ?).

**Comment by PeterSurda** [comment]
Thanks for the feedback, I'll review it.

**Comment by PeterSurda** [comment]
Can't reproduce with current code, the speed shown still fluctuates but that's probably mainly due to how it calculates, it's an average so it may temporarily show higher and lower. The speed now doesn't drop to 0 anymore as long as it's uploading something.
