### ISSUE TITLE
Allow non-interactive build

### ISSUE THREAD

**Issue by orlitzky** [Bitmessage/PyBitmessage#993]
When building v0.6.2 on Gentoo, the setup.py crashes while waiting for the user to press return:

```
Press Return to continue
Traceback (most recent call last):
  File "setup.py", line 165, in <module>
    nothing = raw_input()
EOFError: EOF when reading a line
```

The code handles one possible exception there, a `NameError`, but it misses the `EOFError`. The following one-line patch allows the automatic build to proceed:

```
diff --git a/setup.py b/setup.py
index 2c769a6..166ab14 100644
--- a/setup.py
+++ b/setup.py
@@ -163,7 +163,7 @@ if __name__ == "__main__":
         print "Press Return to continue"
         try:
             nothing = raw_input()
-        except NameError:
+        except EOFError,NameError:
             pass

     here = os.path.abspath(os.path.dirname(__file__))
```

I'm not sure if that's the best way to fix it, but it does work =)

**Comment by PeterSurda** [comment]
Please try v0.6 branch and let me know if the problem still persists.

**Comment by PeterSurda** [comment]
Also thank you for the patch, I'll review it as well.
