### ISSUE TITLE
Strange behavior with onionbindip

### ISSUE THREAD

**Issue by dogtopus** [Bitmessage/PyBitmessage#997]
When tor hidden service was enabled, changing `onionbindip` to `127.0.0.1` will result in pybitmessage listen on `:::port` (expose the port to clearnet, which is not a correct behavior of a tor hidden service). Changing `onionbindip` to `::1` or `localhost` makes it listen on `::1:port` (listen locally, which is the correct behavior) but hangs later on exit.
EDIT: Changed `onionhostname` to `onionbindip`

**Comment by PeterSurda** [comment]
onionhosthame is an **onion** **hostname** of your hidden service, not an IP address. E.g. quzwelsuziwqgpt2.onion. See https://bitmessage.org/wiki/FAQ#How_do_I_setup_Bitmessage_as_a_hidden_service_on_Tor

**Comment by dogtopus** [comment]
> onionhosthame is an onion hostname of your hidden service, not an IP address
Oops, I mean onionbindip

**Comment by PeterSurda** [comment]
Do you have `socklisten` on? That would cause PyBitmessage to listen on all interfaces.

**Comment by dogtopus** [comment]
`sockslisten = False`

No it's off, otherwise PyBitmessage will just ignore my settings and not bind to `::1:port`

**Comment by dogtopus** [comment]
Changing `socket.AF_INET` to `socket.AF_INET6` in `src/class_singleListener.py`, line 52 seems to make PyBitmessage quit normally when `::1` was used as the `onionbindip`. Not sure if it breaks anything though

**Comment by PeterSurda** [comment]
Regarding the 127.0.0.1, I'll review it. Regarding ::1, I believe you but won't try to reproduce it because the new network subsystem that I'm working on will behave differently and won't have this problem (now the listening socket is blocking in a separate thread, the new one is non-blocking). However using ::1 as onionbindip may cause the hidden service not to work.

**Comment by PeterSurda** [comment]
So I can't reproduce it (the listening on everything). Just to make sure you're running the latest code, are you running the v0.6 branch? Also, what OS do you have?

**Comment by dogtopus** [comment]
Tried v0.6 branch, still no good :(
Using `127.0.0.1` as bind ip and PyBitmessage still binds on `::`
I am using Arch Linux with kernel version 4.10.13 and Python 2.7.13

**Comment by PeterSurda** [comment]
I can reproduce it on Arch now (on Ubuntu it works ok). I'll investigate.

**Comment by PeterSurda** [comment]
Works correctly for me now in fd2603247df24c5b35c496a3a2f5d7ad2e052334, if I had to guess it's triggered by a recent change in the linux kernel or glibc but that's not important. Thanks for reporting.
