### ISSUE TITLE
Does not launch

### ISSUE THREAD

**Issue by RyanSinger** [Bitmessage/PyBitmessage#998]
```
Ryans-MacBook-Pro:PyBitmessage ryan$ python src/bitmessagemain.py 
ERROR: The msgpack package is not available. PyBitmessage requires msgpack.
CRITICAL: PyBitmessage cannot start. One or more dependencies are unavailable.
Ryans-MacBook-Pro:PyBitmessage ryan$ brew install msgpack
Warning: msgpack-2.1.1 already installed
Ryans-MacBook-Pro:PyBitmessage ryan$ 
```

**Comment by PeterSurda** [comment]
You need python's msgpack module. There are several ones and any of them should work. I can't find my lion vm now so I can't tell you how I did it for the release, but it works on OSX as well. Try using pip, if you can't, get https://raw.githubusercontent.com/vsergeev/u-msgpack-python/master/umsgpack.py and save it as `msgpack.py` in the `src` directory.
