### ISSUE TITLE
Memory error; bad message?

### ISSUE THREAD

**Issue by ege1** [Bitmessage/PyBitmessage#999]
Hi,

I can't use the bitmessagecli (PyBitmessage/src/bitmessagecli.py) any more.
Listing the inbox times out and when I try to view the first message it dies. The same is for deleting the first message in the inbox (or when trying to "find" the first message?)

This is how it looks like:
````
python2 PyBitmessage/src/bitmessagecli.py

     ------------------------------
     | Bitmessage Daemon by .dok  |
     | Version 0.2.6 for BM 0.3.5 |
     ------------------------------

     API data successfully imported.

Type (H)elp for a list of commands.
>delete

Would you like to delete a message from the (I)nbox or (O)utbox?
> i
Traceback (most recent call last):
  File "PyBitmessage/src/bitmessagecli.py", line 1759, in <module>
    main()
  File "PyBitmessage/src/bitmessagecli.py", line 1754, in main
    UI((raw_input('>').lower()).replace(" ", ""))
  File "PyBitmessage/src/bitmessagecli.py", line 1599, in UI
    inboxMessages = json.loads(api.getAllInboxMessages())
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1476, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
  File "/usr/lib/python2.7/xmlrpclib.py", line 824, in end
    return f(self, join(self._data, ""))
  File "/usr/lib/python2.7/string.py", line 318, in join
    return sep.join(words)
MemoryError
```
I can see that first the bitmessagemain process is using nearly 2 GB of RAM and afterwards the bitmessagecli raises, until it dies.

I'm running on the latest commit of the master branch; will try with v0.6, now.

Is there anything else I could/should provide?
System is Ubuntu 14.04 with 2 GB of RAM and 1 GB swap

**Comment by PeterSurda** [comment]
Try the v0.6 branch. The master branch has excessive memory usage.

**Comment by ege1** [comment]
Hi Peter,

Thanks for the fast reply.

I can't see any difference:

````
~/PyBitmessage$ git status
On branch v0.6
Your branch is up-to-date with 'origin/v0.6'
````
If I try to read any message, first bitmessagemain, afterwards the cli are consuming too much memory.
Later on there is often no connection possible any more and I've to kill -9 bitmessagemain as it refuses to stop.
````
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                        
 4558 erik      20   0 2545468 1.179g   3088 S 36.9 61.8   0:16.78 /usr/bin/python2.7 /home/erik/PyBitmessage/src/bitmessagemain.py                                                                               

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                        
 4644 erik      20   0 2333372 1.689g    912 D  5.0 88.5   0:05.60 python2 PyBitmessage/src/bitmessagecli.py                                                                                                      
````
The debug.log is a bit too quiet and only states some connection errors:

````
2017-05-14 11:41:37,195 - ERROR - Timeout during protocol initialisation
2017-05-14 11:42:02,908 - ERROR - Timeout during protocol initialisation
````
For what its worth, the messages.dat is 326M big.

Any hints how I get that back to working? Removing the messages.dat and loosing the last received messages?

Kind regards,

Erik

**Comment by PeterSurda** [comment]
It looks like your inbox is too big to fit into the API memory. In that case, it's better to use the sqlite command line client to delete the excessive messages from inbox.

**Comment by ege1** [comment]
OK, raising the VM memory to 3 GB doesn't work, also
 1321 erik      20   0 3417804 2.512g   1212 S  0.0 88.2   0:23.90 python2 PyBitmessage/src/bitmessagecli.py

OK, wasn't aware it's an sqlite db ;-)
Will try that, thanks

**Comment by ege1** [comment]
Are deleted messages still in the "inbox" table?

**Comment by ege1** [comment]
OK, there were two "bad" messages in the inbox table. After I deleted them (and before that, the trash ones), all is fine now.

**Comment by PeterSurda** [comment]
There was a sort of attack on Saturday which sent a message with a high compression ratio to the general chan. After decompression it was about 256MB big. Since it needs to fits into the memory during processing, this created problems on systems that are low on memory. I'll probably introduce some configurable size limits that people can adjust.

**Comment by ege1** [comment]
OK, that's what I guessed. It happened again, today (but I didn't look at when the message was sent).
So "low on memory" is below 4 GB of memory. At least with 3 GB it crashes, still.

**Comment by PeterSurda** [comment]
Try the latest v0.6, I now introduced a decompression limit (configurable, defaults to 1MB).

**Comment by ege1** [comment]
OK, updated.

Thanks,
Erik

**Comment by PeterSurda** [comment]
I'm closing this for the time being but when it happens again feel free to reopen.
